#!/usr/bin/env python3
"""Render only the marked laboratory block from verified_lab.json (optional)."""
from pathlib import Path
from html import escape
from math import log10
from urllib.parse import quote
import json
import re

HERE=Path(__file__).resolve().parent
PAGE=HERE.parent/'math-behind-poker.html'
DATA=json.loads((HERE/'verified_lab.json').read_text())
SUITS={'s':('♠','spades'),'h':('♥','hearts'),'d':('♦','diamonds'),'c':('♣','clubs')}
CATEGORY=['High card','One pair','Two pair','Three of a kind','Straight','Flush','Full house','Four of a kind','Straight flush']
SCENARIO=DATA['scenarios'][0]
REFERENCE=next(p for p in SCENARIO['replays']['20260926'] if p['n']==1000)


def hand(codes,label='Example cards'):
    cards=[]
    if isinstance(codes,str):codes=codes.split()
    for code in codes:
        r,s=code[:-1],code[-1];glyph,name=SUITS[s]
        rank={'A':'Ace','K':'King','Q':'Queen','J':'Jack'}.get(r,r)
        cards.append(f'<span class="playing-card {"red" if s in "hd" else "black"}" role="img" aria-label="{rank} of {name}" data-card="{code}"><span class="corner" aria-hidden="true">{r}<small>{glyph}</small></span><span class="pip" aria-hidden="true">{glyph}</span><span class="corner bottom" aria-hidden="true">{r}<small>{glyph}</small></span></span>')
    return f'<div class="hand lab-hand-row" role="group" aria-label="{label}" data-hand="{" ".join(codes)}">'+''.join(cards)+'</div>'


def equation(text):return '<div class="math-equation">'+text+'</div>'


def scenario_options():return ''.join(f'<option value="{s["id"]}">{s["label"]}</option>' for s in DATA['scenarios'])


def convergence_svg():
    exact=SCENARIO['by_river_flop']['decimal']
    points=[p for p in SCENARIO['replays']['20260926'] if p['n']<=1000]
    path=' '.join(f'{"M" if i==0 else "L"}{58+(log10(p["n"])-1)*180:.3f},{235-p["estimate"]*210:.3f}' for i,p in enumerate(points))
    result=['<svg id="simulation-chart" class="simulation-chart" viewBox="0 0 640 290" role="img" aria-labelledby="sim-chart-title sim-chart-desc"><title id="sim-chart-title">Seeded simulation estimate versus exact probability</title><desc id="sim-chart-desc">The horizontal axis is logarithmic in completed trials, from 10 to 10,000. The vertical axis is target-hit probability from zero to one. The solid estimated path fluctuates around a dashed exact line. The checkpoint table supplies the numerical values.</desc>']
    for p in [0,.25,.5,.75,1]:
        y=235-210*p
        result.append(f'<path d="M58 {y}H598" class="sim-grid"/><text x="48" y="{y+4}" text-anchor="end">{p*100:g}%</text>')
    for n in [10,100,1000,10000]:
        x=58+(log10(n)-1)*180
        result.append(f'<text x="{x}" y="258" text-anchor="middle">{n:,}</text>')
    result.append(f'<path id="sim-exact-line" d="M58 {235-exact*210:.3f}H598" class="sim-exact"/><path id="sim-estimate-line" d="{path}" class="sim-estimate"/><text x="320" y="281" text-anchor="middle">Trials n · each equal horizontal step is ×10</text></svg>')
    return ''.join(result)


parts=['''<div class="laboratory" id="laboratory">
<div class="part-heading"><span class="stage-label">Part III · The mathematical laboratory</span><h2>Calculate. Sample. Compare.</h2><p>The same card patterns now become experiments: specify an event, calculate its probability, and study what a finite sample can tell you.</p></div>
<nav class="toc" aria-label="Laboratory contents"><a href="#exact-lab">18 · Exact draws</a><a href="#pot-odds">19 · Pot odds &amp; EV</a><a href="#monte-carlo">20 · Monte Carlo</a><a href="#sampling-uncertainty">21 · Uncertainty</a><a href="#enumeration-simulation">22 · Two methods</a><a href="#state-space">23 · State spaces</a><a href="#math-pipeline">24 · The pipeline</a><a href="#notation">25 · Notation</a><a href="#reproducibility">26 · Reproduce</a></nav>
<section class="chapter" id="exact-lab"><span class="stage-label">18 · A controlled draw calculator</span><h2>Choose the event before calculating its chance.</h2><p>Use one of five curated examples. Each out is a distinct unseen card that reaches the stated target. The two-card result counts <strong>at least one of the current outs</strong>; it does not include every alternative runner–runner improvement or measure the probability of winning.</p>
<div class="experiment exact-experiment"><div class="lab-controls-row" id="exact-controls" hidden><div><label for="exact-scenario">Target scenario</label><select id="exact-scenario">'''+scenario_options()+'''</select></div><div><label for="exact-street">Available information</label><select id="exact-street"><option value="flop">After flop · two board cards to come</option><option value="turn">After a shown miss on turn · river remains</option></select></div></div>
<div class="known-layout"><div><span class="small-label">Private hole cards</span><div id="exact-hole">'''+hand(SCENARIO['hole'])+'''</div></div><div><span class="small-label">Shared flop</span><div id="exact-flop">'''+hand(SCENARIO['flop'])+'''</div></div><div id="exact-turn-wrap" hidden><span class="small-label">Observed turn · misses the fixed outs</span><div id="exact-turn"></div></div></div>
<p id="exact-target">At least one more heart: enough for a heart flush.</p><div class="out-strip"><span class="small-label">Distinct current outs</span><div id="exact-outs">'''+hand(SCENARIO['outs'],'Nine unseen hearts')+'''</div></div>
<p id="exact-known">5 known cards → U = 47 unseen cards; o = 9 outs.</p>
<div class="exact-results"><div><h3 id="next-label">Next card · turn</h3><p id="exact-next"><strong>9/47</strong> = 0.191489… ≈ <strong>19.149%</strong></p></div><div><h3 id="river-label">At least one out by river</h3><p id="exact-river"><strong>378/1081</strong> = 0.349676… ≈ <strong>34.968%</strong></p></div></div>
<div id="exact-equation">'''+equation('<span>P(next hit) = o/U = 9/47</span><span>P(≥1 hit in two cards) = 1 − [(U − o)(U − o − 1)]/[U(U − 1)]</span><span>= 1 − (38 × 37)/(47 × 46) = 378/1081</span>')+'''</div><p class="formula-key"><strong>o</strong> is the fixed number of current outs; <strong>U</strong> is the number of unseen identities. Both cards are sampled without replacement. Fractions are exact; decimals and percentages are rounded.</p><p id="exact-caution" class="note">Making this flush does not rule out an opponent’s full house or four of a kind.</p><p id="exact-status" class="small" role="status" aria-live="polite">Flush draw after flop. The results describe completing the target, not winning.</p></div>
<p class="small">The turn option reveals a specific non-out and removes it from the deck. The current fixed outs remain unseen, giving U = 46 and just one draw left. The separate overcard example uses A♠ K♦ on Q♥ 7♣ 2♠: three remaining aces plus three remaining kings give six nominal outs to pairing a hole-card rank.</p></section>
<section class="chapter" id="pot-odds"><span class="stage-label">19 · Translate probabilities into net payoffs</span><h2>Pot odds: be precise about what is already in the pot.</h2>
<p>Consider a <strong>heads-up terminal decision</strong>: one opponent has bet, calling ends all betting, and the outcome is either win or loss. There are no ties, fees, side pots, future bets, or later folds. All amounts already committed before this decision are treated as sunk.</p>
<div class="pot-story"><div><span>Pot before the bet</span><strong>$100</strong></div><b aria-hidden="true">+</b><div><span>Opponent’s bet</span><strong>$25</strong></div><b aria-hidden="true">=</b><div><span>Available before our call</span><strong>$125</strong></div><b aria-hidden="true">+</b><div><span>Our call</span><strong>$25</strong></div><b aria-hidden="true">=</b><div><span>Final pot</span><strong>$150</strong></div></div>
<p>Calling risks $25. Winning returns the $150 pot, but $25 is our own call coming back: the <strong>net win is +$125</strong>. Losing costs <strong>−$25</strong>. Folding has incremental payoff zero in this model.</p>
'''+equation('<span>Reward : risk = 125 : 25 = <strong>5 : 1</strong></span><span>Break-even probability = 25/150 = <strong>1/6 ≈ 16.667%</strong></span>')+'''
<p>Reward-to-risk odds compare what can be gained to what can be lost. Break-even probability divides the call by the <em>final</em> pot, including that call. These two denominators answer different questions.</p>
<div class="experiment pot-experiment"><div class="lab-controls-row" id="pot-controls" hidden><div><label for="pot-before">Pot before opponent bet ($)</label><input id="pot-before" type="number" min="0" max="10000" step="1" value="100" inputmode="numeric"></div><div><label for="pot-bet">Opponent bet = our call ($)</label><input id="pot-bet" type="number" min="0" max="10000" step="1" value="25" inputmode="numeric"></div><div class="probability-control"><label for="pot-probability">Estimated win probability: <output id="pot-probability-label" for="pot-probability">20.0%</output></label><input id="pot-probability" type="range" min="0" max="100" step="0.1" value="20"></div><div class="preset-controls"><button type="button" id="pot-positive">+EV example</button><button type="button" id="pot-negative">−EV example</button><button type="button" id="pot-reset">Reset</button></div></div>
<p id="pot-error" class="lab-error" role="status" hidden></p>
<div id="pot-results"><div class="pot-composition" role="img" id="pot-composition" aria-label="Final pot: 100 dollars previously in pot, 25 dollars opponent bet, 25 dollars call"><span id="pot-base-bar" style="flex:100">Before bet</span><span id="pot-bet-bar" style="flex:25">Bet</span><span id="pot-call-bar" style="flex:25">Call</span></div><dl class="pot-metrics"><div><dt>Amount risked C</dt><dd id="pot-risk">$25.00</dd></div><div><dt>Net win R</dt><dd id="pot-reward">$125.00</dd></div><div><dt>Final pot F</dt><dd id="pot-final">$150.00</dd></div><div><dt>Reward : risk</dt><dd id="pot-ratio">5.000 : 1</dd></div><div><dt>Break-even p*</dt><dd id="pot-threshold">16.667%</dd></div><div><dt>Estimated EV</dt><dd id="pot-ev">+$5.00</dd></div></dl><p id="pot-reading" class="comparison-status" role="status">At 20% win probability, the modeled EV is +$5.00 relative to folding. This describes an assumed payoff distribution, not a guaranteed outcome.</p>
<div id="pot-worked">'''+equation('<span>R = P₀ + B = 100 + 25 = 125</span><span>C = B = 25; F = R + C = 150</span><span>EV = pR − (1 − p)C = pF − C</span><span>= 0.20 × 125 − 0.80 × 25 = <strong>+$5.00</strong></span><span>EV = 0 ⇒ p* = C/F = 25/150</span>')+'''</div></div>
<p class="formula-key"><strong>P₀</strong> = pot before the bet; <strong>B</strong> = opponent bet; <strong>C</strong> = call cost (equal to B here); <strong>R</strong> = net reward on winning; <strong>F</strong> = final pot; <strong>p</strong> = assumed win probability; <strong>p*</strong> = break-even probability. Under the no-tie assumption, win probability equals equity, the expected fraction of the pot received.</p></div>
<h3>Expected value keeps the signs.</h3>
'''+equation('<span>EV = P(win) × payoff_if_win + P(loss) × payoff_if_loss</span><span>= p(+R) + (1 − p)(−C)</span>')+'''
<div class="ev-contrasts"><div><span class="small-label">Positive hypothetical EV</span><h3>p = 20%</h3><p>0.20(+125) + 0.80(−25)<br>= 25 − 20 = <strong>+$5</strong></p></div><div><span class="small-label">Negative hypothetical EV</span><h3>p = 10%</h3><p>0.10(+125) + 0.90(−25)<br>= 12.5 − 22.5 = <strong>−$10</strong></p></div></div>
<aside class="note"><strong>Changing the model changes the calculation.</strong> A flush-completion probability cannot simply stand in for p. Winning probability must account for opposing hands and stronger outcomes. Future betting or split pots require additional outcomes and payoffs. These controls explore a specified mathematical model.</aside></section>
<section class="chapter" id="monte-carlo"><span class="stage-label">20 · Monte Carlo: estimate by sampling</span><h2>Repeat a fully specified experiment.</h2><ol class="simulation-method"><li><strong>Fix the known cards.</strong> Remove your hole cards and flop from the 52-card deck.</li><li><strong>Complete the board.</strong> Sample distinct turn and river cards from the 47 unseen cards, without replacement.</li><li><strong>Evaluate.</strong> Test the fixed-out event and select the strongest of all 21 five-card subsets.</li><li><strong>Repeat.</strong> Restore the same unseen deck before each new trial. Count target hits and best-hand categories.</li></ol>
<p>Within one trial the two draws depend on each other. Across trials we model independent repetitions of the same experiment. A seeded pseudorandom generator makes the demonstration reproducible; it approximates the random sampling in that model.</p>
<div class="experiment simulation-experiment"><div class="lab-controls-row" id="simulation-controls" hidden><div><label for="sim-scenario">Experiment · always starts at the flop</label><select id="sim-scenario">'''+scenario_options()+'''</select></div><div><label for="sim-seed">Reproducible sample</label><select id="sim-seed"><option value="20260926">Seed 20260926</option><option value="17">Seed 17</option><option value="314159">Seed 314159</option></select></div><div><label for="sim-size">Trials in this run</label><select id="sim-size"><option value="100">100</option><option value="1000" selected>1,000</option><option value="10000">10,000</option></select></div><div class="preset-controls"><button type="button" id="sim-run">Run simulation</button><button type="button" id="sim-stop" disabled>Stop</button><button type="button" id="sim-reset">Clear results</button></div></div>
<div class="known-layout"><div><span class="small-label">Fixed hole cards</span><div id="sim-hole">'''+hand(SCENARIO['hole'])+'''</div></div><div><span class="small-label">Fixed flop</span><div id="sim-flop">'''+hand(SCENARIO['flop'])+'''</div></div></div><p id="sim-event">Event measured: at least one of the nine currently unseen hearts appears on the turn or river.</p><div class="simulation-metrics"><div><span>Completed trials n</span><strong id="sim-n">1,000</strong></div><div><span>Target hits h</span><strong id="sim-hits">'''+str(REFERENCE['hits'])+'''</strong></div><div><span>Estimate p̂ = h/n</span><strong id="sim-estimate">'''+f'{100*REFERENCE["estimate"]:.3f}%'+'''</strong></div><div><span>Exact fixed-out probability</span><strong id="sim-exact">34.968%</strong></div><div><span>Estimated standard error</span><strong id="sim-se">'''+f'{100*REFERENCE["se"]:.3f} pp'+'''</strong></div></div>
<p id="sim-status" role="status" class="small">Saved reference run: seed 20260926, 1,000 trials. Run the same settings to reproduce it. No simulation runs automatically.</p><progress id="sim-progress" value="1000" max="1000" aria-label="Completed simulation trials"></progress>
<figure class="convergence-figure">'''+convergence_svg()+'''<figcaption><span class="line-key estimate-key">Solid: simulated estimate</span> <span class="line-key exact-key">Dashed: exact probability</span><br>The horizontal scale is logarithmic. Error can rise as well as fall along the path; convergence need not be monotonic.</figcaption></figure>
<details class="checkpoint-details"><summary>Numerical convergence checkpoints</summary><div class="math-table-wrap"><table><caption>Same seed, nested sample prefixes; percentages are rounded</caption><thead><tr><th scope="col">Trials</th><th scope="col">Hits</th><th scope="col">Estimate</th><th scope="col">SE (pp)</th></tr></thead><tbody id="sim-checkpoints">''']
for p in SCENARIO['replays']['20260926']:
    if p['n']<=1000:parts.append(f'<tr><th scope="row">{p["n"]:,}</th><td>{p["hits"]}</td><td>{100*p["estimate"]:.3f}%</td><td>{100*p["se"]:.3f}</td></tr>')
parts.append('''</tbody></table></div></details>
<details class="category-details"><summary>Best-hand categories: sampled versus exactly enumerated</summary><p class="small">Every completed board is classified by its best five cards. These are <em>conditional seven-card</em> frequencies for this fixed flop and hole cards; they are different from the earlier unconditional five-card table. Each column counts mutually exclusive categories.</p><div class="math-table-wrap"><table><caption>Observed best-hand frequencies versus all 1,081 runouts</caption><thead><tr><th scope="col">Category</th><th scope="col">Sample count</th><th scope="col">Sample %</th><th scope="col">Exact %</th></tr></thead><tbody id="sim-categories">''')
for i in range(8,-1,-1):parts.append(f'<tr><th scope="row">{CATEGORY[i]}</th><td>{REFERENCE["categories"][i]}</td><td>{100*REFERENCE["categories"][i]/1000:.3f}%</td><td>{100*SCENARIO["exact_category_counts"][i]/1081:.3f}%</td></tr>')
parts.append('''</tbody></table></div></details>
<div id="sim-last" class="last-trial" hidden><span class="small-label">Last completed trial · sampled turn and river</span><div id="sim-runout"></div><span class="small-label">Best five selected from that trial’s seven cards</span><div id="sim-best"></div><p id="sim-last-label" class="small"></p></div>
<p class="small">Each Run starts the selected seed from its beginning. Thus 100 trials are the prefix of 1,000, and 1,000 are the prefix of 10,000 for that same scenario and seed. Change the seed to compare different reproducible samples. The page yields between short batches and stops scheduling work when complete or stopped.</p></div>
'''+equation('<span>p̂ = h/n</span>')+f'''<p class="formula-key"><strong>h</strong> is the number of target hits; <strong>n</strong> is the number of trials; <strong>p̂</strong> (“p-hat”) is the empirical proportion. In the saved run, h = {REFERENCE['hits']}, n = 1,000, and p̂ = {REFERENCE['hits']}/1,000 = {REFERENCE['estimate']:.3f}, compared with the exact 378/1,081 ≈ 0.349676.</p>
<p><strong>Law-of-large-numbers intuition:</strong> for independent repetitions with fixed success probability, the empirical proportion approaches that probability as the sample grows. It does not promise a smaller error after every trial, and a simulation does not prove the exact fraction. Here enumeration provides the comparison standard.</p></section>
<section class="chapter" id="sampling-uncertainty"><span class="stage-label">21 · Sampling uncertainty</span><h2>A sample estimate has a scale of fluctuation.</h2><p>Code each trial as 1 for a target hit and 0 for a miss: a <strong>Bernoulli outcome</strong>. Under the independent-trial model, the standard error is the standard deviation of p̂ across repeated samples of size n.</p>
'''+equation('<span>SE(p̂) = √[p(1 − p)/n]</span><span>Estimated SE(p̂) ≈ √[p̂(1 − p̂)/n]</span>')+'''<p class="formula-key"><strong>p</strong> is the true event probability; <strong>p̂</strong> is its sample estimate; <strong>n</strong> is the number of independent trials. The first expression is the theoretical standard error. The second substitutes p̂ when p is unknown. Both use probability units; multiply by 100 for <em>percentage points</em> (pp).</p>
<div class="uncertainty-visual"><p>For the exact flush probability p = 378/1,081, each interval below spans <strong>p ± one theoretical SE</strong>. These are illustrations of sampling scale, not guaranteed bounds or 95% confidence intervals.</p>''')
for point in DATA['uncertainty']:
    p=378/1081;se=point['se']
    parts.append(f'<div class="uncertainty-row"><strong>n = {point["n"]:,}</strong><div class="uncertainty-track" role="img" aria-label="Mean 34.968 percent, plus or minus {100*se:.3f} percentage points"><span class="uncertainty-band" style="left:{100*(p-se)/.7:.5f}%;width:{200*se/.7:.5f}%"></span><span class="uncertainty-center" style="left:{100*p/.7:.5f}%"></span></div><span>± {100*se:.3f} pp</span></div>')
parts.append('''<div class="uncertainty-axis"><span>0%</span><span>Same probability axis for all three rows</span><span>70%</span></div></div>
'''+equation('<span>n = 100: √[(378/1081)(703/1081)/100] ≈ 0.047687 ≈ <strong>4.769 pp</strong></span><span>n = 10,000: SE ≈ 0.004769 ≈ <strong>0.477 pp</strong></span>')+'''<p>Multiply the sample size by 100 and the standard error shrinks by √100 = 10. Achieving half the standard error requires about four times as many trials. More trials reduce sampling noise; they do not repair an incorrectly defined event or an unrealistic model.</p><aside class="note"><strong>A plug-in estimate has limits.</strong> If a small sample contains no hits, p̂ = 0 makes the plug-in SE zero. That does not prove the true probability is zero. Normal-approximation error summaries are unreliable for rare events or small samples; all uncertainty here is about the specified sampling model.</aside></section>
<section class="chapter" id="enumeration-simulation"><span class="stage-label">22 · Two computational approaches</span><h2>List the possibilities, or sample them.</h2><div class="methods-comparison"><article><h3>Exact enumeration</h3><p>List every relevant outcome and evaluate each once. For a fixed flop and your hole cards, there are only C(47, 2) = 1,081 unordered turn–river pairs.</p><ul><li>Exact and deterministic under the stated uniform model.</li><li>No Monte Carlo sampling error.</li><li>Work grows with the number of states and the cost per evaluation.</li></ul><p class="small">For this laboratory, full enumeration is practical and supplies the reference values.</p></article><article><h3>Monte Carlo</h3><p>Sample from the same outcome distribution and replace exact proportions with empirical frequencies.</p><ul><li>Flexible when the outcome model becomes more complex.</li><li>Work can be limited by a chosen trial budget.</li><li>Sampling error remains; rare events may need many trials.</li></ul><p class="small">Useful in computational statistics for estimating probabilities and expectations when exhaustive sums are expensive.</p></article></div><p>The correct distribution matters in both methods. If outcomes are not equally likely, enumeration needs probability weights and simulation must sample from those weights. A deterministic seed supports reproducibility, not proof of accuracy.</p></section>
<section class="chapter" id="state-space"><span class="stage-label">23 · Combinatorial growth</span><h2>The size depends on what a “state” records.</h2><div class="state-ladder">''')
states=[('1,081','C(47, 2)','Unordered turn–river cards, given your hole cards and flop. Order is irrelevant to the final hand.'),('1,070,190','C(47, 2) × C(45, 2)','An unordered runout plus one opponent’s unordered hole pair, disjoint from the runout, given those same five known cards.'),('2,598,960','C(52, 5)','All unordered five-card sets from a full deck.'),('133,784,560','C(52, 7)','All unordered seven-card sets from a full deck; each has 21 five-card candidates.')]
for value,formula,meaning in states:parts.append(f'<div class="state-row"><strong>{value}</strong><div><b>{formula}</b><p>{meaning}</p></div></div>')
parts.append('''</div><p>The examples have different information assumptions; they are not successive stages of one identical sample space. In the second row, 47 cards remain initially, then 45 after selecting the runout. This counts assignments of cards, not betting histories or player strategies.</p>'''+equation('<span>C(52, 7) = 52!/(7!45!) = <strong>133,784,560</strong></span><span>C(47, 2) × C(45, 2) = 1,081 × 990 = <strong>1,070,190</strong></span>')+'''<p>These finite spaces are not inherently impossible to compute. Their size, the evaluation algorithm, and the extra information represented in each state determine the work. That is why choosing a precise state description is part of the mathematics.</p></section>
<section class="chapter" id="math-pipeline"><span class="stage-label">24 · The whole mathematical pipeline</span><h2>From a deck to an estimate you can interpret.</h2><ol class="poker-pipeline">''')
for title,desc,href in [('52-card deck','Define the objects.','deck-math'),('Combinations','Count unordered choices.','total-hands'),('Five-card ranking','Classify patterns.','hierarchy'),('Best five of seven','Maximize hand value.','seven-card-math'),('Conditional probability','Update the sample space.','conditional-math'),('Outs','Specify useful unseen cards.','exact-lab'),('Expected value','Weight signed payoffs.','pot-odds'),('Monte Carlo','Estimate by repeated sampling.','monte-carlo'),('Uncertainty','Quantify sampling fluctuation.','sampling-uncertainty')]:
    parts.append(f'<li><a href="#{href}">{title}</a><span>{desc}</span></li>')
parts.append('''</ol></section>
<section class="chapter" id="notation"><span class="stage-label">25 · Notation at a glance</span><h2>A compact mathematical reference.</h2><dl class="notation-list"><div><dt>C(n, k)</dt><dd>Number of unordered k-element subsets of n distinct objects, without replacement.</dd></div><div><dt>P(A)</dt><dd>Probability of event A under the stated model.</dd></div><div><dt>P(A | B)</dt><dd>Probability of A conditional on information B, with P(B) &gt; 0.</dd></div><div><dt>o and U</dt><dd>Number of distinct current outs and number of unseen cards. Here P(next fixed out) = o/U.</dd></div><div><dt>best_hand(S)</dt><dd>Maximum hand value rank(T) among five-card subsets T of the available set S.</dd></div><div><dt>EV</dt><dd>Expected signed net payoff: Σᵢ pᵢxᵢ, with outcome probabilities pᵢ and net payoffs xᵢ.</dd></div><div><dt>p and p*</dt><dd>Assumed success or win probability, depending on the stated event; p* is the terminal pot model’s break-even value C/F.</dd></div><div><dt>p̂ = h/n</dt><dd>Observed hit proportion: h successes in n simulation trials. Here n counts trials; in C(n, k), it counts available objects.</dd></div><div><dt>SE(p̂)</dt><dd>Standard deviation of the sample proportion across repeated independent samples; estimated by √[p̂(1 − p̂)/n].</dd></div><div><dt>P₀, B, C, R, F</dt><dd>Pot before the opponent bet, bet, call cost, net winning reward, and final pot. In this model C = B, R = P₀ + B, F = R + C.</dd></div></dl></section>
<section class="chapter" id="reproducibility"><span class="stage-label">26 · Reproducibility and limits</span><h2>The numbers can be checked.</h2><p>The exact results use exhaustive enumeration. Simulation paths use a documented seed and a fixed deck order; replaying the same scenario, seed, and trial count produces the same counts. No browser experiment runs until requested.</p><details><summary>Verification scripts and their roles</summary><ul class="repro-files"><li><a href="math-behind-poker/verify_math.py">verify_math.py</a> independently enumerates all 2,598,960 five-card hands and checks the combinatorial formulas, fixed-out probabilities, Bayes example, and introductory EV.</li><li><a href="math-behind-poker/verify_lab.py">verify_lab.py</a> uses Python to enumerate all 1,081 runouts for each of five scenarios and reproduce 15 seeded 10,000-trial sequences.</li><li><a href="math-behind-poker/verify_lab.cjs">verify_lab.cjs</a> checks the browser engine against Python: every complete-board ranking, seeded checkpoint, exact fraction, pot example, and standard error.</li><li><a href="math-behind-poker/audit_poker.py">audit_poker.py</a> audits displayed mathematics, poker examples, page structure, relative links, and the index entry.</li><li><a href="math-behind-poker/verified_math.json">verified_math.json</a> and <a href="math-behind-poker/verified_lab.json">verified_lab.json</a> contain the reproducible reference results.</li><li><a href="math-behind-poker/poker-engine.js">poker-engine.js</a> is the local ranking, probability, EV, and seeded sampling implementation used by the browser and Node checks.</li></ul><pre><code>python3 research/math-behind-poker/verify_math.py
python3 research/math-behind-poker/verify_lab.py
node research/math-behind-poker/verify_lab.cjs
python3 research/math-behind-poker/audit_poker.py</code></pre><p class="small">Python uses only its standard library; Node uses only built-in modules. The optional <a href="math-behind-poker/render_math.py">render_math.py</a> and <a href="math-behind-poker/render_lab.py">render_lab.py</a> regenerate their marked static sections, including figures. Neither is required for GitHub Pages hosting.</p></details>
<details><summary>Sampling assumptions and implementation</summary><p>Each trial samples an ordered pair of distinct cards using a seeded Mulberry32 generator and rejection when mapping a 32-bit word to a deck index. Each unordered pair has two orders, so its exact probability is 1/1,081. The Python verifier independently implements the integer arithmetic and checks the JavaScript results.</p><p>Cards are restored between trials, never between the turn and river in one trial. The engine evaluates all 21 five-card subsets, including the ace-low straight exception. Runs are capped at 10,000 trials and executed in short scheduled batches; stopping, changing the experiment, or leaving the page cancels pending work.</p><p class="small">The probability and EV models do not infer an opponent’s strategy or promise profit. Optional typography reuses the research site’s Google Fonts with local system-font fallbacks; all cards, diagrams, equations, and controls work without an external asset service.</p></details>
<p class="next-phase">The essential habit: define the event, state the information, count or sample consistently, then interpret the uncertainty.</p></section>
</div>''')
# Keep only data needed by UI; the full reference file remains downloadable.
ui={'scenarios':[{k:v for k,v in s.items() if k not in ['replays','exact_rank_digest']} for s in DATA['scenarios']],
    'checkpoints':DATA['checkpoints'],'reference':REFERENCE,
    'reference_points':[p for p in SCENARIO['replays']['20260926'] if p['n']<=1000]}
parts.append('<script type="application/json" id="poker-lab-data">'+json.dumps(ui,ensure_ascii=False).replace('</','<\\/')+'</script>')
block='\n<!-- BEGIN GENERATED LABORATORY: render_lab.py -->\n'+'\n'.join(parts)+'\n<!-- END GENERATED LABORATORY -->\n'
text=PAGE.read_text()
if 'rel="icon"' not in text:
    icon = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="7" fill="#153f33"/><text x="8" y="30" font-size="29" fill="#fffdf9" font-family="serif">∑</text></svg>'
    text=text.replace('</title>', '</title>\n<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,'+quote(icon,safe='')+'">', 1)
if '<!-- BEGIN GENERATED LABORATORY:' in text:
    text=re.sub(r'\n<!-- BEGIN GENERATED LABORATORY:.*?<!-- END GENERATED LABORATORY -->\n',lambda _:block,text,flags=re.S)
else:
    marker='<!-- Phase 3 insertion point: interactive decision and simulation laboratory. -->'
    assert marker in text
    text=text.replace(marker,marker+block,1)
if 'href="math-behind-poker/lab.css"' not in text:
    text=text.replace('<script defer src="math-behind-poker/math.js"></script>', '<script defer src="math-behind-poker/math.js"></script>\n<link rel="stylesheet" href="math-behind-poker/lab.css">\n<script defer src="math-behind-poker/poker-engine.js"></script>\n<script defer src="math-behind-poker/lab.js"></script>')
text=text.replace('A visual mathematical guide · Phases 1–2 draft','A visual mathematical guide · From cards to computation')
text=text.replace('<a href="#mathematics">Part II · The mathematics ↓</a></nav>','<a href="#mathematics">Part II · The mathematics ↓</a><a href="#laboratory">Part III · The laboratory ↓</a></nav>')
text=text.replace('Bayes’ rule, and expected value.','Bayes’ rule, expected value, Monte Carlo simulation, and sampling uncertainty.')
text=text.replace('JavaScript adds optional ordering, subset, draw-selection, and comparison controls.','JavaScript adds optional comparisons, calculators, and seeded simulations. The saved reference examples remain visible without it.')
PAGE.write_text(text)
print('Rendered the laboratory in',PAGE.name)
