"""Authored mathematical explanations. Numbers are inserted by build_chapter.py."""
CONTENT = [
{
'origin': '''Least squares was published by Legendre in 1805; Gauss's 1809 treatment linked squared errors to a probability model. Astronomers needed a way to reconcile inconsistent measurements. A dynamic regression adds an earlier outcome to explain persistence. This chapter's economic-size and distance variables resemble empirical gravity predictors; they do not create a causal or general-equilibrium structural gravity model. See <a href="https://mathshistory.st-andrews.ac.uk/HistTopics/Least_squares/">University of St Andrews history of least squares</a> and the <a href="https://www.statsmodels.org/stable/examples/notebooks/generated/ols.html">statsmodels OLS treatment</a>.''',
'intuition': '''Ask: can last year's wheat exports and economic characteristics explain next year's exports? A coefficient on last year's log trade lets established relationships persist. Other coefficients add or subtract predicted log trade. The model learns a single plane, so the response to an economic characteristic is the same everywhere unless an interaction is explicitly supplied.''',
'notation': [('V_it','Observed scalar trade in dollars','Cell i at origin year t'),('y_it = log(1+V_it)','Transformed scalar outcome','Zero becomes zero'),('z_it','Column vector of standardized inputs','14 economic inputs, lag, one HS2 dummy'),('b, a, rho','Learned slopes, intercept, raw-lag slope','OLS coefficients; rho is standardized-lag coefficient / lag SD'),('A, theta','Design matrix and coefficient vector','168 × 17 including intercept; 17 coefficients'),('epsilon_it','Unobserved additive log error','Mismatch after conditioning on inputs')],
'math': r'''<p>Start with a conditional-mean assumption in transformed units. The intercept is the prediction at zero standardized covariates. A lag is an earlier observation of the same exporter–destination–heading cell, not an arbitrary preceding CSV row.</p>
\[y_{i,t+1}=a+\rho y_{i,t}+\beta^{\mathsf T}x_{i,t}+\gamma_{HS2(i)}+\epsilon_{i,t+1}.\tag{1.1}\]
<p>For fitting, put the intercept, standardized lag and encoded predictors into each row of A. If the conditional mean is linear and errors have mean zero given A, theta describes that mean. Independent Gaussian errors with common variance give a density proportional to exp(−error²/(2 sigma²)); maximizing their product therefore minimizes squared residuals. Gaussianity is a motivation, not a requirement for computing least squares; trade-panel errors need not actually be independent or Gaussian.</p>
\[L(\theta)=\sum_{i=1}^{n}(y_i-A_i\theta)^2=(y-A\theta)^{\mathsf T}(y-A\theta).\tag{1.2}\]
<p>A superscript T turns a column into a row. The matrix product adds coefficient × input terms for each observation. Expand the square; the middle two scalar terms are equal.</p>
\[L=y^{\mathsf T}y-2\theta^{\mathsf T}A^{\mathsf T}y+\theta^{\mathsf T}A^{\mathsf T}A\theta.\]
<p>A derivative measures how the loss changes as one parameter changes. The gradient collects every such derivative. Set this vector to zero at a stationary minimum:</p>
\[\nabla_\theta L=-2A^{\mathsf T}y+2A^{\mathsf T}A\theta=0,\qquad A^{\mathsf T}A\widehat\theta=A^{\mathsf T}y.\tag{1.3}\]
<p>If the columns are independent, the unique solution is (AᵀA)⁻¹Aᵀy. An inverse undoes a linear transformation. With dependent columns the inverse does not exist; the numerical least-squares solver uses a minimum-norm solution via singular values. We do not invert AᵀA by hand. Small changes can still cause large coefficient changes when columns are nearly dependent.</p>
\[\widehat y_{2025}=A_{2024}\widehat\theta,\qquad \widehat V_{2025}=c\max\{\exp(\widehat y_{2025})-1,0\}.\tag{1.4}\]
<p>exp undoes a natural log. Because averaging and exponentiating do not commute, the dollar transformation is not automatically a conditional mean. The source's scalar c matches the training dollar total (defined below); it is an aggregate correction, not a proof of unbiasedness for each cell. Clipping enforces nonnegative dollars. No 2025 outcome enters this equation.</p>''',
'assumptions': '''A single linear log-mean relation, stable lag dynamics, and usable variation in predictors are central. Zero conditional mean supports coefficient interpretation; exogeneity is unverified. Neither HC3 nor clustered standard errors fix misspecified dynamics, national-to-provincial transfer, or insufficient time variation. No interaction columns are added here.''',
'difference': '''The full model estimates one 2023→2024 transition for 51,618 cells and validates transfer by excluding exporters. Here the final OLS pools 2022→2023 and 2023→2024 (168 rows); the 2024 validation fit has only the earlier 84 transitions. Manufacturing medians are fitted per training sample. Both use the same economic family and a trade lag, but the tiny two-sector design has much less identification and different coefficients. National Canada is modelled here, not Alberta; no CAD conversion or provincial proxy transfer is performed.'''
},
{
'origin': '''Zou and Hastie introduced the Elastic Net in 2005 to combine variable selection with stability when predictors are correlated. L1 shrinkage builds on Tibshirani's 1996 lasso; L2 shrinkage connects to ridge regression (Hoerl and Kennard, 1970). <a href="https://hastie.su.domains/Papers/elasticnet.pdf">Zou and Hastie's original paper</a> motivates the combined penalty; <a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html">the estimator documentation</a> fixes the normalization used here.''',
'intuition': '''GDP and population move together. An unrestricted plane can assign large, opposing slopes that fit a small sample yet extrapolate badly. Elastic Net charges a price for large coefficients. It trades some training fit for a less extreme rule. Unlike Model 1 it has no trade lag: historical economic characteristics are used as proxies for next year's structural potential.''',
'notation': [('y_i','Observed scalar log1p trade','Contemporaneous target at fit year'),('Z, b, a','Standardized matrix, learned slope vector and intercept','252 × 16 matrix; 16 slopes plus intercept'),('alpha > 0','Penalty-strength hyperparameter','Chosen from .01 and .1 using pre-2024 tuning'),('r in [0,1]','Penalty-mixing hyperparameter','Chosen from .2 and .8'),('||b||_1, ||b||_2²','Sum absolute slopes; sum squared slopes','Intercept excluded from penalty'),('S(u,t)','Soft-threshold operator','sign(u) max(|u|−t,0)')],
'math': r'''<p>Begin with least-squares prediction, then penalize the slopes. The L1 term has a corner at zero, enabling exact zeros. The smooth L2 term makes large coefficients expensive and stabilizes correlated directions.</p>
\[\widehat y_i=a+z_i^{\mathsf T}b,\quad J(a,b)=\frac{1}{2n}\sum_i(y_i-a-z_i^{\mathsf T}b)^2+\alpha r\sum_j|b_j|+\frac{\alpha(1-r)}2\sum_j b_j^2.\tag{2.1}\]
<p>The factor 1/(2n) makes the squared-error gradient an average. Norm bars summarize the sums shown explicitly. The intercept is unpenalized. Holding slopes fixed, differentiating with respect to a gives a = mean(y − Zb). To update one slope, remove that column's current contribution and call the partial residual u_i.</p>
\[u_i=y_i-a-\sum_{k\ne j}z_{ik}b_k,\quad q_j=\frac1n\sum_i z_{ij}u_i,\quad d_j=\frac1n\sum_i z_{ij}^2.\]
<p>The terms involving b_j become d_j b_j²/2 − q_j b_j + alpha r |b_j| + alpha(1−r)b_j²/2. For a nonzero b_j, its derivative is zero when:</p>
\[(d_j+\alpha(1-r))b_j-q_j+\alpha r\,\operatorname{sign}(b_j)=0.\]
<p>At zero the absolute-value derivative is a set [−1,1], called a subgradient. Zero is optimal when |q_j| ≤ alpha r. Combining these cases gives the coordinate update:</p>
\[b_j\leftarrow\frac{S(q_j,\alpha r)}{d_j+\alpha(1-r)},\qquad S(q,t)=\operatorname{sign}(q)\max(|q|-t,0).\tag{2.2}\]
<p>The solver cycles through columns until improvement is small, with a dual-gap convergence check. There is no general unpenalized normal-equation closed form for the mixed L1 objective. Scaling numeric columns makes a penalty comparable across GDP logs, percentages and border flags; dummy columns are passed through without standardization, exactly as in the source.</p>
\[\widehat V=c\max\{\exp(a+z^{\mathsf T}\widehat b)-1,0\}.\tag{2.3}\]
<p>Regularization changes the fitted coefficients, not the target or dollar inverse. The same calibration can increase dollar predictions even when a penalty shrinks log slopes. A low log loss need not mean low dollar WAPE.</p>''',
'assumptions': '''The log response is approximately additive; shrinkage creates bias deliberately. Stable standardized feature relationships and the tuning population matter. Penalization addresses variance and collinearity; it does not establish a causal gravity elasticity or cure temporal feature shifts.''',
'difference': '''The original uses a 2024 cross-section and nested exporter-held-out tuning. Here final fitting pools 252 historical rows; alpha and r are selected by fitting 2022 and predicting 2023 with 2022 inputs. That is a time-aware adaptation, not reproduction of the original selected alpha. The source grid, loss normalization, preprocessing, zero handling and training-only dollar calibration remain the same. There is no lag or Alberta scale correction.'''
},
{
'origin': '''Breiman's 2001 Random Forests combined random feature selection with bagged decision trees. Bagging (Breiman, 1996) averages estimators fitted to bootstrap resamples; CART (Breiman, Friedman, Olshen and Stone, 1984) supplies recursive partitioning. The purpose is to reduce unstable individual-tree predictions while capturing nonlinear relationships. See <a href="https://www.stat.berkeley.edu/~breiman/randomforest2001.pdf">Breiman's paper</a> and <a href="https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html">the actual regression estimator</a>.''',
'intuition': '''A tree asks threshold questions: is external car supply large, is distance short, and is this a wheat cell? Each answer leads to a smaller group whose average transformed trade supplies a prediction. A forest repeats this with different resampled rows and candidate features, then averages predictions. It does not learn a single GDP slope.''',
'notation': [('R','Set of row indices in one tree node','Bootstrap sample, multiplicities retained'),('m_R','Learned scalar leaf value','Mean log1p trade in node'),('j, s','Feature index and split threshold','Chosen by reducing squared error'),('T_b(z)','Prediction from tree b','One of 120 fitted trees'),('B','Tree-count hyperparameter','120'),('eta, lambda','Not used by this model','No boosting step or dynamic blend')],
'math': r'''<p>For a fixed leaf, predict a constant m. Differentiate its squared error to find the best constant:</p>
\[Q_R(m)=\sum_{i\in R}(y_i-m)^2,\quad \frac{dQ_R}{dm}=-2\sum_{i\in R}(y_i-m)=0\ \Rightarrow\ m_R=\frac{\sum_{i\in R}y_i}{|R|}.\tag{3.1}\]
<p>Bootstrap weights count duplicated draws. The mean is then weighted by those multiplicities. For feature j and threshold s, form two children, L = {i:z_ij ≤ s} and H = {i:z_ij > s}. Each child gets its own mean.</p>
\[\Delta(j,s)=\sum_{i\in R}(y_i-m_R)^2-\sum_{i\in L}(y_i-m_L)^2-\sum_{i\in H}(y_i-m_H)^2.\tag{3.2}\]
<p>Choose the allowed split with largest positive reduction. Repeat until depth, leaf size, purity or other stopping conditions prevent further splitting. This is greedy: the best immediate split need not lead to the globally best tree. The library searches a random candidate feature subset at each node; max_features .7 of 16 gives 11 candidates, with implementation exceptions if no valid partition is found.</p>
\[F(z)=\frac1B\sum_{b=1}^{B}T_b(z),\qquad \widehat V=c\max\{\exp(F(z))-1,0\}.\tag{3.3}\]
<p>Average log predictions BEFORE exponentiating. Averaging tree dollar predictions would be a different algorithm. If trees have equal variance sigma² and pairwise correlation r_T, elementary variance expansion gives Var(mean) = sigma²[r_T + (1−r_T)/B]. This explanatory identity assumes equal variances/correlations; it is not an estimated uncertainty interval. Randomness aims to reduce correlation while retaining informative trees.</p>
<p>Scaling preserves feature ordering and hence feasible threshold partitions except for floating-point effects. Here it is retained to match the shared source pipeline. Forests naturally represent threshold interactions without extra interaction columns. Outside the training range, an input lands in an existing leaf rather than extrapolating a new slope.</p>''',
'assumptions': '''Useful nearby partitions and enough examples per leaf are needed. Bootstrap sampling treats the selected rows as a resampling population; repeated dyads are dependent, so tree diversity is not independent economic evidence. No out-of-bag score is reported: temporal validation provides the relevant error check.''',
'difference': '''All 120/depth16/leaf8/feature.7 settings and the log-dollar pipeline are retained. The original final cross-section has 51,618 cells; this final forest pools 252 rows from three years. The temporal evaluation uses 2023 predictors for 2024 outcomes. There are only two HS2 categories and seven countries. National scale, two-sector extrapolation and serial dependence differ from the Alberta task.'''
},
{
'origin': '''Rosenblatt's late-1950s perceptron developed trainable units; multilayer training became widely influential through Rumelhart, Hinton and Williams's 1986 backpropagation account. Backpropagation applies the calculus chain rule efficiently; Adam (Kingma and Ba, 2014/2015) supplies adaptive numerical updates. These are separate historical components. See <a href="https://doi.org/10.1038/323533a0">the 1986 paper</a>, <a href="https://arxiv.org/abs/1412.6980">Adam</a>, and <a href="https://scikit-learn.org/stable/modules/neural_networks_supervised.html">the implemented MLP guide</a>.''',
'intuition': '''A network repeatedly mixes inputs and bends them with a smooth nonlinear function. Its learned hidden units are not preassigned economic concepts. Two hidden layers can represent combinations such as large supply together with short distance. Many weight combinations can describe a tiny sample, so a good training fit is weak evidence of forecasting reliability.''',
'notation': [('z','16-dimensional standardized input vector','14 numeric features and two HS2 indicators'),('W1, W2, w3','Learned weight matrices/vector','16×8, 8×4, 4×1'),('b1, b2, b3','Learned bias vectors/scalar','8, 4 and 1 entries'),('h1, h2','Hidden activation vectors','8 and 4 tanh outputs'),('alpha','L2 hyperparameter','0.1; biases not penalized'),('m_t, v_t, eta','Adam gradient moments and step-size hyperparameter','Optimizer state; eta=.001')],
'math': r'''<p>Use row vectors to match the library's array orientation. Matrix multiplication combines each input with its weights. tanh is a smooth S-shaped transformation; applying it componentwise produces a hidden vector.</p>
\[a_1=zW_1+b_1,\quad h_1=\tanh(a_1),\quad a_2=h_1W_2+b_2,\quad h_2=\tanh(a_2),\quad F(z)=h_2w_3+b_3.\tag{4.1}\]
\[\tanh(u)=\frac{e^u-e^{-u}}{e^u+e^{-u}},\qquad \frac{d\tanh(u)}{du}=1-\tanh^2(u).\]
<p>The final output is linear and may be any real log prediction. Hidden outputs lie between −1 and 1; this bounds hidden activations, not export dollars. The half-squared-error loss plus the library's weight penalty is:</p>
\[J=\frac1{2n}\sum_i(F(z_i)-y_i)^2+\frac{\alpha}{2n}\left(\|W_1\|_F^2+\|W_2\|_F^2+\|w_3\|_2^2\right).\tag{4.2}\]
<p>The Frobenius squared norm is the sum of squared matrix entries. For one observation set delta_3 = F − y. A product's derivative transmits error backward through the weights; multiplying componentwise by tanh's derivative accounts for its bend.</p>
\[\delta_2=(\delta_3 w_3^{\mathsf T})\odot(1-h_2^2),\qquad \delta_1=(\delta_2W_2^{\mathsf T})\odot(1-h_1^2).\]
\[\nabla_{W_1}J=\frac1n\sum_i z_i^{\mathsf T}\delta_{1i}+\frac\alpha nW_1,\quad \nabla_{W_2}J=\frac1n\sum_i h_{1i}^{\mathsf T}\delta_{2i}+\frac\alpha nW_2,\quad \nabla_{w_3}J=\frac1n\sum_i h_{2i}^{\mathsf T}\delta_{3i}+\frac\alpha nw_3.\tag{4.3}\]
<p>The symbol ⊙ means multiply matching entries. Bias gradients are average deltas without the L2 term. The full-sample expression describes the objective; the actual optimizer estimates gradients using minibatches, with penalty normalization by the batch sample count in this implementation. The sequence and random initialization affect the result.</p>
\[m_t=.9m_{t-1}+.1g_t,\quad v_t=.999v_{t-1}+.001g_t^2,\quad \theta_t=\theta_{t-1}-\eta_t\frac{m_t}{\sqrt{v_t}+10^{-8}},\quad \eta_t=.001\frac{\sqrt{1-.999^t}}{1-.9^t}.\tag{4.4}\]
<p>Squares and square roots here are componentwise. This is the library's Adam update form, including bias-corrected effective step size. The objective is nonconvex; the iteration limit is not a guarantee of an optimum. Finally use c max(exp(F)−1,0). Backpropagation trains the model; the forward pass alone makes a prediction.</p>''',
'assumptions': '''The chosen architecture must represent a transferable relationship, optimization must find useful weights, and scaling must be reliable. Bounded tanh can saturate and produce tiny gradients. A weight penalty limits some complexity but neither implies monotone economic effects nor eliminates overfitting.''',
'difference': '''The original uses tanh 32/16 with 180 epochs, batch512 and random 15% internal early stopping. This teaching version uses tanh 8/4, batch64 and a fixed 2000-epoch Adam budget, alpha .1, and disables random early stopping so the explicit 2024 temporal check remains separate. There are 177 trainable scalars. The recorded convergence warning is retained. These are declared teaching settings, not the original fitted network or a numerical replication.'''
},
{
'origin': '''Friedman's 2001 gradient boosting formulation describes sequential function approximation by following gradients in prediction space. Histogram implementations group continuous inputs into bins to accelerate tree split searches; the source uses scikit-learn's HistGradientBoostingRegressor, not XGBoost or a generic named package. See <a href="https://jerryfriedman.su.domains/ftp/trebst.pdf">Friedman's paper</a> and <a href="https://scikit-learn.org/stable/modules/ensemble.html#histogram-based-gradient-boosting">the implementation guide</a>.''',
'intuition': '''Start with a rough constant log-trade prediction. A small tree learns what that rough answer misses. Add a modest fraction of its correction, then let the next tree work on what is still wrong. Forest trees are averaged in parallel; these boosting trees depend on the earlier trees' errors.''',
'notation': [('F_m(z)','Learned scalar additive log prediction','After m correction trees'),('r_im','Negative loss gradient','y_i − F_(m−1)(z_i) for squared loss'),('eta','Learning-rate hyperparameter','0.05'),('R_l, u_l','Tree leaf region and learned correction','Up to seven leaves per iteration'),('G_l, H_l, L2','Sums of gradients, Hessians, leaf penalty','Squared-loss Hessian 1; L2=0 here'),('M','Maximum correction trees','150, no random early stopping')],
'math': r'''<p>Minimize half squared error in transformed units. First choose a constant; differentiation gives the training mean log outcome.</p>
\[L(F)=\frac12\sum_i(y_i-F(z_i))^2,\qquad F_0=\overline y.\tag{5.1}\]
<p>Treat each observation's prediction as a coordinate. The derivative with respect to that coordinate is F−y, so moving in the negative-gradient direction means fitting residuals y−F. A tree approximates this correction using a few regions rather than a separate correction for every row.</p>
\[g_i=F_{m-1}(z_i)-y_i,\quad h_i=1,\quad r_{im}=-g_i,\quad F_m=F_{m-1}+\eta\sum_l u_l\mathbf1\{z\in R_l\}.\tag{5.2}\]
<p>The indicator is 1 inside a leaf and 0 outside it. The library uses a second-order loss expansion for each leaf. Holding its rows fixed, the part that depends on correction u is G u + (H + L2)u²/2. Differentiate to obtain its Newton value:</p>
\[G_l=\sum_{i\in R_l}g_i,\quad H_l=\sum_{i\in R_l}h_i,\quad u_l=-\frac{G_l}{H_l+L2}.\tag{5.3}\]
<p>For squared error and L2=0 this is exactly the average residual. The optimal quadratic value is −G²/[2(H+L2)]. Therefore an ideal split's loss reduction is:</p>
\[\operatorname{gain}=\frac12\left[\frac{G_L^2}{H_L+L2}+\frac{G_H^2}{H_H+L2}-\frac{G_R^2}{H_R+L2}\right].\tag{5.4}\]
<p>Implementation score scaling can omit a common factor 1/2 without changing the maximizing split. Instead of trying every distinct numeric value, the histogram model searches learned bin boundaries (max_bins255), with min_samples_leaf20. This is a computational approximation to candidate split locations, not a different trade target. Smaller eta means each tree changes the fit less, but many iterations can still overfit.</p>
\[F_{150}(z)=F_0(z)+\sum_{m=1}^{150}\eta h_m(z),\qquad \widehat V=c\max\{e^{F_{150}(z)}-1,0\}.\tag{5.5}\]
<p>These are residual corrections to log1p trade, including zeros. There is no positive-trade probability or partial-adjustment lambda in Model 5. A leaf has a constant correction; accumulated leaves produce nonlinear threshold interactions.</p>''',
'assumptions': '''Shallow residual patterns must transfer across years. Bin resolution, leaf size and shrinkage regulate flexibility. The stagewise greedy algorithm has no global tree-ensemble closed form and can fit sample peculiarities. Nonnegative inverse predictions need not exactly reproduce zero cells.''',
'difference': '''The 150/7/.05 settings and minleaf20/maxbins255 defaults are retained. Automatic early stopping is explicitly disabled; the original auto setting also stays off below 10,000 rows, so this avoids any random validation split in the toy fit. Final fitting pools 252 historical rows instead of only the 2024 cross-section. The source dollar calibration remains. There is no Alberta lag blend or extra classification stage.'''
},
{
'origin': '''This is a composite, not a single algorithm with one inventor. Binary response models separate the chance of a positive outcome from its size; Cragg's 1971 two-part work is a relevant early econometric reference. Gradient boosting supplies the two nonlinear estimators. Partial adjustment appears in mid-twentieth-century dynamic econometrics, including <a href="https://doi.org/10.2307/1234920">Nerlove's 1958 distributed-lag work</a>. The precise coupling here comes from the supplied trade-method script and PDF; it is not claimed as a standard off-the-shelf model. See <a href="https://doi.org/10.2307/1909582">Cragg (1971)</a>, <a href="https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html">the classifier</a>, and the <a href="details-of-machine-learning-models/model_inventory.md">local specification inventory</a>.''',
'intuition': '''First ask whether a trade cell is positive. Then ask how large it is when positive. Multiply the probability by the positive amount to form a structural potential. Established trade does not instantly become that potential: move last year's log trade partway toward it. This makes three connected estimation tasks—classification, positive-size regression and adjustment-speed estimation.''',
'notation': [('d_i = 1{V_i>0}','Observed binary scalar','All 84 cells classify, including zeros'),('s(z), pi(z)','Learned logit and predicted probability','pi = 1/(1+exp(−s))'),('f(z), c+','Positive-only learned log-dollar function and calibration','Only strictly positive cells fit f'),('V*, p = log(1+V*)','Predicted structural dollars and log potential','pi c+ exp(f)'),('g_i, Delta y_i','OOF potential gap and observed next-year change','2022→2023 paired cells'),('lambda','Learned scalar, restricted to [0,1]','Through-origin OLS slope, then clipping')],
'math': r'''<p>For any nonnegative outcome, the law of total expectation is an exact identity. E[V|z] means the average outcome over possible observations sharing inputs z; the vertical bar means “conditional on.” P(V&gt;0|z) is the probability of a positive outcome given those inputs. This is a probability model, not an average of the three plotted examples:</p>
\[E[V\mid z]=P(V>0\mid z)E[V\mid V>0,z]+P(V=0\mid z)\,0.\tag{6.1}\]
<p>The model approximates the first probability and positive conditional size separately. Let d be the observed 0/1 target. Under a Bernoulli probability model, the likelihood and negative log-likelihood are:</p>
\[\mathcal L=\prod_i\pi_i^{d_i}(1-\pi_i)^{1-d_i},\quad L=-\sum_i[d_i\log\pi_i+(1-d_i)\log(1-\pi_i)].\tag{6.2}\]
<p>A summation adds one term for every cell. Taking a log turns a product into a sum; the minus sign changes maximization to minimization. A logit s maps real numbers to a probability through the logistic sigmoid. Rewrite the single-row loss using pi=exp(s)/(1+exp(s)):</p>
\[L_i(s)=\log(1+e^s)-d_i s,\quad \frac{dL_i}{ds}=\pi_i-d_i,\quad \frac{d^2L_i}{ds^2}=\pi_i(1-\pi_i).\tag{6.3}\]
<p>The Hessian is the second derivative, measuring curvature. Histogram trees use the Newton leaf expression from Model 5 with these binary-loss gradients and Hessians. The classifier is trained on every cell; no hard 0.5 decision is multiplied into dollar potential.</p>
\[\widehat f=\operatorname{boost}\left(\log V_i\ ;\ V_i>0\right),\quad c_+=\frac{\sum_{V_i>0}V_i}{\sum_{V_i>0}\exp(\widehat f(z_i))},\quad \widehat V_i^*=\widehat\pi_i c_+\exp(\widehat f(z_i)).\tag{6.4}\]
<p>The positive stage minimizes half squared log errors using the gradient-boosting derivation above. It uses log V, not log(1+V). Its exp output approximates a geometric central amount; c+ matches the positive training total. Equation 6.1 is exact, but treating this calibrated exp output as a conditional mean is a modelling approximation. Separate preprocessors are fitted to the all-cell and positive-only samples.</p>
<p>Now assume a partial-adjustment relation in log1p units. Given last year's trade y and potential p, move a fraction lambda of the gap. Lambda=0 is USD persistence; lambda=1 is full adjustment to potential.</p>
\[\Delta y_i=\lambda g_i+\epsilon_i,\quad g_i=p_i^{OOF}-y_i,\quad \Delta y_i=y_{i,t+1}-y_{i,t}.\tag{6.5}\]
<p>OOF means the potential for a 2022 exporter comes from structural stages trained on the other six exporters. It reduces own-target fitting in the gap; it does not make correlated dyads independent. Estimate lambda using observed 2022→2023 changes, with no intercept:</p>
\[Q(\lambda)=\sum_i(\Delta y_i-\lambda g_i)^2,\quad Q'(\lambda)=-2\sum_i g_i\Delta y_i+2\lambda\sum_i g_i^2=0.\]
\[\widehat\lambda_{raw}=\frac{\sum_i g_i\Delta y_i}{\sum_i g_i^2},\quad \widehat\lambda=\min\{1,\max\{0,\widehat\lambda_{raw}\}\}.\tag{6.6}\]
<p>The denominator must be positive. If every gap is zero, lambda is unidentified; it cannot be assigned from this formula. Clipping is the constrained quadratic minimizer on [0,1]. Freeze this slope, obtain 2023 OOF potentials and validate predictions against 2024; only afterward fit final structural stages on 2024.</p>
\[\widehat y_{2025}=(1-\widehat\lambda)y_{2024}+\widehat\lambda p_{2024},\quad 1+\widehat V_{2025}=(1+V_{2024})^{1-\widehat\lambda}(1+\widehat V_{2024}^*)^{\widehat\lambda}.\tag{6.7}\]
<p>The second equation follows exactly by exponentiating the first. It is geometric interpolation in 1+dollars, not an arithmetic average of dollar amounts. A zero lag remains eligible; with positive potential and positive lambda it can receive positive forecast trade. The estimated common speed is an empirical smoothing relation, not a causal speed of market access.</p>''',
'assumptions': '''The probability and positive-size models must transfer; one common adjustment speed must summarize very different cells; the OOF gap must be informative about subsequent change. A small lambda makes persistence dominate, and can look excellent in a scenario generated from last year's values. This is not evidence that structural potential estimates are accurate.''',
'difference': '''The original learns lambda across 51,618 cells, with South Korea in its network, then transfers national structural stages to Alberta using provincial lags and Canadian proxies. Here Germany replaces South Korea, only 84 gaps identify lambda, and final stages fit 84 2024 cells. Same all-cell classifier, positive-only log regressor, calibration and constrained gap slope are retained. No externally validated prospective 2025 outcome exists in this teaching table. The toy lambda is independently estimated, never copied from the original 0.134342.'''
}
]
