"""Build the standalone research HTML from measured results and retained sources."""
from html import escape
import json
from pathlib import Path
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
ASSET='gpt-6-astra-blender/'
C=json.loads((ROOT/'data/city.json').read_text())
A=json.loads((ROOT/'data/analysis.json').read_text())
V=json.loads((ROOT/'data/scene_validation.json').read_text())
B=json.loads((ROOT/'data/build_runtime.json').read_text())
R=json.loads((ROOT/'data/render_runtime.json').read_text())
T=json.loads((ROOT/'data/animation_runtime.json').read_text()) if (ROOT/'data/animation_runtime.json').exists() else {}
def link(path,label):return f'<a href="{ASSET}{path}">{label}</a>'
def figure(name,alt,caption,chart=False):
    ext='png' if chart else 'webp'
    with Image.open(ROOT/'renders'/f'{name}.png') as img:width,height=img.size
    return f'<figure class="figure"><a href="{ASSET}renders/{name}.png"><img src="{ASSET}renders/{name}.{ext}" alt="{escape(alt,quote=True)}" loading="lazy" width="{width}" height="{height}"></a><figcaption>{caption}</figcaption></figure>'
def video(name,poster,caption):
    return f'<figure class="figure"><video controls playsinline preload="none" poster="{ASSET}renders/{poster}.webp" width="960" height="540" aria-label="{escape(caption,quote=True)}"><source src="{ASSET}video/{name}.mp4" type="video/mp4"><a href="{ASSET}video/{name}.mp4">Download this animation</a></video><figcaption>{caption}</figcaption></figure>'
def code_excerpt(file,start,end):
    text=(ROOT/'scripts'/file).read_text();snippet=text[text.index(start):text.index(end,text.index(start))].rstrip()
    return '<pre><code>'+escape(snippet)+'</code></pre>'
def table(headers,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+str(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def chapter(id,number,title):return f'<section class="chapter" id="{id}"><span class="chapter-number">{number}</span><h2>{title}</h2>'
peak=max(A['betweenness'],key=A['betweenness'].get)
lo=min(A['accessibility_before']);hi=max(A['accessibility_after'])
mc=A['monte_carlo'][1]
options=lambda selected:''.join(f'<option value="{n["id"]}"'+(' selected' if n['id']==selected else '')+f'>Node {n["id"]} ({n["x"]}, {n["y"]})</option>' for n in C['nodes'])
page=r'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="An editable 204-building Blender city, exact graph calculations, Monte Carlo resilience experiments, and interactive 3D accessibility maps. A reproducible visual research laboratory.">
<title>Using GPT-6 Astra with Blender: A 3D Laboratory for Graph Theory, GIS, and Spatial Economics</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&amp;family=Inter:wght@400;500;600;700&amp;family=Source+Code+Pro:wght@400;500&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="gpt-6-astra-blender/page.css">
<link rel="icon" href="gpt-6-astra-blender/favicon.svg" type="image/svg+xml">
<script>window.MathJax={tex:{inlineMath:[['$','$'],['\\(','\\)']],displayMath:[['$$','$$'],['\\[','\\]']]},svg:{fontCache:'local'}};</script>
<script defer src="gpt-6-astra-blender/vendor/tex-svg.js"></script>
<script type="module" src="gpt-6-astra-blender/page.js"></script>
</head><body><a class="skip" href="#main">Skip to the laboratory</a><div class="page">
<nav class="top-nav" aria-label="Site navigation"><a href="../research.html">← Naresh Neupane · Research</a><a href="#files">Data, models &amp; source ↗</a></nav>
<main class="card" id="main"><header><span class="eyebrow">A reproducible visual laboratory · Synthetic city No. 260905</span>
<h1>Using GPT-6 Astra<br>with Blender:<br><span>A 3D Laboratory for Graph Theory, GIS, and Spatial Economics</span></h1>
<p class="lead">A city can be more than a picture. Give every street an explicit connection and every building an address in a coordinate system, and the model becomes a place to ask mathematical questions.</p>
<p>This project actually generates the editable city, calculates its network, renders its analytical views, and runs its disruption experiments. Begin with a cube; finish with a small, inspectable spatial model.</p>
<figure class="hero-figure cinematic-hero">
<video id="city-cinematic" controls autoplay muted loop playsinline preload="metadata" poster="gpt-6-astra-blender/renders/cinematic/poster.webp" width="1280" height="720" aria-label="24-second city tour: aerial approach, architectural sweep, transit street, river bridge, and full-city reveal" aria-describedby="cinematic-caption"><source src="gpt-6-astra-blender/video/astra_city_cinematic.mp4" type="video/mp4"><a href="gpt-6-astra-blender/video/astra_city_cinematic.mp4">Download the cinematic city tour</a></video>
<figcaption id="cinematic-caption"><p>A 24-second tour of the city constructed procedurally by GPT-6 Astra through Codex using Blender Python. Every building remains editable in the <a href="gpt-6-astra-blender/blender/city_cinematic.blend">downloadable Blender scene</a>.</p>Locally generated geometry includes twelve architectural families, seven branching tree archetypes and 48 pedestrians. The coral line is existing transit; twelve pedestrians have simple walking animation.</figcaption></figure>
'''
page+=fr'''<div class="metric-grid"><div class="metric"><strong>{A['buildings']}</strong><span>individually editable buildings</span></div><div class="metric"><strong>{A['nodes']} / {A['road_edges']}</strong><span>road nodes / undirected edges</span></div><div class="metric"><strong>{V['master_objects']}</strong><span>objects in the complete master</span></div><div class="metric"><strong>{V['glb']['city_web']['bytes']/1048576:.2f} MiB</strong><span>interactive city download</span></div></div>
<aside class="provenance"><p>Workflow note supplied in the project brief: <q>The implementation prompt for this project was drafted in ChatGPT using GPT-5.6 Sol with high reasoning effort. The project was then implemented and iterated in OpenCode using GPT-6 Astra.</q></p><p>Execution provenance: the artifacts on this page were generated and checked in the local coding-agent session accompanying this repository. The supplied workflow note is retained as author-provided context; it is not an independently verified record of a separate OpenCode run. Human browser review remains pending.</p></aside></header>
<nav class="toc" aria-label="On this page"><h2>Choose your starting point</h2><div class="toc-grid"><div><strong>01 · Learn the visual language</strong><a href="#built">What was built?</a><a href="#blender">What exactly is Blender?</a><a href="#anatomy">From cube to building</a><a href="#city">From building to city</a></div><div><strong>02 · Explore the mathematics</strong><a href="#graph">Streets become a graph</a><a href="#paths">Calculate a shortest path</a><a href="#centrality">Degree and betweenness</a><a href="#gis">Coordinates and spatial joins</a><a href="#statistics">City statistics</a></div><div><strong>03 · Run and inspect experiments</strong><a href="#failure">Close a river crossing</a><a href="#monte-carlo">Monte Carlo resilience</a><a href="#accessibility">Transit and accessibility</a><a href="#engineering">Procedural engineering</a><a href="#interactive">Interactive 3D model</a><a href="#reproduce">Checks, reproduction and prompt</a></div></div></nav>'''

page+=chapter('built','01 · The result','What did Astra build?')
page+=r'''<p>A fictional 392 × 338 metre diorama contains 36 blocks: 34 developed blocks with six buildings each, plus two parks. Four neighbourhoods have different material palettes and height profiles. Two road crossings join the riverbanks. Four stations form an existing eastern transit line; a proposed cross-river connection is a separate scenario.</p>
<div class="steps"><div class="step"><strong>Data</strong><p>One JSON file records positions, building parameters, road edges, transit costs and opportunities.</p></div><div class="step"><strong>Geometry</strong><p>Python constructs shared meshes, named objects, materials, cameras and lights.</p></div><div class="step"><strong>Analysis</strong><p>Shortest paths, centrality, accessibility and 1,200 disruption trials use the recorded graph.</p></div><div class="step"><strong>Evidence</strong><p>Blender files, rendered images, animated experiments, GLBs and validation reports are downloadable.</p></div></div>
<aside class="note"><p><strong>Three things to keep separate.</strong> The city is a designed synthetic dataset. The shortest-path results are exact for its stated graph and costs. The disruption probabilities are Monte Carlo estimates under a chosen failure model. None describe an observed real city.</p></aside></section>'''

page+=chapter('blender','02 · Start here','What exactly is Blender?')
page+=r'''<p>Blender is an application for creating, organizing, animating and rendering three-dimensional scenes. Its interface is one way to construct a scene. Its Python API, <code>bpy</code>, exposes the same underlying data so a script can build a scene from explicit rules.</p><p>Think of a building as a named object placed in space. Its mesh describes the surface. Its materials describe how that surface responds to light. The camera chooses a view; the renderer calculates the image.</p>
<dl class="terms"><div><dt>Object</dt><dd>A named scene item with a position, rotation and scale. Each B### building is one object.</dd></div><div><dt>Mesh</dt><dd>The geometric data used by an object. Multiple buildings can refer to one shared mesh.</dd></div><div><dt>Vertex</dt><dd>A point in a mesh. An ordinary cube has eight corner vertices.</dd></div><div><dt>Edge</dt><dd>A connection between two mesh vertices. A cube has twelve; these are different from transportation-graph edges.</dd></div><div><dt>Face</dt><dd>A surface bounded by mesh edges. A cube has six quadrilateral faces; exporting it as triangles produces twelve triangles.</dd></div><div><dt>Material</dt><dd>Surface colour, roughness, metallic response and optional emission. Blue glazing is a material on facade faces.</dd></div><div><dt>Collection</dt><dd>A named group of objects. Roads, buildings, trees and graph overlays live in separate collections.</dd></div><div><dt>Modifier</dt><dd>A reversible operation on evaluated geometry, such as beveling corners or making a linear array.</dd></div><div><dt>Camera</dt><dd>The scene viewpoint and projection. The static overview uses an orthographic camera; the cinematic reel uses perspective cameras.</dd></div><div><dt>Light</dt><dd>A source of illumination. This scene combines a sun, large area lights and world illumination.</dd></div><div><dt>Render</dt><dd>An image computed from geometry, materials, camera and lighting. A frame sequence becomes an animation.</dd></div><div><dt>.blend</dt><dd>The editable Blender project: objects, mesh relationships, materials, scene settings and animation data.</dd></div><div><dt>glTF / GLB</dt><dd>A browser-oriented scene format. GLB packages its scene description and binary geometry into one file; it does not preserve every Blender feature.</dd></div><div><dt>bpy</dt><dd>Blender’s Python module. Run the scripts with Blender’s Python interpreter, not an ordinary Python process that lacks Blender.</dd></div></dl></section>'''

page+=chapter('anatomy','03 · One object, explained','From a primitive cube to a finished building')
page+=figure('anatomy','Four building stages: cube, stretched cube with highlighted vertices and edges, exploded windows and roof, and a finished green building','Read left to right: (1) cube, (2) scaled cuboid with visible topology, (3) facade panes and roof separated for explanation, (4) complete shared archetype. This is an actual Blender render; the exploded arrangement is educational, not a construction simulation.')
page+=r'''<p>Scaling a cube changes its dimensions without increasing its vertex count. Adding facade panes and roof geometry changes the mesh itself. Materials can vary across faces within the same mesh, so a window does not need to be a separate object.</p><p>The generator constructs twelve architectural families in normalized local coordinates. For building $b$, a local point $(u,v,w)$ is placed in the city as:</p><div class="equation">$$x=x_b+s_{x,b}u,\qquad y=y_b+s_{y,b}v,\qquad z=0.65+s_{z,b}w.$$</div><p class="symbols">Here $(x_b,y_b)$ is the building’s ground position in metres; $s_{x,b}$, $s_{y,b}$ and $s_{z,b}$ are its width, depth and facade-height parameters. The 0.65 m offset puts the building on the sidewalk. The local body runs from $w=0$ to $w=1$; roofs extend above it.</p><p>A 10 × 9 × 20 m building therefore uses scale <code>(10, 9, 20)</code>. A pitched roof with local ridge height 1.22 reaches 24.4 m above the building base. Facade height and total roof height are intentionally distinct quantities.</p>'''
page+=code_excerpt('build_city.py','def object_from','def orient')
page+='<p class="small">Actual helper from '+link('scripts/build_city.py','build_city.py')+'. It creates an object that references an existing mesh, then assigns its transform. In Blender, select a B### object to move or scale it. To change only its topology, make its mesh single-user first; otherwise edits propagate to its linked siblings.</p></section>'

page+=chapter('city','04 · Deterministic generation','A city is a system of rules')
page+=r'''<p>The generation seed is <code>260905</code>. The original 8-column by 7-row grid has 48 m spacing. Eight outer promenade junctions, their feeder links and two diagonal park paths add alternative walking routes. Most horizontal connections across the central river are omitted; only the crossings at $y=-96$ m and $y=48$ m remain. Building slots sit inside the non-river blocks, with small seeded variations in width, depth, height and archetype.</p><p>Twelve shared architectural families provide cottages, townhouses, brick commercial buildings, apartments, civic forms and modern towers. The east bank draws from taller archetypes, and Innovation District applies a further height multiplier. This is a design rule, not a discovered relationship between location and development.</p>'''
page+=figure('detail','Close view of the river crossing, neighbourhood buildings, joined window details, trees and street furniture','The master includes facade sills, floor bands and roof details. Each building remains one object, including its repeated windows. The 162 trees share seven branched-trunk and asymmetric-crown meshes. Forty-eight clothed pedestrian instances establish human scale; twelve use lightweight walking shape keys.')
page+=r'''<p>Direct mesh construction avoids thousands of expensive add-object operations. Window panes are faces; sills are small boxes already included in the archetype mesh. Sidewalks, 64 intersection surfaces and ordinary lane markings are each batched. Crossing-specific markings stay separately addressable so the failure animation can remove the complete crossing.</p></section>'''

page+=chapter('graph','05 · An explicit network','Turning streets into a graph')
page+=r'''<p>Stand at an intersection and list the streets you can enter. This is the local meaning of a graph. Our road graph has one node per intersection or path junction and one undirected edge per traversable road or footway connection. Directional turn restrictions and traffic lanes are outside this model.</p><div class="equation">$$G_R=(V,E_R),\qquad |V|=64,\quad |E_R|=108.$$</div><p class="symbols">$G_R$ is the road graph, $V$ its set of intersection IDs and $E_R$ its road-edge set. Each edge has endpoints, a centre-line length in metres and a positive travel cost in seconds.</p>'''
page+='<div class="grid">'+figure('overlay','Cyan nodes and edges overlaid on the exact generated road network','The cyan overlay follows the road centre lines. Glyph height is a display choice; graph distances use the planar node coordinates.')+figure('graph','Graph-only Blender render of the same 64 junctions and 108 edges','Hiding the city reveals the same network. Empty space between the riverbanks has only two connecting road edges.')+'</div>'
page+=r'''<p>The JSON edge <code>{"u":35,"v":36,"length_m":48,"seconds":36}</code> becomes the Blender object <code>Road_35-36</code>. Its centre is the average of the two node positions. The script generates road surfaces from this edge list, and the validator checks every midpoint, length and cost against it.</p><p>For accessibility we form a second graph $G_T=(V,E_R\cup E_T)$ by adding three existing transit edges between four stations. The proposed scenario adds one more transit edge. Centrality, degree and the random road-failure experiment use $G_R$; accessibility before and after uses the explicitly stated transit graphs.</p></section>'''

page+=chapter('paths','06 · A calculable journey','The shortest path is a result, not a drawing')
page+=r'''<p>Travel from node 40 at $(-168,96)$ to node 47 at $(168,96)$. The shortest road route crosses the northern bridge. Every regular 48 m grid segment costs 36 seconds at the assumed walking speed of 80 m/min.</p><div class="equation">$$c_e=\frac{\operatorname{round}(60\ell_e/80)}{60}\quad\text{minutes},\qquad d_G(s,t)=\min_{P:s\leadsto t}\sum_{e\in P}c_e.$$</div><p class="symbols">$\ell_e$ is road-edge length in metres, $c_e$ its walking cost, $P$ a path from source $s$ to target $t$, and $d_G(s,t)$ the least total cost. Edge costs are rounded to the nearest second before routing; this matters for the diagonal and irregular links. The scripts store $60c_e$ as integer seconds; accessibility calculations use minutes.</p>'''
page+=f'<p>The computed path is <code>{" → ".join(map(str,A["route"]["nodes"]))}</code>: {len(A["route"]["nodes"])-1} edges, <strong>{A["route"]["metres"]:.2f} m and {A["route"]["seconds"]/60:.2f} minutes</strong>. Dijkstra’s algorithm is appropriate because all edge costs are positive. Equal-cost routes can exist; one valid shortest route is displayed.</p>'
page+=video('shortest_path','route',f'A 14-second sequence establishes the network, approaches the origin, progressively highlights the calculated {A["route"]["seconds"]/60:.2f}-minute path and pulls back. Muted alternatives show route choice. Playback timing is illustrative, not simulated travel behavior.')
page+=fr'''<div class="interactive"><h3>Try different endpoints</h3><p class="small">This browser explorer runs Dijkstra on the same JSON road edges. Closing the northern crossing removes edge 35–36 and recalculates the route.</p><div class="controls"><label for="origin">Origin<select id="origin">{options(A["source"])}</select></label><label for="destination">Destination<select id="destination">{options(47)}</select></label><label><input type="checkbox" id="close-bridge"> Close northern crossing</label></div><svg id="graph-lab" viewBox="-204 -170 408 340" role="img" aria-label="Road graph with computed route and node IDs"></svg><p class="route-output" id="route-output" aria-live="polite">Node {A["source"]} → {A["target"]}: {A["route"]["metres"]:.2f} m · {A["route"]["seconds"]/60:.2f} minutes.</p><noscript><p>For a static equivalent, see the labelled graph below. Interactive recalculation requires JavaScript.</p></noscript></div>'''
page+=figure('graph_map','Labelled graph showing baseline and closure routes on a synthetic metre coordinate grid','A second, two-dimensional view makes every ID and the detour inspectable. Original IDs 0–55 proceed west to east within rows, from south to north; outer promenade junctions retain IDs 56–63.',True)+'</section>'

page+=chapter('centrality','07 · Local and global structure','Degree counts choices; betweenness counts reliance')
page+=r'''<p>A node of degree four has four immediate road choices. That does not guarantee that it lies on many long journeys. The endpoints of a scarce river crossing can have ordinary degree but high betweenness because many shortest paths pass through them.</p><div class="equation">$$k_i=\sum_{j\in V}\mathbf{1}\{\{i,j\}\in E_R\},\qquad \sum_{i\in V}k_i=2|E_R|=216.$$</div><p class="symbols">$k_i$ is node $i$’s degree. The indicator is one if nodes $i$ and $j$ share a road edge, and zero otherwise. Each undirected edge contributes once to each endpoint, which explains the factor of two.</p>'''
page+=figure('degree','Graph-only degree map with taller warmer node columns indicating more incident road edges','Degree is encoded by glyph height and colour: the observed minimum maps to 3 m and the maximum to 25 m, with linear spacing between. These are display heights, not physical towers.')
page+=r'''<p>For betweenness, consider every unordered pair of other nodes. If several equally short routes exist, split that pair’s contribution among them rather than choosing one arbitrarily.</p><div class="equation">$$B(v)=\frac{1}{\binom{n-1}{2}}\sum_{\substack{s&lt;t\\s,t\ne v}}\frac{\sigma_{st}(v)}{\sigma_{st}},\qquad n=64.$$</div><p class="symbols">$B(v)$ is normalized, endpoint-excluding betweenness of node $v$; $\sigma_{st}$ counts shortest $s$–$t$ paths and $\sigma_{st}(v)$ counts those passing through $v$ internally. The normalization is the number of eligible unordered pairs. All-pairs paths use integer-second road weights.</p>'''
page+=figure('betweenness','City with node columns coloured and scaled by calculated weighted betweenness',f'Glyphs run from 3 m at betweenness zero to 25 m at the observed maximum. One maximum occurs at node {peak}, with normalized betweenness {A["betweenness"][peak]:.4f}. NetworkX computes exact weighted Brandes betweenness; no source-node sampling is used.')
page+='<p class="small">Definition and implementation reference: <a href="https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.betweenness_centrality.html">NetworkX betweenness documentation</a>. High betweenness is structural dependence under these shortest-path assumptions, not observed traffic volume.</p></section>'

page+=chapter('gis','08 · Spatial reasoning','Coordinates, distances and neighbourhood membership')
page+=r'''<p>In this project, one Blender unit means one metre. The $x$ axis points along the grid’s west–east direction, $y$ along south–north, and $z$ upward. The origin is a local reference point near the river centre. There is no latitude, longitude, EPSG code or real-world georeferencing.</p><p>A projected coordinate reference system also expresses planar positions in units such as metres, but it comes with a specified projection, datum and relationship to Earth. A real GIS workflow would transform source data into an appropriate projected CRS, subtract a documented local origin to keep Blender coordinates numerically small, and preserve that transformation for export. Merely naming Blender’s axes does not perform a projection.</p><div class="equation">$$d_{ij}^{\mathrm{Euclid}}=\sqrt{(x_i-x_j)^2+(y_i-y_j)^2},\qquad n(b)=\arg\min_{i\in V}\sqrt{(x_b-x_i)^2+(y_b-y_i)^2}.$$</div><p class="symbols">$d_{ij}^{\mathrm{Euclid}}$ is straight-line distance between nodes; $n(b)$ assigns building $b$ to its closest intersection. Ties use ascending node-ID order. The building record retains both this node and the straight-line snapping distance.</p><p>Nodes 35 and 36 are only 48 m apart. With their crossing removed, a straight line still has length 48 m, while walking through the southern crossing requires 336 m. Euclidean proximity and network proximity answer different questions.</p><p>Neighbourhood membership is an explicit block-generation rule based on riverbank and row, not a polygon overlay inferred afterward. All accessibility colours are inherited from the nearest node. Within-block walking links, entrances and barriers are not modeled; a building’s colour is an intersection-level proxy.</p></section>'''

page+=chapter('statistics','09 · Measure the generated city','Descriptive statistics from the actual dataset')
page+=figure('city_statistics','Histograms of facade heights and node degrees plus mean facade height by neighbourhood','Every bar is calculated from city.json. Height here means the body/facade parameter; roof projections are additional geometry. Neighbourhood differences reflect the specified generation rules.',True)
page+=table(['Quantity','Calculated value','Interpretation'],[
    ('Facade height, mean / median',f"{A['height']['mean']:.2f} / {A['height']['median']:.2f} m",'204 synthetic buildings'),
    ('Facade height, minimum / maximum',f"{A['height']['min']:.2f} / {A['height']['max']:.2f} m",'Roof height is not included'),
    ('Population standard deviation',f"{A['height']['std_population']:.2f} m",'Divide by 204, not 203: describing this complete synthetic population'),
    ('Total road centre-line length',f"{A['road_length_total_m']/1000:.3f} km",'Each undirected edge counted once'),
    ('Road edge length',f"{A['road_length']['min']:.2f}–{A['road_length']['max']:.2f} m; mean {A['road_length']['mean']:.2f} m",'Grid roads, diagonal park paths and irregular outer promenades'),
    ('Mean pairwise road travel time',f"{A['baseline_road_cost_minutes']['mean']:.3f} min",'All 2,016 unordered pairs; excludes self-pairs'),
    ('Maximum pairwise road time',f"{A['baseline_road_cost_minutes']['max']:.2f} min",'Positive integer-second walking costs')])
page+=r'''<p>A distribution is not automatically evidence of a real process. The height histogram summarizes our design choices and seed; it is not an empirical urban-height distribution. Replicating the experiment with other seeds would measure variation under this generator, not uncertainty about a real city.</p></section>'''

page+=chapter('failure','10 · A controlled intervention','Close the northern crossing')
page+=r'''<p>Remove only edge 35–36. Keep all other nodes, roads, opportunities and costs fixed, then run shortest-path calculation again. The source and destination remain connected through the southern crossing.</p>'''
page+=video('bridge_failure','closure','First half: the baseline journey. At the midpoint, the northern crossing and its markings disappear. The example journey restarts on the newly calculated southern detour. This is a comparison of two routes, not a vehicle continuing from its mid-trip position.')
page+=table(['Scenario','Road length','Walking time','Change'],[('Both crossings available',f"{A['route']['metres']:.2f} m",f"{A['route']['seconds']/60:.2f} min",'Baseline'),('Northern crossing removed',f"{A['closure_route']['metres']:.2f} m",f"{A['closure_route']['seconds']/60:.2f} min",f"+{A['closure_route']['metres']-A['route']['metres']:.2f} m, +{(A['closure_route']['seconds']-A['route']['seconds'])/60:.2f} min, +{100*(A['closure_route']['seconds']/A['route']['seconds']-1):.2f}%")])
page+=r'''<aside class="note"><p><strong>A physical bridge is not necessarily a graph-theoretic bridge.</strong> A graph bridge is an edge whose deletion increases the number of connected components. Neither crossing alone has this property here. Together, the two crossing edges form a cut separating the banks. The northern crossing is nevertheless a bottleneck for the selected journey.</p></aside><p>The visualization removes the road surface, rail geometry and its own marking batch. It does not simulate structural collapse, queue formation, congestion or emergency response. Those would require additional physical or behavioral models.</p></section>'''

page+=chapter('monte-carlo','11 · Repeated perturbations','Monte Carlo network resilience')
page+=r'''<p>One deliberate closure answers one question. To explore many disruptions, independently delete each of the 108 road/footway edges with probability $p$, keep all 64 nodes, and recompute all-pairs costs. The experiment uses $p\in\{0.03,0.08,0.15\}$ and 400 repetitions at each level: 1,200 trials in total. The random stream is seeded and consumed in a fixed order after building generation.</p><div class="equation">$$D_e^{(r)}\sim\operatorname{Bernoulli}(p),\qquad E_R^{(r)}=\{e\in E_R:D_e^{(r)}=0\},\qquad \widehat q=\frac{1}{R}\sum_{r=1}^{R}\mathbf{1}\{G_R^{(r)}\text{ is disconnected}\}.$$</div><p class="symbols">$D_e^{(r)}=1$ means edge $e$ fails in trial $r$; $E_R^{(r)}$ is the surviving road set; $R=400$ is the number of trials for one $p$; $\widehat q$ estimates the probability that at least one pair of nodes becomes disconnected. Failures are independent across edges and trials. Transit is excluded from this road-resilience experiment.</p>'''
page+=figure('monte_carlo','Three calculated Monte Carlo charts: graph disconnection probability with intervals, conditional route detour and mean accessibility loss','Error bars show 95% Wilson binomial intervals for any-node disconnection. Route increases average only trials in which the selected endpoints remain connected; accessibility loss includes every trial and every origin.',True)
page+=table(['Edge failure p','Disconnected graphs','Probability','Example pair disconnected','Mean detour, connected pair only','Mean accessibility loss'],[
    (f"{r['p']:.0%}",f"{r['disconnected_runs']} / 400",f"{r['probability_disconnected']:.2%}",f"{r['pair_disconnected_runs']} / 400",f"{r['mean_route_increase_pct_conditional']:.2f}%",f"{r['mean_accessibility_loss_pct']:.2f}%") for r in A['monte_carlo']])
page+=fr'''<p>At $p=0.08$, {mc['disconnected_runs']} of 400 graphs disconnect: $\widehat q={mc['probability_disconnected']:.4f}$, with a Wilson interval of [{mc['wilson_95'][0]:.4f}, {mc['wilson_95'][1]:.4f}]. Yet the chosen endpoint pair disconnects in only {mc['pair_disconnected_runs']} trials. “The graph disconnects” and “this journey becomes impossible” are different outcomes.</p>'''
page+=figure('resilience','Node columns in the 3D city show mean accessibility loss across the 400 trials at eight percent edge failure',f"The direct Blender simulation map encodes mean percentage accessibility loss at each origin for p = 0.08: 0% → a 3 m cyan glyph; {max(A['node_mean_loss_pct']['0.08']):.2f}% → a 25 m warm-red glyph. This measures vulnerability of origins, not node-removal criticality.")
page+=r'''<details><summary>How the uncertainty interval and loss are calculated</summary><div class="details-body"><p>A symmetric normal approximation can be misleading near zero. The Wilson interval uses the following centre and half-width:</p><div class="equation">$$m=\frac{\widehat q+z^2/(2R)}{1+z^2/R},\qquad h=\frac{z}{1+z^2/R}\sqrt{\frac{\widehat q(1-\widehat q)}{R}+\frac{z^2}{4R^2}}.$$</div><p class="symbols">The interval is $[m-h,m+h]$ with $z=1.96$, an approximate 97.5th percentile of the standard normal distribution. $R$ and $\widehat q$ have the definitions above. This interval quantifies simulation sampling error under the specified failure law.</p><p>The loss map averages $100(1-A_i^{(r)}/A_i^0)$ over all trials, where $A_i^0$ is baseline road-only accessibility and $A_i^{(r)}$ uses trial $r$’s disrupted road costs. The next section defines $A$. Unreachable destinations contribute zero; disconnected origins are never silently dropped.</p></div></details><p>Independent random road failures are a deliberately simple stress test. Floods, earthquakes and maintenance often close spatially correlated edges. No hazard map, traffic demand, capacity constraint or repair process is included. The 400 trials at each level are repetitions of one synthetic network, not 400 independently sampled cities.</p></section>'''

page+=chapter('accessibility','12 · Spatial economics','Access to opportunities, before and after transit')
page+=r'''<p>A place is accessible when many useful destinations can be reached at low travel cost. Here, every node receives ten synthetic opportunity units. Buildings contribute additional units to their nearest node according to their facade height and neighbourhood: three units per complete three metres of height, or six in Innovation District. These are designed attractiveness weights, not observed jobs, population or money.</p><div class="equation">$$A_i=\sum_{j\in V}O_j\exp(-\lambda c_{ij}),\qquad \lambda=0.18\;\mathrm{min}^{-1}.$$</div><p class="symbols">$A_i$ is accessibility at origin $i$ in weighted synthetic opportunity units; $O_j$ is opportunity at destination $j$; $c_{ij}$ is minimum generalized travel time in minutes; $\lambda$ controls sensitivity to travel cost. Include $j=i$ with $c_{ii}=0$. If $j$ is unreachable, set $c_{ij}=\infty$ and its contribution to zero.</p><p>For example, a destination offering 100 units contributes about 69.77 units at two minutes, but only 23.69 at eight minutes. The half-weight travel time is $\log(2)/0.18\approx3.85$ minutes. This decay rate is an illustrative parameter, not an estimated preference.</p>'''
page+=code_excerpt('generate_data.py','def accessibility','def summary')
page+=r'''<p>The three existing transit connections link nodes 6–22–38–54 along the east bank. Each 96 m segment costs 24 seconds in-vehicle at 240 m/min plus a 30-second boarding/transfer penalty: 54 seconds total. The proposal connects nodes 33 and 38 across 240 m at a total cost of 90 seconds. Both directions are available.</p><p>This compact graph charges the penalty on <em>every transit edge</em>, even across consecutive existing segments. It does not track whether someone stays on the same vehicle. A more realistic transit model would expand the state space to distinguish station, route, boarding and transfer states. The proposed straight connection is a schematic corridor with an assigned cost, not an engineered alignment or a funded infrastructure plan.</p>'''
page+=fr'''<div class="interactive"><div class="controls"><button type="button" data-access-view="before" aria-pressed="true">Existing transit</button><button type="button" data-access-view="after" aria-pressed="false">With new connection</button></div><img id="access-image" src="{ASSET}renders/access_before.webp" alt="Building colours show baseline accessibility with the existing east-bank transit line" loading="lazy" width="1440" height="1000"><div class="legend"><span>{lo:.0f} units · lower</span><span class="gradient" aria-hidden="true"></span><span>{hi:.0f} units · higher</span></div><p class="caption" id="access-caption" aria-live="polite">Before: four stations serve the existing eastern transit corridor.</p><p class="small">Both images use the same numerical colour scale. Only the assigned node accessibility changes the building facade colour; roof and glazing materials remain fixed. Lighting affects perceived brightness.</p></div>'''
page+=video('transit_accessibility','access_after','Before → after: the new connection appears and building colours interpolate between the two calculated accessibility maps. Intermediate colours are a visual transition, not intermediate model solves.')
page+=figure('accessibility_statistics','Scatter comparison of before versus after accessibility and a coordinate map of percentage gains','Left: each of the 64 origin nodes lies on or above the identity line. Right: percentage gain uses the same origin-specific baseline in its denominator.',True)
page+=fr'''<p>Mean node accessibility rises from <strong>{A['accessibility_mean_before']:.2f}</strong> to <strong>{A['accessibility_mean_after']:.2f}</strong> units, a <strong>{A['accessibility_mean_gain_pct']:.2f}% increase in the mean</strong>. This is the percentage change in two arithmetic means, not the mean of node percentage changes. The largest individual-node increase is {max(A['accessibility_gain_pct']):.2f}%.</p>'''
page+=r'''<aside class="note"><p><strong>What can be concluded?</strong> Adding a usable positive-cost edge cannot increase the minimum path cost: every old route remains feasible. Since $O_j\ge0$ and exponential decay decreases with cost, accessibility cannot decrease. The validator checks this at all 64 origins.</p><p><strong>What cannot be concluded?</strong> These synthetic quantities are not estimates of a real causal policy effect. The experiment has no observed counterfactual, land prices, household sorting, equilibrium relocation, service frequency, capacity or construction cost. It is a transparent comparative exercise with opportunities held fixed.</p></aside></section>'''

page+=chapter('engineering','13 · Inside the generator','Procedural engineering and Blender performance')
page+=r'''<p>The preliminary six-building capability test used 848 mesh objects. It proved that geometry, rendering and export worked, but its window-by-window object structure would scale poorly. The city uses a different representation: twelve shared building meshes, one object per building, shared tree and lamp meshes, and joined static batches.</p>'''
page+=table(['Representation','Master city','Browser export'],[
    ('Building identity','204 named B### objects with node and neighbourhood properties','204 building nodes retain IDs in glTF extras'),
    ('Repeated architecture','Twelve linked architectural families; joined panes, sills and roof details','Twelve simplified architectural families; flat window faces, fewer roof parts'),
    ('Vegetation and furniture','162 trees / seven shared meshes; 64 lamps / one mesh','Seven simplified tree meshes; shared lamp geometry'),
    ('Human scale','48 pedestrians / six clothing families; twelve animated instances','Six simplified static pose meshes; no walking morph payload'),
    ('Road system','One road object per graph edge; batched junctions and regular markings','Same street layout and identity'),
    ('Analytical modes','Hidden collections; parameter-driven materials and glyphs',f"Separate {V['glb']['graph_web']['triangles_instanced']:,}-triangle graph GLB"),
    ('Lighting and cameras','Three cameras, sun, two studio area lights and world','Excluded; the browser provides viewing light'),
    ('Geometry count',f"{V['master_triangles_instanced']:,} instanced triangles",f"{V['glb']['city_web']['triangles_instanced']:,} instanced triangles")])
page+=r'''<h3>Shared meshes save storage; they do not erase drawing cost</h3><p>A mesh datablock stores the archetype once, while object transforms place it repeatedly. The renderer still draws the geometry for every visible instance. The report therefore provides both unique mesh triangles and instance-expanded triangles. Material groups may create multiple browser draw calls; a small download alone does not guarantee fast rendering on every phone.</p><h3>Topology and level of detail</h3><p>Closed box components use outward-wound quads; the export triangulates them. Window panes are intentional surface faces with small offsets, and archetypes contain disconnected decorative components. The meshes are suitable for visualization, not guaranteed watertight solids for fabrication. The validator checks empty meshes and finite coordinates, but does not certify manifoldness or perform full collision detection.</p><p>The master retains floor bands, window sills and roof details. The web version removes those details from its archetypes before export and omits studio and analytical objects. It is a separate level of detail generated in memory after the master is saved. The compressed master happens to be smaller on disk than the GLB; the browser model is nevertheless substantially lighter in instance-expanded geometry.</p><h3>Modifiers, arrays and Geometry Nodes</h3><p>The prototype used bevel and weighted-normal modifiers. This city deliberately uses explicit low-poly geometry with no building modifiers to evaluate at render time. Arrays would be a reasonable option for facade editing; here, Python batches the same repeated elements directly into archetype meshes. Geometry Nodes is not used because mesh reuse already solves the repetition problem without another system to debug.</p><h3>Composition and rendering</h3><p>The static overview uses an orthographic camera; a second gives the close-up and a third looks more steeply downward for analytical clarity. The 24-second hero retains five perspective shots, including a lower street tracking shot with people and foreground trees. City stills and the hero use Eevee at 16 samples; analytical videos use 12 samples. One sun casts shadows, with broad area-light fill. Image-space glyphs and schematic transit offsets improve visibility without changing network costs.</p><h3>Animation is editable data</h3><p>The three animation files contain keyframes. Route markers interpolate along actual path segments. The closure switches object visibility at frame 113; the transit animation interpolates material colour after a new edge appears. Each 224-frame analytical animation uses four smooth camera shots and is encoded as 960 × 540 H.264 at 16 fps: 14 seconds, yuv420p, BT.709, fast-start metadata and no audio. Raw frames remain outside the repository.</p></section>'''

page+=chapter('interactive','14 · Inspect the geometry','Rotate the city yourself')
page+=fr'''<p>The interactive export keeps buildings as distinct nodes and uses {V['glb']['city_web']['triangles_instanced']:,} triangles when instances are counted. Loading is optional. The image remains available if WebGL or JavaScript is unavailable.</p><div class="viewer-actions"><button type="button" data-model="city" aria-pressed="false">Load city · {V['glb']['city_web']['bytes']/1048576:.2f} MiB</button><button type="button" data-model="graph" aria-pressed="false">Load graph · {V['glb']['graph_web']['bytes']/1024:.0f} KiB</button></div><div class="viewer-shell" id="viewer-shell"><img class="fallback" id="model-fallback" src="{ASSET}renders/hero.webp" alt="Static fallback of the complete city; use the model buttons above for interactive 3D" loading="lazy" width="1440" height="1000"></div><p id="viewer-status" class="status" aria-live="polite">The model has not been downloaded. Select a model above to begin.</p><p class="small">Drag to rotate, scroll or pinch to zoom. This viewer does not expose Blender editing or per-building inspection panels; use the .blend file for those. Download {link('models/city_web.glb','the city GLB')} or {link('models/graph_web.glb','the graph GLB')}. The pinned, locally bundled <a href="https://modelviewer.dev/">model-viewer</a> module adds the browser controls.</p></section>'''

page+=chapter('reproduce','15 · Evidence and reproduction','What Astra generated and what I checked')
page+=r'''<p>The “checked” record below describes automated and agent-assisted inspection performed in this project. It does not claim that the site author has already reviewed the result. Human browser and Blender review is the next step.</p>'''
page+=table(['Generated by the agent','Concrete check performed'],[
    ('Seeded city and twelve architectural families','Reopened saved master; counted building IDs and twelve shared meshes; checked empty meshes, materials, finite transforms and dimensions'),
    ('108 road/footway meshes and graph overlays','Compared every edge midpoint, length and cost, and every node glyph coordinate, against city.json; checked its embedded SHA-256'),
    ('Shortest paths and access values','All 4,096 Floyd–Warshall entries matched independently computed Dijkstra costs; checked degree sum and monotone accessibility'),
    ('City and graph GLBs','Parsed GLB headers and buffers, counted per-instance triangles, checked embedded building IDs, then reimported both into Blender'),
    ('Renders and animation','Inspected rendered views; corrected coplanar road overlap and camera clipping; decoded all videos and checked durations and dimensions'),
    ('Standalone HTML and viewer','Served over local HTTP; checked asset responses, desktop/mobile overflow, equation rendering, graph controls, GLB loading and video playback in Chromium')])
page+='<p>Reports: '+link('data/scene_validation.json','scene and GLB validation')+' · '+link('data/calculation_validation.json','mathematical consistency')+' · '+link('data/world_calculation_validation.json','independent full-trial replay')+' · '+link('data/world_revision_comparison.json','previous/revised measurements')+' · '+link('data/local_qa.json','local browser and asset QA')+'. The full terminal logs are retained with the source artifacts.</p>'
page+=table(['Measured characteristic','Recorded value'],[
    ('Blender',V['blender_version']),('Seed',C['seed']),('Blender master objects / meshes',f"{V['master_objects']} / {V['master_mesh_objects']} (includes hidden analytical objects)"),
    ('Buildings / shared building meshes',f"{V['buildings']} / {V['unique_building_meshes']}"),('Road nodes / edges',f"{A['nodes']} / {A['road_edges']}"),
    ('Trees / tree archetypes',f"{V['trees']} / {V['tree_archetypes']}"),('Pedestrians / animated',f"{V['pedestrians']} / {V['animated_pedestrians']}"),
    ('Existing transit / proposed edges','3 / 1'),('Master polygons / triangles',f"{V['master_polygons_instanced']:,} / {V['master_triangles_instanced']:,}, instance-expanded"),
    ('Master unique triangles',f"{V['master_unique_triangles']:,}"),('City GLB triangles',f"{V['glb']['city_web']['triangles_instanced']:,} instance-expanded; {V['glb']['city_web']['triangles_unique']:,} stored across unique exported meshes"),
    ('Compressed master .blend',f"{V['blend_bytes']:,} bytes"),('City GLB',f"{V['glb']['city_web']['bytes']:,} bytes"),
    ('City still resolution','1440 × 1000; anatomy 1440 × 680'),('Monte Carlo trials','400 × 3 = 1,200'),
    ('Graph/data computation',f"{A['generation_seconds']:.3f} s; NetworkX {A['networkx_version']}"),
    ('Master construction and export',f"{B['generation_and_export_seconds']:.3f} s inside Blender, excluding process startup"),
    ('City still render time',f"{sum(R.values()):.1f} s total across {len(R)} timed city views; anatomy excluded"),
    ('Analytical frame rendering',f"{sum(t['seconds'] for t in T.values()):.1f} s total; hardware-specific" if len(T)==3 else 'Rendering in progress')])
page+=r'''<h3>Regenerate locally</h3><p>The website itself has no build system or package installation step. Regeneration uses Python libraries and Blender as offline authoring tools. The scripts locate their output directory relative to their own files.</p><pre><code># From the repository root. Substitute your Blender executable if needed.
python3 -m venv /tmp/astra-city-env
/tmp/astra-city-env/bin/pip install -r research/gpt-6-astra-blender/requirements.txt
/tmp/astra-city-env/bin/python research/gpt-6-astra-blender/scripts/generate_data.py
/tmp/astra-city-env/bin/python research/gpt-6-astra-blender/scripts/generate_charts.py
/tmp/astra-city-env/bin/python research/gpt-6-astra-blender/scripts/run_blender_pipeline.py \
  --blender "$HOME/Documents/astra-blender-test/blender-4.5.13-linux-x64/blender"
/tmp/astra-city-env/bin/python research/gpt-6-astra-blender/scripts/package_assets.py
/tmp/astra-city-env/bin/python research/gpt-6-astra-blender/scripts/build_page.py
python3 -m http.server 8000 --bind 127.0.0.1</code></pre><p class="small">FFmpeg with libx264 must be on PATH for video encoding. The seed fixes geometry and simulation draws; rendering can vary slightly with Blender version, hardware and denoiser. The original portable Blender installation is reused, but none of the preliminary test’s output files are copied into this project.</p>'''
prompt=escape((ROOT/'data/original_prompt.txt').read_text())
page+='<details id="prompt"><summary>Complete original OpenCode implementation prompt</summary><div class="details-body"><p class="small">The supplied project request, including its performance guidance, is retained verbatim below. It describes the requested workflow; the execution provenance is stated near the beginning of this page.</p>'+link('data/original_prompt.txt','Download the prompt as plain text')+'<pre class="prompt"><code>'+prompt+'</code></pre></div></details></section>'

page+=chapter('files','16 · Open the laboratory','Files and source code')
page+='<div class="grid downloads"><div><h3>Blender and browser models</h3>'+''.join(link(p,t) for p,t in [
    ('blender/city_master.blend','Editable master city'),('blender/building_anatomy.blend','Building anatomy scene'),
    ('blender/shortest_path.blend','Shortest-path keyframes'),('blender/bridge_failure.blend','Bridge-closure keyframes'),
    ('blender/transit_accessibility.blend','Transit accessibility keyframes'),('models/city_web.glb','Optimized city GLB'),('models/graph_web.glb','Graph-only GLB')])+'</div><div><h3>Data and reproducibility</h3>'+''.join(link(p,t) for p,t in [
    ('data/city.json','City, graph and building parameters'),('data/analysis.json','Calculated metrics and experiment summaries'),('data/disruption_trials.json','All 1,200 individual disruption trials'),
    ('data/scene_validation.json','Saved-scene validation'),('data/local_qa.json','Local browser QA'),('data/file_manifest.json','Complete asset inventory and SHA-256 checksums'),('README.md','Reproduction and editing guide')])+'</div></div>'
page+='<h3>Small scripts, explicit responsibilities</h3>'+table(['Script','Responsibility'],[(link('scripts/'+name,name),desc) for name,desc in [
    ('generate_data.py','Build the synthetic dataset; calculate exact network metrics and Monte Carlo outcomes'),('build_city.py','Construct the master and simplified GLBs from that dataset'),('world_assets.py','Generate shared branching trees, clothed people and lightweight walking poses'),
    ('render_views.py','Set analytical modes, render the city and explain one building'),('render_animations.py','Save keyframes, render frame sequences and encode three MP4s'),
    ('validate_blender.py','Inspect saved geometry and reimport exports'),('generate_charts.py','Plot the computed values'),('package_assets.py','Create efficient WebP derivatives and asset inventory'),
    ('build_page.py','Assemble this page from measured results'),('qa_site.py','Test local HTTP assets and interactive browser behavior'),('run_blender_pipeline.py','Run Blender stages and retain logs')]])
page+='</section>'+chapter('limitations','17 · Interpret with care','Limitations and useful next experiments')
page+=r'''<p>The city retains a regular parcel grid, supplemented by diagonal park paths and irregular outer walking loops. It has one undirected walking network, simplified transit costs, fixed synthetic opportunity weights and a planar coordinate grid. Buildings have no interior layouts. Tree foliage uses clustered low-poly volumes and pedestrians have simplified faces and gait; windows are stylized surfaces. No real elevation, geographic location, mobility observation or economic outcome is inferred.</p><p>The current resilience experiment changes edges, not demand or capacity. A shortest path is an optimal route under fixed costs; it does not predict which routes people actually choose. Future experiments could add correlated flood zones, directed streets, turn penalties, transfer-aware transit states, heterogeneous opportunities and sensitivity analysis over the decay parameter.</p><p>Further engineering could batch web geometry by neighbourhood, adopt GPU instancing extensions, or add distance-dependent levels of detail. Those tradeoffs should be measured on representative devices: they can improve drawing performance while reducing per-building browser editability.</p>
<div class="conclusion"><h3>A model you can question</h3><p>The useful achievement is the connection between editable geometry, explicit data and reproducible calculations. A bridge is a visible object and a named graph edge. A building has a spatial address and an inherited accessibility value. Changing an assumption produces a new calculation that can be traced back to both.</p><p>Open the model, inspect the route, alter a parameter, and rerun the scripts. The scene is a starting point for experiments whose assumptions remain visible.</p></div></section>
<section class="chapter" id="references"><h2>Technical references</h2><ol class="reference-list"><li><a href="https://docs.blender.org/api/4.5/">Blender 4.5 Python API</a> — scene data, meshes, objects, rendering and operators. The actual scripts were executed with 4.5.13 LTS.</li><li><a href="https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.betweenness_centrality.html">NetworkX: weighted betweenness centrality</a> — endpoint convention, normalization and positive weight requirements.</li><li><a href="https://networkx.org/documentation/stable/reference/algorithms/shortest_paths.html">NetworkX: shortest-path algorithms</a> — the graph computation library used here.</li><li><a href="https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html">Khronos glTF 2.0 specification</a> — meshes, nodes, accessors and binary GLB structure.</li><li><a href="https://modelviewer.dev/">model-viewer documentation</a> — browser interaction and compatibility. Version 4.1.0 is bundled locally with its license.</li></ol><p class="small">No external city models, commercial assets or paper-specific empirical claims are used. All reported city and simulation quantities come from the downloadable project data.</p></section>
</main><footer class="footer-nav"><a href="../index.html">Home</a><span class="sep">|</span><a href="../research.html">Research</a><span class="sep">|</span><a href="#main">Back to top ↑</a></footer></div></body></html>'''
(ROOT.parent/'gpt-6-astra-blender.html').write_text(page+'\n')
print(f'PAGE_BUILT: {len(page):,} characters')
