((global) => {
  "use strict";

  const exercises = [
    {
      id: "sum-salary-01",
      title: "Calculate Total Salary",
      functionCategory: "SUM",
      difficulty: "Beginner",
      prompt: "Calculate the total salary of all six employees.",
      targetCell: "H4",
      expectedValue: 450000,
      hints: ["The salaries are in D2:D7.", "SUM can add one continuous range."],
      solutionFormula: "=SUM(D2:D7)",
      acceptedFunctionSets: [["SUM"]]
    },
    {
      id: "average-salary-01",
      title: "Calculate Average Salary",
      functionCategory: "AVERAGE",
      difficulty: "Beginner",
      prompt: "Calculate the average salary of all six employees.",
      targetCell: "H4",
      expectedValue: 75000,
      hints: ["The salaries are in D2:D7.", "Use AVERAGE with the complete salary range."],
      solutionFormula: "=AVERAGE(D2:D7)",
      acceptedFunctionSets: [["AVERAGE"]]
    },
    {
      id: "if-maya-salary-01",
      title: "Classify Maya's Salary",
      functionCategory: "IF",
      difficulty: "Beginner",
      prompt: "Return \"High\" if Maya's salary is greater than 70000. Otherwise return \"Standard\".",
      targetCell: "H4",
      expectedValue: "High",
      hints: ["Maya's salary is in D2.", "Test D2>70000, then provide the two text results."],
      solutionFormula: "=IF(D2>70000,\"High\",\"Standard\")",
      acceptedFunctionSets: [["IF"]]
    },
    {
      id: "and-maya-01",
      title: "Check Maya's Salary and Experience",
      functionCategory: "AND",
      difficulty: "Beginner",
      prompt: "Return TRUE if Maya earns more than 70000 and has at least 4 years.",
      targetCell: "H4",
      expectedValue: true,
      hints: ["Maya's salary and years are in D2 and E2.", "AND requires both comparisons to be TRUE."],
      solutionFormula: "=AND(D2>70000,E2>=4)",
      acceptedFunctionSets: [["AND"]]
    },
    {
      id: "countif-finance-01",
      title: "Count Finance Employees",
      functionCategory: "COUNTIF",
      difficulty: "Beginner",
      prompt: "Count employees in Finance.",
      targetCell: "H4",
      expectedValue: 3,
      hints: ["Departments are in C2:C7.", "Use \"Finance\" as the COUNTIF criterion."],
      solutionFormula: "=COUNTIF(C2:C7,\"Finance\")",
      acceptedFunctionSets: [["COUNTIF"]]
    },
    {
      id: "sumif-finance-01",
      title: "Total Finance Salary",
      functionCategory: "SUMIF",
      difficulty: "Intermediate",
      prompt: "Find the total salary of Finance employees.",
      targetCell: "H4",
      expectedValue: 216000,
      hints: ["Test departments in C2:C7.", "Add the aligned salaries in D2:D7."],
      solutionFormula: "=SUMIF(C2:C7,\"Finance\",D2:D7)",
      acceptedFunctionSets: [["SUMIF"]]
    },
    {
      id: "averageif-finance-01",
      title: "Average Finance Salary",
      functionCategory: "AVERAGEIF",
      difficulty: "Intermediate",
      prompt: "Find the average salary of Finance employees.",
      targetCell: "H4",
      expectedValue: 72000,
      hints: ["Test C2:C7 for Finance.", "Average the aligned values in D2:D7."],
      solutionFormula: "=AVERAGEIF(C2:C7,\"Finance\",D2:D7)",
      acceptedFunctionSets: [["AVERAGEIF"]]
    },
    {
      id: "countifs-finance-salary-01",
      title: "Count Higher-Paid Finance Employees",
      functionCategory: "COUNTIFS",
      difficulty: "Intermediate",
      prompt: "Count Finance employees earning more than 70000.",
      targetCell: "H4",
      expectedValue: 2,
      hints: ["Use one criterion for C2:C7 and another for D2:D7.", "The salary criterion is \" >70000\" without the leading space."],
      solutionFormula: "=COUNTIFS(C2:C7,\"Finance\",D2:D7,\">70000\")",
      acceptedFunctionSets: [["COUNTIFS"]]
    },
    {
      id: "sumifs-finance-years-01",
      title: "Finance Salary with Experience",
      functionCategory: "SUMIFS",
      difficulty: "Intermediate",
      prompt: "Find total salary for Finance employees with at least 4 years.",
      targetCell: "H4",
      expectedValue: 148000,
      hints: ["D2:D7 is the sum range.", "Test C2:C7 for Finance and E2:E7 with the criterion >=4."],
      solutionFormula: "=SUMIFS(D2:D7,C2:C7,\"Finance\",E2:E7,\">=4\")",
      acceptedFunctionSets: [["SUMIFS"]]
    },
    {
      id: "vlookup-id-salary-01",
      title: "Look Up Salary by Employee ID",
      functionCategory: "VLOOKUP",
      difficulty: "Intermediate",
      prompt: "Use Employee ID 1004 to return the salary.",
      targetCell: "H4",
      expectedValue: 64000,
      hints: ["The lookup table is A2:E7.", "Salary is column 4 of that table; use an exact match."],
      solutionFormula: "=VLOOKUP(1004,A2:E7,4,FALSE)",
      acceptedFunctionSets: [["VLOOKUP"]]
    },
    {
      id: "xlookup-basic-01",
      title: "Find Lucas's Salary",
      functionCategory: "XLOOKUP",
      difficulty: "Beginner",
      prompt: "Use Lucas's name to return his salary.",
      targetCell: "H4",
      expectedValue: 76000,
      hints: ["The names are in B2:B7.", "The salaries are in D2:D7.", "XLOOKUP needs a lookup value, lookup array, and return array."],
      solutionFormula: "=XLOOKUP(\"Lucas\",B2:B7,D2:D7)",
      acceptedFunctionSets: [["XLOOKUP"]]
    },
    {
      id: "xlookup-left-01",
      title: "Find Lucas's Employee ID",
      functionCategory: "XLOOKUP",
      difficulty: "Intermediate",
      prompt: "Use Lucas's name to return his Employee ID from the left.",
      targetCell: "H4",
      expectedValue: 1006,
      hints: ["Search names in B2:B7.", "Employee IDs are in A2:A7, to the left of the names."],
      solutionFormula: "=XLOOKUP(\"Lucas\",B2:B7,A2:A7)",
      acceptedFunctionSets: [["XLOOKUP"]]
    },
    {
      id: "match-noah-01",
      title: "Find Noah's Position",
      functionCategory: "MATCH",
      difficulty: "Intermediate",
      prompt: "Find Noah's position within the employee-name list.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["The names are in B2:B7.", "Use match type 0 for an exact position."],
      solutionFormula: "=MATCH(\"Noah\",B2:B7,0)",
      acceptedFunctionSets: [["MATCH"]]
    },
    {
      id: "index-name-01",
      title: "Return a Name by Position",
      functionCategory: "INDEX",
      difficulty: "Intermediate",
      prompt: "Return the employee name at row position 4 and column position 2 within A2:E7.",
      targetCell: "H4",
      expectedValue: "Noah",
      hints: ["Use A2:E7 as the INDEX array.", "The requested relative row is 4 and column is 2."],
      solutionFormula: "=INDEX(A2:E7,4,2)",
      acceptedFunctionSets: [["INDEX"]]
    },
    {
      id: "index-match-lucas-01",
      title: "Find Lucas's Salary with INDEX and MATCH",
      functionCategory: "INDEX + MATCH",
      difficulty: "Advanced",
      prompt: "Find Lucas's salary using INDEX and MATCH.",
      targetCell: "H4",
      expectedValue: 76000,
      hints: ["MATCH can find Lucas's position in B2:B7.", "Use exact match type 0.", "Pass the MATCH position to INDEX over D2:D7."],
      solutionFormula: "=INDEX(D2:D7,MATCH(\"Lucas\",B2:B7,0))",
      acceptedFunctionSets: [["INDEX", "MATCH"]]
    },
    {
      id: "len-maya-name-01",
      title: "Count Maya's Name",
      functionCategory: "LEN",
      difficulty: "Beginner",
      prompt: "Count the characters in Maya's name.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["Maya's name is in B2.", "LEN counts every character in its text argument."],
      solutionFormula: "=LEN(B2)",
      acceptedFunctionSets: [["LEN"]]
    },
    {
      id: "left-lucas-name-01",
      title: "Take Lucas's First Letters",
      functionCategory: "LEFT",
      difficulty: "Beginner",
      prompt: "Return the first two letters of Lucas's name.",
      targetCell: "H4",
      expectedValue: "Lu",
      hints: ["Lucas's name is in B7.", "Ask LEFT for 2 characters."],
      solutionFormula: "=LEFT(B7,2)",
      acceptedFunctionSets: [["LEFT"]]
    },
    {
      id: "right-sofia-name-01",
      title: "Take Sofia's Last Letters",
      functionCategory: "RIGHT",
      difficulty: "Beginner",
      prompt: "Return the last two letters of Sofia's name.",
      targetCell: "H4",
      expectedValue: "ia",
      hints: ["Sofia's name is in B4.", "RIGHT takes characters from the end."],
      solutionFormula: "=RIGHT(B4,2)",
      acceptedFunctionSets: [["RIGHT"]]
    },
    {
      id: "mid-vancouver-01",
      title: "Extract from Vancouver",
      functionCategory: "MID",
      difficulty: "Beginner",
      prompt: "Return characters 4 through 6 from the supplied Vancouver text.",
      targetCell: "H4",
      expectedValue: "cou",
      hints: ["The practice text is in H3.", "Start at character 4 and request 3 characters."],
      solutionFormula: "=MID(H3,4,3)",
      acceptedFunctionSets: [["MID"]],
      setup: [{ cell: "H3", value: "Vancouver" }]
    },
    {
      id: "upper-finance-01",
      title: "Uppercase Finance",
      functionCategory: "UPPER",
      difficulty: "Beginner",
      prompt: "Convert the Finance department in C2 to uppercase.",
      targetCell: "H4",
      expectedValue: "FINANCE",
      hints: ["The department is in C2.", "UPPER changes every letter to uppercase."],
      solutionFormula: "=UPPER(C2)",
      acceptedFunctionSets: [["UPPER"]]
    },
    {
      id: "trim-name-spacing-01",
      title: "Clean Name Spacing",
      functionCategory: "TRIM",
      difficulty: "Beginner",
      prompt: "Clean the extra spaces from the supplied Maya Chen text.",
      targetCell: "H4",
      expectedValue: "Maya Chen",
      hints: ["The text with extra spaces is in H3.", "TRIM cleans outer and repeated interior spaces."],
      solutionFormula: "=TRIM(H3)",
      acceptedFunctionSets: [["TRIM"]],
      setup: [{ cell: "H3", value: "   Maya    Chen   " }]
    },
    {
      id: "concat-name-department-01",
      title: "Build an Employee Label",
      functionCategory: "CONCAT",
      difficulty: "Beginner",
      prompt: "Combine Maya and Finance as Maya - Finance.",
      targetCell: "H4",
      expectedValue: "Maya - Finance",
      hints: ["Maya is in B2 and Finance is in C2.", "Include \" - \" as the middle CONCAT piece."],
      solutionFormula: "=CONCAT(B2,\" - \",C2)",
      acceptedFunctionSets: [["CONCAT"]]
    },
    {
      id: "textjoin-first-names-01",
      title: "Join the First Three Names",
      functionCategory: "TEXTJOIN",
      difficulty: "Intermediate",
      prompt: "Join Maya, Liam, and Sofia with comma-space separators.",
      targetCell: "H4",
      expectedValue: "Maya, Liam, Sofia",
      hints: ["The three names are in B2:B4.", "Use \", \" as the delimiter.", "Set ignore_empty to TRUE."],
      solutionFormula: "=TEXTJOIN(\", \",TRUE,B2:B4)",
      acceptedFunctionSets: [["TEXTJOIN"]]
    },
    {
      id: "search-vancouver-01",
      title: "Find a Character Position",
      functionCategory: "SEARCH",
      difficulty: "Beginner",
      prompt: "Find the position of c inside the supplied Vancouver text.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["The practice text is in H3.", "SEARCH returns a one-based position and ignores case."],
      solutionFormula: "=SEARCH(\"c\",H3)",
      acceptedFunctionSets: [["SEARCH"]],
      setup: [{ cell: "H3", value: "Vancouver" }]
    },
    {
      id: "substitute-department-01",
      title: "Rename a Department",
      functionCategory: "SUBSTITUTE",
      difficulty: "Intermediate",
      prompt: "Change Finance Department to Finance Division.",
      targetCell: "H4",
      expectedValue: "Finance Division",
      hints: ["The source text is in H3.", "Replace Department with Division."],
      solutionFormula: "=SUBSTITUTE(H3,\"Department\",\"Division\")",
      acceptedFunctionSets: [["SUBSTITUTE"]],
      setup: [{ cell: "H3", value: "Finance Department" }]
    },
    {
      id: "date-build-2026-01",
      title: "Create a Calendar Date",
      functionCategory: "DATE",
      difficulty: "Beginner",
      prompt: "Create August 17, 2026 using DATE.",
      targetCell: "H4",
      expectedValue: 46251,
      expectedNumberFormat: "Date",
      hints: ["DATE accepts year, month, and day in that order.", "Use 2026, 8, and 17."],
      solutionFormula: "=DATE(2026,8,17)",
      acceptedFunctionSets: [["DATE"]]
    },
    {
      id: "year-from-date-2026-01",
      title: "Extract the Year",
      functionCategory: "YEAR",
      difficulty: "Beginner",
      prompt: "Return the year from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 2026,
      hints: ["H3 contains a date-formatted serial.", "YEAR returns an ordinary number."],
      solutionFormula: "=YEAR(H3)",
      acceptedFunctionSets: [["YEAR"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "month-from-date-2026-01",
      title: "Extract the Month",
      functionCategory: "MONTH",
      difficulty: "Beginner",
      prompt: "Return the month number from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 8,
      hints: ["H3 contains August 17, 2026.", "MONTH returns a number from 1 through 12."],
      solutionFormula: "=MONTH(H3)",
      acceptedFunctionSets: [["MONTH"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "day-from-date-2026-01",
      title: "Extract the Day",
      functionCategory: "DAY",
      difficulty: "Beginner",
      prompt: "Return the day of the month from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 17,
      hints: ["H3 contains August 17, 2026.", "DAY returns the calendar day number."],
      solutionFormula: "=DAY(H3)",
      acceptedFunctionSets: [["DAY"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "days-between-august-2026-01",
      title: "Count Days Between Dates",
      functionCategory: "DAYS",
      difficulty: "Beginner",
      prompt: "Find the number of days from August 10 to August 17, 2026.",
      targetCell: "H4",
      expectedValue: 7,
      hints: ["H2 contains the start date and H3 contains the end date.", "DAYS takes the end date first."],
      solutionFormula: "=DAYS(H3,H2)",
      acceptedFunctionSets: [["DAYS"]],
      setup: [
        { cell: "H2", value: "=DATE(2026,8,10)" },
        { cell: "H3", value: "=DATE(2026,8,17)" }
      ]
    },
    {
      id: "edate-three-months-01",
      title: "Move Forward Three Months",
      functionCategory: "EDATE",
      difficulty: "Intermediate",
      prompt: "Move the practice date in H3 forward by three months.",
      targetCell: "H4",
      expectedValue: 46343,
      expectedNumberFormat: "Date",
      hints: ["H3 contains August 17, 2026.", "Use a positive month offset of 3."],
      solutionFormula: "=EDATE(H3,3)",
      acceptedFunctionSets: [["EDATE"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "eomonth-august-2026-01",
      title: "Find the End of August",
      functionCategory: "EOMONTH",
      difficulty: "Intermediate",
      prompt: "Return the final day of the practice date's current month.",
      targetCell: "H4",
      expectedValue: 46265,
      expectedNumberFormat: "Date",
      hints: ["H3 contains August 17, 2026.", "Use a month offset of 0 for the same month."],
      solutionFormula: "=EOMONTH(H3,0)",
      acceptedFunctionSets: [["EOMONTH"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "weekday-monday-2026-01",
      title: "Number a Monday",
      functionCategory: "WEEKDAY",
      difficulty: "Intermediate",
      prompt: "Using return type 2, determine the weekday number for the practice date.",
      targetCell: "H4",
      expectedValue: 1,
      hints: ["H3 contains Monday, August 17, 2026.", "Return type 2 makes Monday equal 1."],
      solutionFormula: "=WEEKDAY(H3,2)",
      acceptedFunctionSets: [["WEEKDAY"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "round-two-decimals-01",
      title: "Round to Two Decimals",
      functionCategory: "ROUND",
      difficulty: "Beginner",
      prompt: "Round 12.3456 to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.35,
      hints: ["ROUND changes the stored numeric result.", "Use 2 for num_digits."],
      solutionFormula: "=ROUND(12.3456,2)",
      acceptedFunctionSets: [["ROUND"]]
    },
    {
      id: "roundup-two-decimals-01",
      title: "Round Away from Zero",
      functionCategory: "ROUNDUP",
      difficulty: "Beginner",
      prompt: "Round 12.341 upward to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.35,
      hints: ["ROUNDUP always moves away from zero.", "Use 2 decimal places."],
      solutionFormula: "=ROUNDUP(12.341,2)",
      acceptedFunctionSets: [["ROUNDUP"]]
    },
    {
      id: "rounddown-two-decimals-01",
      title: "Round Toward Zero",
      functionCategory: "ROUNDDOWN",
      difficulty: "Beginner",
      prompt: "Round 12.349 downward to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.34,
      hints: ["ROUNDDOWN moves toward zero.", "Use 2 decimal places."],
      solutionFormula: "=ROUNDDOWN(12.349,2)",
      acceptedFunctionSets: [["ROUNDDOWN"]]
    },
    {
      id: "int-negative-01",
      title: "Round a Negative Integer Down",
      functionCategory: "INT",
      difficulty: "Beginner",
      prompt: "Use INT on -8.9.",
      targetCell: "H4",
      expectedValue: -9,
      hints: ["INT rounds downward, not toward zero."],
      solutionFormula: "=INT(-8.9)",
      acceptedFunctionSets: [["INT"]]
    },
    {
      id: "abs-negative-01",
      title: "Find an Absolute Value",
      functionCategory: "ABS",
      difficulty: "Beginner",
      prompt: "Return the absolute value of -125.",
      targetCell: "H4",
      expectedValue: 125,
      hints: ["ABS returns distance from zero."],
      solutionFormula: "=ABS(-125)",
      acceptedFunctionSets: [["ABS"]]
    },
    {
      id: "mod-remainder-01",
      title: "Find a Remainder",
      functionCategory: "MOD",
      difficulty: "Beginner",
      prompt: "Find the remainder when 25 is divided by 7.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["MOD takes the number first and divisor second."],
      solutionFormula: "=MOD(25,7)",
      acceptedFunctionSets: [["MOD"]]
    },
    {
      id: "iferror-division-01",
      title: "Handle Division by Zero",
      functionCategory: "IFERROR",
      difficulty: "Intermediate",
      prompt: "Use IFERROR so division by zero returns Cannot divide.",
      targetCell: "H4",
      expectedValue: "Cannot divide",
      hints: ["Use 10/0 as the primary expression.", "Use \"Cannot divide\" as the fallback."],
      solutionFormula: "=IFERROR(10/0,\"Cannot divide\")",
      acceptedFunctionSets: [["IFERROR"]]
    },
    {
      id: "ifna-xlookup-01",
      title: "Handle a Missing Lookup",
      functionCategory: "IFNA",
      difficulty: "Intermediate",
      prompt: "Use XLOOKUP for Olivia and return Not found with IFNA.",
      targetCell: "H4",
      expectedValue: "Not found",
      hints: ["Search Olivia in B2:B7 and return from D2:D7.", "Wrap XLOOKUP with IFNA."],
      solutionFormula: "=IFNA(XLOOKUP(\"Olivia\",B2:B7,D2:D7),\"Not found\")",
      acceptedFunctionSets: [["IFNA", "XLOOKUP"]]
    },
    {
      id: "median-salary-01",
      title: "Find the Middle Salary",
      functionCategory: "MEDIAN",
      difficulty: "Beginner",
      prompt: "Find the median salary across the six employees.",
      targetCell: "H4",
      expectedValue: 74000,
      hints: ["The salary range is D2:D7.", "MEDIAN orders the six salaries and uses the two middle values."],
      solutionFormula: "=MEDIAN(D2:D7)",
      acceptedFunctionSets: [["MEDIAN"]]
    },
    {
      id: "mode-years-01",
      title: "Find the Most Common Experience",
      functionCategory: "MODE.SNGL",
      difficulty: "Beginner",
      prompt: "Return the most frequently occurring Years value.",
      targetCell: "H4",
      expectedValue: 5,
      hints: ["Years are in E2:E7.", "MODE.SNGL returns the numeric value occurring most often."],
      solutionFormula: "=MODE.SNGL(E2:E7)",
      acceptedFunctionSets: [["MODE.SNGL"]]
    },
    {
      id: "stdev-s-salary-01",
      title: "Estimate Sample Salary Spread",
      functionCategory: "STDEV.S",
      difficulty: "Intermediate",
      prompt: "Treat the six salaries as a sample and calculate their sample standard deviation.",
      targetCell: "H4",
      expectedValue: 9077.44457432817,
      hints: ["Use D2:D7.", "The sample version uses STDEV.S and an n − 1 denominator."],
      solutionFormula: "=STDEV.S(D2:D7)",
      acceptedFunctionSets: [["STDEV.S"]]
    },
    {
      id: "stdev-p-salary-01",
      title: "Calculate Population Salary Spread",
      functionCategory: "STDEV.P",
      difficulty: "Intermediate",
      prompt: "Treat the six salaries as the complete population and calculate population standard deviation.",
      targetCell: "H4",
      expectedValue: 8286.53526310404,
      hints: ["Use D2:D7.", "The population version uses STDEV.P and divides variance by n."],
      solutionFormula: "=STDEV.P(D2:D7)",
      acceptedFunctionSets: [["STDEV.P"]]
    },
    {
      id: "var-s-salary-01",
      title: "Calculate Sample Salary Variance",
      functionCategory: "VAR.S",
      difficulty: "Intermediate",
      prompt: "Calculate sample variance for the six salaries.",
      targetCell: "H4",
      expectedValue: 82400000,
      hints: ["The salary observations are D2:D7.", "VAR.S returns variance, not standard deviation."],
      solutionFormula: "=VAR.S(D2:D7)",
      acceptedFunctionSets: [["VAR.S"]]
    },
    {
      id: "rank-lucas-salary-01",
      title: "Rank Lucas by Salary",
      functionCategory: "RANK.EQ",
      difficulty: "Intermediate",
      prompt: "Rank Lucas's salary among all six salaries from highest to lowest.",
      targetCell: "H4",
      expectedValue: 3,
      hints: ["Lucas's salary is D7.", "Use D2:D7 as the reference and 0 for descending order."],
      solutionFormula: "=RANK.EQ(D7,D2:D7,0)",
      acceptedFunctionSets: [["RANK.EQ"]]
    },
    {
      id: "percentile-salary-75-01",
      title: "Find the 75th Salary Percentile",
      functionCategory: "PERCENTILE.INC",
      difficulty: "Advanced",
      prompt: "Calculate the inclusive 75th percentile of salary.",
      targetCell: "H4",
      expectedValue: 79750,
      hints: ["Use D2:D7.", "The 75th percentile uses k = 0.75."],
      solutionFormula: "=PERCENTILE.INC(D2:D7,0.75)",
      acceptedFunctionSets: [["PERCENTILE.INC"]]
    },
    {
      id: "quartile-salary-01",
      title: "Find the First Salary Quartile",
      functionCategory: "QUARTILE.INC",
      difficulty: "Intermediate",
      prompt: "Calculate the first inclusive quartile of salary.",
      targetCell: "H4",
      expectedValue: 69000,
      hints: ["Use D2:D7.", "The first quartile uses quart = 1."],
      solutionFormula: "=QUARTILE.INC(D2:D7,1)",
      acceptedFunctionSets: [["QUARTILE.INC"]]
    },
    {
      id: "correl-salary-years-01",
      title: "Correlate Salary and Experience",
      functionCategory: "CORREL",
      difficulty: "Advanced",
      prompt: "Calculate the Pearson correlation between Salary and Years.",
      targetCell: "H4",
      expectedValue: 0.831467676330196,
      hints: ["Salary is D2:D7 and Years is E2:E7.", "CORREL requires two aligned numeric arrays."],
      solutionFormula: "=CORREL(D2:D7,E2:E7)",
      acceptedFunctionSets: [["CORREL"]]
    },
    {
      id: "covariance-s-salary-years-01",
      title: "Calculate Sample Covariance",
      functionCategory: "COVARIANCE.S",
      difficulty: "Advanced",
      prompt: "Calculate sample covariance between Salary and Years.",
      targetCell: "H4",
      expectedValue: 13000,
      hints: ["Use D2:D7 and E2:E7 as aligned arrays.", "COVARIANCE.S uses an n − 1 denominator."],
      solutionFormula: "=COVARIANCE.S(D2:D7,E2:E7)",
      acceptedFunctionSets: [["COVARIANCE.S"]]
    },
    {
      id: "pv-savings-01",
      title: "Value a Monthly Savings Stream Today",
      functionCategory: "PV",
      difficulty: "Intermediate",
      prompt: "Find the present value of receiving $200 per month for 10 years at 6% annual interest, compounded monthly. Enter the payment as -200 so the present value is positive.",
      targetCell: "H4",
      expectedValue: 18014.6906654335,
      hints: ["Use 0.06/12 for the monthly rate.", "Ten years of monthly payments gives 120 periods.", "Use -200 as the payment to follow Excel's cash-flow sign convention."],
      solutionFormula: "=PV(0.06/12,120,-200)",
      acceptedFunctionSets: [["PV"]]
    },
    {
      id: "fv-savings-01",
      title: "Project a Savings Balance",
      functionCategory: "FV",
      difficulty: "Intermediate",
      prompt: "Find the future value after depositing $200 per month for 10 years at 6% annual interest, compounded monthly. Enter deposits as -200.",
      targetCell: "H4",
      expectedValue: 32775.8693612916,
      hints: ["Use a monthly rate of 0.06/12.", "Use 120 monthly periods.", "Deposits are cash paid out, so use -200."],
      solutionFormula: "=FV(0.06/12,120,-200)",
      acceptedFunctionSets: [["FV"]]
    },
    {
      id: "pmt-loan-01",
      title: "Calculate a Loan Payment",
      functionCategory: "PMT",
      difficulty: "Intermediate",
      prompt: "Calculate the monthly payment on a $20,000 loan repaid over 60 months at 5% annual interest.",
      targetCell: "H4",
      expectedValue: -377.42467288022,
      hints: ["Use 0.05/12 for the monthly rate.", "There are 60 payments.", "The loan received today is a positive present value, so PMT returns a negative repayment."],
      solutionFormula: "=PMT(0.05/12,60,20000)",
      acceptedFunctionSets: [["PMT"]]
    },
    {
      id: "npv-future-cashflows-01",
      title: "Discount Future Cash Flows",
      functionCategory: "NPV",
      difficulty: "Intermediate",
      prompt: "Discount future cash flows of 3000, 4200, and 6800 at 10%. Remember that NPV treats the first supplied value as one period from today.",
      targetCell: "H4",
      expectedValue: 11307.2877535688,
      hints: ["Use 0.10 as the discount rate.", "Supply 3000, 4200, and 6800 as the future cash flows."],
      solutionFormula: "=NPV(0.1,3000,4200,6800)",
      acceptedFunctionSets: [["NPV"]]
    },
    {
      id: "npv-project-net-01",
      title: "Include the Initial Investment",
      functionCategory: "NPV",
      difficulty: "Advanced",
      prompt: "The project costs 10000 today and pays 3000, 4200, and 6800 over the next three periods. Calculate the project's net value at 10%, adding the time-0 investment separately from NPV.",
      targetCell: "H7",
      expectedValue: 1307.2877535688,
      hints: ["H2 is the time-0 investment and H3:H5 are future cash flows.", "NPV discounts H3:H5; then add H2 separately."],
      solutionFormula: "=NPV(0.1,H3:H5)+H2",
      acceptedFunctionSets: [["NPV"]],
      setup: [
        { cell: "H2", value: "-10000" },
        { cell: "H3", value: "3000" },
        { cell: "H4", value: "4200" },
        { cell: "H5", value: "6800" }
      ]
    },
    {
      id: "irr-project-01",
      title: "Find a Project's Periodic IRR",
      functionCategory: "IRR",
      difficulty: "Advanced",
      prompt: "Find the internal rate of return for the project cash flows in H2:H5.",
      targetCell: "H7",
      expectedValue: 0.163405600688989,
      hints: ["The range must contain both a negative and a positive cash flow.", "IRR assumes equally spaced periods."],
      solutionFormula: "=IRR(H2:H5)",
      acceptedFunctionSets: [["IRR"]],
      setup: [
        { cell: "H2", value: "-10000" },
        { cell: "H3", value: "3000" },
        { cell: "H4", value: "4200" },
        { cell: "H5", value: "6800" }
      ]
    },
    {
      id: "xnpv-irregular-01",
      title: "Discount Irregular Cash Flows",
      functionCategory: "XNPV",
      difficulty: "Advanced",
      prompt: "Calculate XNPV at 10% for the dated cash flows in H2:H5 and I2:I5.",
      targetCell: "H7",
      expectedValue: 2227.43187269064,
      hints: ["Values are in H2:H5 and their actual dates are in I2:I5.", "XNPV includes the initial dated cash flow rather than shifting every value one period forward."],
      solutionFormula: "=XNPV(0.1,H2:H5,I2:I5)",
      acceptedFunctionSets: [["XNPV"]],
      setup: [
        { cell: "H2", value: "-10000" },
        { cell: "H3", value: "3000" },
        { cell: "H4", value: "4200" },
        { cell: "H5", value: "6800" },
        { cell: "I2", value: "=DATE(2026,1,1)" },
        { cell: "I3", value: "=DATE(2026,7,1)" },
        { cell: "I4", value: "=DATE(2027,3,15)" },
        { cell: "I5", value: "=DATE(2028,1,1)" }
      ]
    },
    {
      id: "xirr-irregular-01",
      title: "Find an Annualized Irregular Return",
      functionCategory: "XIRR",
      difficulty: "Advanced",
      prompt: "Find the annualized XIRR for the dated cash flows in H2:H5 and I2:I5.",
      targetCell: "H7",
      expectedValue: 0.273144698866988,
      hints: ["Use the cash-flow range H2:H5 and aligned dates I2:I5.", "XIRR uses the actual day gaps rather than equally spaced periods."],
      solutionFormula: "=XIRR(H2:H5,I2:I5)",
      acceptedFunctionSets: [["XIRR"]],
      setup: [
        { cell: "H2", value: "-10000" },
        { cell: "H3", value: "3000" },
        { cell: "H4", value: "4200" },
        { cell: "H5", value: "6800" },
        { cell: "I2", value: "=DATE(2026,1,1)" },
        { cell: "I3", value: "=DATE(2026,7,1)" },
        { cell: "I4", value: "=DATE(2027,3,15)" },
        { cell: "I5", value: "=DATE(2028,1,1)" }
      ]
    },
    {
      id: "ifs-salary-band-01",
      title: "Classify a Salary with IFS",
      functionCategory: "IFS",
      difficulty: "Intermediate",
      prompt: "Classify Maya's salary as High at 80000 or above, Medium at 70000 or above, and Low otherwise.",
      targetCell: "H4",
      expectedValue: "Medium",
      hints: ["Test the highest threshold first.", "Use TRUE as the final catch-all condition."],
      solutionFormula: "=IFS(D2>=80000,\"High\",D2>=70000,\"Medium\",TRUE,\"Low\")",
      acceptedFunctionSets: [["IFS"]]
    },
    {
      id: "switch-department-01",
      title: "Map a Department with SWITCH",
      functionCategory: "SWITCH",
      difficulty: "Intermediate",
      prompt: "Return Budget when Maya's department is Finance, Technology when it is IT, and Other for anything else.",
      targetCell: "H4",
      expectedValue: "Budget",
      hints: ["Maya's department is in C2.", "SWITCH compares one expression against listed values."],
      solutionFormula: "=SWITCH(C2,\"Finance\",\"Budget\",\"IT\",\"Technology\",\"Other\")",
      acceptedFunctionSets: [["SWITCH"]]
    },
    {
      id: "choose-tier-01",
      title: "Choose a Tier by Position",
      functionCategory: "CHOOSE",
      difficulty: "Beginner",
      prompt: "Use CHOOSE to return the third item from Bronze, Silver, and Gold.",
      targetCell: "H4",
      expectedValue: "Gold",
      hints: ["CHOOSE uses a 1-based index.", "The third listed value is Gold."],
      solutionFormula: "=CHOOSE(3,\"Bronze\",\"Silver\",\"Gold\")",
      acceptedFunctionSets: [["CHOOSE"]]
    },
    {
      id: "xmatch-noah-01",
      title: "Find Noah's Position with XMATCH",
      functionCategory: "XMATCH",
      difficulty: "Intermediate",
      prompt: "Find Noah's relative position within B2:B7 using XMATCH.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["XMATCH uses exact matching by default.", "The returned number is a position within B2:B7."],
      solutionFormula: "=XMATCH(\"Noah\",B2:B7)",
      acceptedFunctionSets: [["XMATCH"]]
    },
    {
      id: "xmatch-wildcard-01",
      title: "Use an XMATCH Wildcard",
      functionCategory: "XMATCH",
      difficulty: "Advanced",
      prompt: "Use wildcard XMATCH to find the position of the employee whose name starts with Lu.",
      targetCell: "H4",
      expectedValue: 6,
      hints: ["Use Lu* as the lookup pattern.", "XMATCH match_mode 2 enables wildcards."],
      solutionFormula: "=XMATCH(\"Lu*\",B2:B7,2)",
      acceptedFunctionSets: [["XMATCH"]]
    },
    {
      id: "networkdays-holiday-01",
      title: "Count Workdays Around a Holiday",
      functionCategory: "NETWORKDAYS",
      difficulty: "Intermediate",
      prompt: "Count workdays from Monday August 17, 2026 through Friday August 21, 2026, excluding the holiday stored in I2.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["NETWORKDAYS includes both endpoints.", "I2 contains Wednesday August 19 as a holiday."],
      solutionFormula: "=NETWORKDAYS(DATE(2026,8,17),DATE(2026,8,21),I2)",
      acceptedFunctionSets: [["NETWORKDAYS"]],
      setup: [{ cell: "I2", value: "=DATE(2026,8,19)" }]
    },
    {
      id: "workday-holiday-01",
      title: "Move Five Workdays Forward",
      functionCategory: "WORKDAY",
      difficulty: "Intermediate",
      prompt: "Starting Monday August 17, 2026, move forward five workdays while excluding the holiday in I2.",
      targetCell: "H4",
      expectedValue: 46259,
      hints: ["The start date itself is not counted as day 1.", "I2 removes Wednesday August 19 from the workday count."],
      solutionFormula: "=WORKDAY(DATE(2026,8,17),5,I2)",
      acceptedFunctionSets: [["WORKDAY"]],
      setup: [{ cell: "I2", value: "=DATE(2026,8,19)" }]
    },
    {
      id: "let-bonus-01",
      title: "Name an Intermediate Value with LET",
      functionCategory: "LET",
      difficulty: "Advanced",
      prompt: "Use LET to name a 5% bonus rate and calculate Maya's bonus from D2.",
      targetCell: "H4",
      expectedValue: 3600,
      hints: ["Give the local name a value of 0.05.", "Use that name in the final D2 multiplication."],
      solutionFormula: "=LET(bonusRate,0.05,D2*bonusRate)",
      acceptedFunctionSets: [["LET"]]
    },
    {
      id: "sequence-vertical-01",
      title: "Create a Vertical Sequence",
      functionCategory: "SEQUENCE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Create a vertical sequence from 1 through 5.",
      targetCell: "H15",
      expectedShape: [5, 1],
      expectedValues: [[1], [2], [3], [4], [5]],
      hints: ["SEQUENCE needs only the number of rows for a vertical result."],
      solutionFormula: "=SEQUENCE(5)",
      acceptedFunctionSets: [["SEQUENCE"]]
    },
    {
      id: "sequence-rectangle-01",
      title: "Build a Sequence Rectangle",
      functionCategory: "SEQUENCE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Create a 2 × 3 sequence beginning at 10 and increasing by 5.",
      targetCell: "H15",
      expectedShape: [2, 3],
      expectedValues: [[10, 15, 20], [25, 30, 35]],
      hints: ["Use rows, columns, start, then step."],
      solutionFormula: "=SEQUENCE(2,3,10,5)",
      acceptedFunctionSets: [["SEQUENCE"]]
    },
    {
      id: "filter-finance-01",
      title: "Filter Finance Employees",
      functionCategory: "FILTER",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Return only Finance employees from A2:E7.",
      targetCell: "H15",
      expectedShape: [3, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Use A2:E7 as the returned array.", "Compare C2:C7 with \"Finance\"."],
      solutionFormula: "=FILTER(A2:E7,C2:C7=\"Finance\")",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "filter-salary-01",
      title: "Filter Higher Salaries",
      functionCategory: "FILTER",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Return employees earning more than 70000.",
      targetCell: "H15",
      expectedShape: [4, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1002, "Liam", "IT", 81000, 6],
        [1005, "Emma", "IT", 89000, 8],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Compare D2:D7 with 70000."],
      solutionFormula: "=FILTER(A2:E7,D2:D7>70000)",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "filter-two-conditions-01",
      title: "Combine Filter Conditions",
      functionCategory: "FILTER",
      difficulty: "Advanced",
      validationType: "arrayFormula",
      prompt: "Return Finance employees earning more than 70000.",
      targetCell: "H15",
      expectedShape: [2, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Build one comparison for department and one for salary.", "Multiply the two boolean arrays to require both conditions."],
      solutionFormula: "=FILTER(A2:E7,(C2:C7=\"Finance\")*(D2:D7>70000))",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "sort-salary-descending-01",
      title: "Sort Salaries Descending",
      functionCategory: "SORT",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Sort the employee table by its fourth column, Salary, from highest to lowest.",
      targetCell: "H15",
      expectedShape: [6, 5],
      expectedValues: [
        [1005, "Emma", "IT", 89000, 8],
        [1002, "Liam", "IT", 81000, 6],
        [1006, "Lucas", "Finance", 76000, 5],
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1004, "Noah", "HR", 64000, 5]
      ],
      hints: ["Salary is column 4 within A2:E7.", "Use -1 for descending order."],
      solutionFormula: "=SORT(A2:E7,4,-1)",
      acceptedFunctionSets: [["SORT"]]
    },
    {
      id: "sortby-salary-descending-01",
      title: "Sort by an Aligned Salary Range",
      functionCategory: "SORTBY",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Sort A2:E7 using D2:D7 from highest salary to lowest.",
      targetCell: "H15",
      expectedShape: [6, 5],
      expectedValues: [
        [1005, "Emma", "IT", 89000, 8],
        [1002, "Liam", "IT", 81000, 6],
        [1006, "Lucas", "Finance", 76000, 5],
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1004, "Noah", "HR", 64000, 5]
      ],
      hints: ["The returned array is A2:E7.", "Use D2:D7 as the separate sort key and -1 as its order."],
      solutionFormula: "=SORTBY(A2:E7,D2:D7,-1)",
      acceptedFunctionSets: [["SORTBY"]]
    },
    {
      id: "unique-departments-01",
      title: "List Unique Departments",
      functionCategory: "UNIQUE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Return each department from C2:C7 once, preserving first-occurrence order.",
      targetCell: "H15",
      expectedShape: [3, 1],
      expectedValues: [["Finance"], ["IT"], ["HR"]],
      hints: ["UNIQUE needs only the department range for this result."],
      solutionFormula: "=UNIQUE(C2:C7)",
      acceptedFunctionSets: [["UNIQUE"]]
    },
    {
      id: "format-percentage-01",
      title: "Format a Percentage",
      functionCategory: "Percentage Format",
      difficulty: "Beginner",
      validationType: "format",
      prompt: "Apply Percentage formatting with two decimal places to the value in H4.",
      targetCell: "H4",
      expectedValue: 0.075,
      expectedNumberFormat: "Percentage",
      expectedDecimals: 2,
      hints: ["Do not change the underlying 0.075 value.", "Use the % toolbar button or format dropdown."],
      solutionFormat: "Percentage with 2 decimal places",
      acceptedFunctionSets: [],
      setup: [{ cell: "H4", value: "0.075" }]
    },
    {
      id: "format-currency-01",
      title: "Format a Salary as Currency",
      functionCategory: "Currency Format",
      difficulty: "Beginner",
      validationType: "format",
      prompt: "Apply Currency formatting with two decimal places to the salary in H4.",
      targetCell: "H4",
      expectedValue: 72000,
      expectedNumberFormat: "Currency",
      expectedDecimals: 2,
      hints: ["Keep the underlying value at 72000.", "Use the $ toolbar button or format dropdown."],
      solutionFormat: "Currency with 2 decimal places",
      acceptedFunctionSets: [],
      setup: [{ cell: "H4", value: "72000" }]
    }
    ,
    {
      id: "min-salary-02",
      title: "Find the Lowest Salary",
      functionCategory: "MIN",
      difficulty: "Beginner",
      prompt: "Return the lowest salary in the employee table.",
      targetCell: "H4",
      expectedValue: 64000,
      hints: ["Salaries are in D2:D7.", "MIN returns the smallest numeric value in a range."],
      solutionFormula: "=MIN(D2:D7)",
      acceptedFunctionSets: [["MIN"]]
    },
    {
      id: "max-salary-02",
      title: "Find the Highest Salary",
      functionCategory: "MAX",
      difficulty: "Beginner",
      prompt: "Return the highest salary in the employee table.",
      targetCell: "H4",
      expectedValue: 89000,
      hints: ["Salaries are in D2:D7.", "MAX returns the largest numeric value in a range."],
      solutionFormula: "=MAX(D2:D7)",
      acceptedFunctionSets: [["MAX"]]
    },
    {
      id: "count-salaries-02",
      title: "Count Numeric Salaries",
      functionCategory: "COUNT",
      difficulty: "Beginner",
      prompt: "Count how many numeric salary values appear in D2:D7.",
      targetCell: "H4",
      expectedValue: 6,
      hints: ["Use the salary range D2:D7.", "COUNT ignores text and counts numeric cells."],
      solutionFormula: "=COUNT(D2:D7)",
      acceptedFunctionSets: [["COUNT"]]
    },
    {
      id: "or-department-02",
      title: "Check Either Department",
      functionCategory: "OR",
      difficulty: "Beginner",
      prompt: "Return TRUE if Maya's department is Finance or IT.",
      targetCell: "H4",
      expectedValue: true,
      hints: ["Maya's department is in C2.", "OR returns TRUE when at least one condition is TRUE."],
      solutionFormula: "=OR(C2=\"Finance\",C2=\"IT\")",
      acceptedFunctionSets: [["OR"]]
    },
    {
      id: "not-hr-02",
      title: "Check That Maya Is Not in HR",
      functionCategory: "NOT",
      difficulty: "Beginner",
      prompt: "Return TRUE if Maya's department is not HR.",
      targetCell: "H4",
      expectedValue: true,
      hints: ["Maya's department is in C2.", "NOT reverses the TRUE/FALSE result of a comparison."],
      solutionFormula: "=NOT(C2=\"HR\")",
      acceptedFunctionSets: [["NOT"]]
    },
    {
      id: "averageifs-finance-years-02",
      title: "Average Experienced Finance Salaries",
      functionCategory: "AVERAGEIFS",
      difficulty: "Intermediate",
      prompt: "Find the average salary of Finance employees with at least 4 years of experience.",
      targetCell: "H4",
      expectedValue: 74000,
      hints: ["Average D2:D7.", "Test C2:C7 for Finance and E2:E7 for >=4."],
      solutionFormula: "=AVERAGEIFS(D2:D7,C2:C7,\"Finance\",E2:E7,\">=4\")",
      acceptedFunctionSets: [["AVERAGEIFS"]]
    },
    {
      id: "hlookup-product-price-02",
      title: "Look Up a Price Horizontally",
      functionCategory: "HLOOKUP",
      difficulty: "Intermediate",
      prompt: "Use HLOOKUP to return the price of product A103 from the small horizontal table in H2:L3.",
      targetCell: "H5",
      expectedValue: 15,
      hints: ["Search across the first row H2:L2.", "Price is the second row of the selected table; use an exact match."],
      solutionFormula: "=HLOOKUP(\"A103\",H2:L3,2,FALSE)",
      acceptedFunctionSets: [["HLOOKUP"]],
      setup: [
        { cell: "H2", value: "Product" },
        { cell: "I2", value: "A101" },
        { cell: "J2", value: "A102" },
        { cell: "K2", value: "A103" },
        { cell: "L2", value: "A104" },
        { cell: "H3", value: "Price" },
        { cell: "I3", value: "12" },
        { cell: "J3", value: "18" },
        { cell: "K3", value: "15" },
        { cell: "L3", value: "22" }
      ]
    },
    {
      id: "lower-finance-02",
      title: "Convert Finance to Lowercase",
      functionCategory: "LOWER",
      difficulty: "Beginner",
      prompt: "Convert Maya's department in C2 to lowercase.",
      targetCell: "H4",
      expectedValue: "finance",
      hints: ["Maya's department is in C2.", "LOWER converts letters to lowercase."],
      solutionFormula: "=LOWER(C2)",
      acceptedFunctionSets: [["LOWER"]]
    },
    {
      id: "proper-name-02",
      title: "Capitalize a Name Properly",
      functionCategory: "PROPER",
      difficulty: "Beginner",
      prompt: "Convert the supplied text maya chen to proper capitalization.",
      targetCell: "H4",
      expectedValue: "Maya Chen",
      hints: ["The unformatted name is in H3.", "PROPER capitalizes the beginning of each word."],
      solutionFormula: "=PROPER(H3)",
      acceptedFunctionSets: [["PROPER"]],
      setup: [{ cell: "H3", value: "maya chen" }]
    },
    {
      id: "find-vancouver-02",
      title: "Find a Case-Sensitive Character",
      functionCategory: "FIND",
      difficulty: "Beginner",
      prompt: "Find the position of lowercase c in Vancouver using FIND.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["The text is in H3.", "FIND is case-sensitive and returns a 1-based position."],
      solutionFormula: "=FIND(\"c\",H3)",
      acceptedFunctionSets: [["FIND"]],
      setup: [{ cell: "H3", value: "Vancouver" }]
    },
    {
      id: "replace-report-year-02",
      title: "Replace the Report Year",
      functionCategory: "REPLACE",
      difficulty: "Beginner",
      prompt: "Change 2025-report to 2026-report by replacing the first four characters.",
      targetCell: "H4",
      expectedValue: "2026-report",
      hints: ["The source text is in H3.", "Start at character 1, replace 4 characters, and insert 2026."],
      solutionFormula: "=REPLACE(H3,1,4,\"2026\")",
      acceptedFunctionSets: [["REPLACE"]],
      setup: [{ cell: "H3", value: "2025-report" }]
    },
    {
      id: "today-current-date-02",
      title: "Return Today's Date",
      functionCategory: "TODAY",
      difficulty: "Beginner",
      validationType: "todayFormula",
      prompt: "Use TODAY to return the current calendar date.",
      targetCell: "H4",
      expectedNumberFormat: "Date",
      hints: ["TODAY takes no arguments.", "The result is a numeric date serial displayed with Date formatting."],
      solutionFormula: "=TODAY()",
      acceptedFunctionSets: [["TODAY"]]
    },
    {
      id: "var-p-salary-02",
      title: "Calculate Population Salary Variance",
      functionCategory: "VAR.P",
      difficulty: "Intermediate",
      prompt: "Treat all six salaries as the complete population and calculate their population variance.",
      targetCell: "H4",
      expectedValue: 68666666.6666667,
      hints: ["Use D2:D7.", "VAR.P uses the population denominator n."],
      solutionFormula: "=VAR.P(D2:D7)",
      acceptedFunctionSets: [["VAR.P"]]
    },
    {
      id: "mixed-round-average-01",
      title: "Round the Average Salary",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["AVERAGE", "ROUND"],
      difficulty: "Intermediate",
      prompt: "Calculate the average salary and round the result to zero decimal places.",
      targetCell: "H4",
      expectedValue: 75000,
      hints: ["AVERAGE D2:D7 first.", "Wrap the average inside ROUND with 0 digits."],
      solutionFormula: "=ROUND(AVERAGE(D2:D7),0)",
      acceptedFunctionSets: [["AVERAGE", "ROUND"]]
    },
    {
      id: "mixed-if-and-eligibility-01",
      title: "Combine IF and AND for Eligibility",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["IF", "AND"],
      difficulty: "Intermediate",
      prompt: "Return Eligible if Maya is in Finance and earns more than 70000; otherwise return No.",
      targetCell: "H4",
      expectedValue: "Eligible",
      hints: ["Use AND for the department and salary tests.", "Use that logical result as the IF condition."],
      solutionFormula: "=IF(AND(C2=\"Finance\",D2>70000),\"Eligible\",\"No\")",
      acceptedFunctionSets: [["IF", "AND"]]
    },
    {
      id: "mixed-safe-xlookup-01",
      title: "Build a Safe Lookup",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["XLOOKUP", "IFNA"],
      difficulty: "Intermediate",
      prompt: "Look up Olivia's salary by name and return Not found when the name does not exist.",
      targetCell: "H4",
      expectedValue: "Not found",
      hints: ["Search B2:B7 and return D2:D7.", "Wrap the lookup with IFNA so #N/A becomes readable text."],
      solutionFormula: "=IFNA(XLOOKUP(\"Olivia\",B2:B7,D2:D7),\"Not found\")",
      acceptedFunctionSets: [["XLOOKUP", "IFNA"]]
    },
    {
      id: "mixed-positional-lookup-01",
      title: "Combine INDEX with a Position Lookup",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["INDEX", "MATCH or XMATCH"],
      difficulty: "Advanced",
      prompt: "Return Lucas's salary using INDEX with either MATCH or XMATCH to find his position.",
      targetCell: "H4",
      expectedValue: 76000,
      hints: ["Find Lucas in B2:B7.", "Use the returned relative position inside INDEX over D2:D7."],
      solutionFormula: "=INDEX(D2:D7,XMATCH(\"Lucas\",B2:B7))",
      acceptedFunctionSets: [["INDEX", "MATCH"], ["INDEX", "XMATCH"]]
    },
    {
      id: "mixed-percentile-count-01",
      title: "Count Salaries Above the 75th Percentile",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["PERCENTILE.INC", "COUNTIF"],
      difficulty: "Advanced",
      prompt: "Calculate the 75th salary percentile and count how many salaries are strictly above it.",
      targetCell: "H4",
      expectedValue: 2,
      hints: ["The 75th percentile is PERCENTILE.INC(D2:D7,0.75).", "Build a > criterion for COUNTIF by concatenating the percentile value."],
      solutionFormula: "=COUNTIF(D2:D7,\">\"&PERCENTILE.INC(D2:D7,0.75))",
      acceptedFunctionSets: [["COUNTIF", "PERCENTILE.INC"]]
    },
    {
      id: "mixed-correlation-classify-01",
      title: "Classify a Correlation",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["CORREL", "IF"],
      difficulty: "Advanced",
      prompt: "Return Strong if the salary-years correlation is greater than 0.8; otherwise return Moderate.",
      targetCell: "H4",
      expectedValue: "Strong",
      hints: ["CORREL compares D2:D7 with E2:E7.", "Use the correlation result directly inside an IF comparison."],
      solutionFormula: "=IF(CORREL(D2:D7,E2:E7)>0.8,\"Strong\",\"Moderate\")",
      acceptedFunctionSets: [["CORREL", "IF"]]
    },
    {
      id: "mixed-payment-round-01",
      title: "Show a Positive Rounded Loan Payment",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["PMT", "ABS", "ROUND"],
      difficulty: "Advanced",
      prompt: "Calculate the monthly payment on a $20,000 loan for 60 months at 5% annual interest, make the payment positive, and round it to cents.",
      targetCell: "H4",
      expectedValue: 377.42,
      hints: ["Use PMT(0.05/12,60,20000).", "ABS changes the repayment sign and ROUND(...,2) gives cents."],
      solutionFormula: "=ROUND(ABS(PMT(0.05/12,60,20000)),2)",
      acceptedFunctionSets: [["PMT", "ABS", "ROUND"]]
    },
    {
      id: "mixed-filter-sort-finance-01",
      title: "Filter Finance, Then Sort by Salary",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["FILTER", "SORT"],
      difficulty: "Advanced",
      validationType: "arrayFormula",
      prompt: "Return only Finance employees and sort those rows by Salary from highest to lowest.",
      targetCell: "H15",
      expectedShape: [3, 5],
      expectedValues: [
        [1006, "Lucas", "Finance", 76000, 5],
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3]
      ],
      hints: ["FILTER A2:E7 using C2:C7=\"Finance\".", "Feed that array into SORT and sort by relative column 4 descending."],
      solutionFormula: "=SORT(FILTER(A2:E7,C2:C7=\"Finance\"),4,-1)",
      acceptedFunctionSets: [["FILTER", "SORT"]]
    },
    {
      id: "mixed-let-filter-salary-01",
      title: "Name a Threshold and Filter with LET",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["LET", "FILTER"],
      difficulty: "Advanced",
      validationType: "arrayFormula",
      prompt: "Use LET to name a minimum salary of 70000, then return employees earning more than that threshold.",
      targetCell: "H15",
      expectedShape: [4, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1002, "Liam", "IT", 81000, 6],
        [1005, "Emma", "IT", 89000, 8],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Define a local name such as minSalary with value 70000.", "Use that name inside FILTER's salary comparison."],
      solutionFormula: "=LET(minSalary,70000,FILTER(A2:E7,D2:D7>minSalary))",
      acceptedFunctionSets: [["LET", "FILTER"]]
    },
    {
      id: "mixed-left-search-first-name-01",
      title: "Extract a First Name with LEFT and SEARCH",
      functionCategory: "Mixed Skills",
      curriculumTrack: "Mixed",
      skills: ["LEFT", "SEARCH"],
      difficulty: "Intermediate",
      prompt: "Extract Maya from the supplied Maya Chen text by finding the space and taking everything to its left.",
      targetCell: "H4",
      expectedValue: "Maya",
      hints: ["SEARCH can find the position of the space.", "Subtract 1 from that position and use it as LEFT's character count."],
      solutionFormula: "=LEFT(H3,SEARCH(\" \",H3)-1)",
      acceptedFunctionSets: [["LEFT", "SEARCH"]],
      setup: [{ cell: "H3", value: "Maya Chen" }]
    }

  ];

  const curriculum = Object.freeze({
    levels: Object.freeze([
      Object.freeze({ id: "Beginner", label: "Beginner", description: "Build confidence with one main spreadsheet idea at a time." }),
      Object.freeze({ id: "Intermediate", label: "Intermediate", description: "Apply functions with multiple arguments, criteria, lookups, and structured data." }),
      Object.freeze({ id: "Advanced", label: "Advanced", description: "Compose functions, analyze data, and solve multi-step spreadsheet problems." })
    ]),
    specialTracks: Object.freeze([
      Object.freeze({ id: "Mixed", label: "Mixed", description: "Combine two or more skills in one formula or dynamic-array task." }),
      Object.freeze({ id: "All", label: "All", description: "Browse the complete curriculum." })
    ])
  });

  global.ExcelExercises = exercises;
  global.ExcelCurriculum = curriculum;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = exercises;
  }
})(typeof window === "undefined" ? globalThis : window);
