((global) => {
  "use strict";

  const exercises = [
    {
      id: "sum-salary-01",
      title: "Calculate Total Salary",
      functionCategory: "SUM",
      difficulty: "Beginner",
      prompt: "Calculate the total salary of all six employees.",
      targetCell: "H4",
      expectedValue: 450000,
      hints: ["The salaries are in D2:D7.", "SUM can add one continuous range."],
      solutionFormula: "=SUM(D2:D7)",
      acceptedFunctionSets: [["SUM"]]
    },
    {
      id: "average-salary-01",
      title: "Calculate Average Salary",
      functionCategory: "AVERAGE",
      difficulty: "Beginner",
      prompt: "Calculate the average salary of all six employees.",
      targetCell: "H4",
      expectedValue: 75000,
      hints: ["The salaries are in D2:D7.", "Use AVERAGE with the complete salary range."],
      solutionFormula: "=AVERAGE(D2:D7)",
      acceptedFunctionSets: [["AVERAGE"]]
    },
    {
      id: "if-maya-salary-01",
      title: "Classify Maya's Salary",
      functionCategory: "IF",
      difficulty: "Beginner",
      prompt: "Return \"High\" if Maya's salary is greater than 70000. Otherwise return \"Standard\".",
      targetCell: "H4",
      expectedValue: "High",
      hints: ["Maya's salary is in D2.", "Test D2>70000, then provide the two text results."],
      solutionFormula: "=IF(D2>70000,\"High\",\"Standard\")",
      acceptedFunctionSets: [["IF"]]
    },
    {
      id: "and-maya-01",
      title: "Check Maya's Salary and Experience",
      functionCategory: "AND",
      difficulty: "Beginner",
      prompt: "Return TRUE if Maya earns more than 70000 and has at least 4 years.",
      targetCell: "H4",
      expectedValue: true,
      hints: ["Maya's salary and years are in D2 and E2.", "AND requires both comparisons to be TRUE."],
      solutionFormula: "=AND(D2>70000,E2>=4)",
      acceptedFunctionSets: [["AND"]]
    },
    {
      id: "countif-finance-01",
      title: "Count Finance Employees",
      functionCategory: "COUNTIF",
      difficulty: "Beginner",
      prompt: "Count employees in Finance.",
      targetCell: "H4",
      expectedValue: 3,
      hints: ["Departments are in C2:C7.", "Use \"Finance\" as the COUNTIF criterion."],
      solutionFormula: "=COUNTIF(C2:C7,\"Finance\")",
      acceptedFunctionSets: [["COUNTIF"]]
    },
    {
      id: "sumif-finance-01",
      title: "Total Finance Salary",
      functionCategory: "SUMIF",
      difficulty: "Intermediate",
      prompt: "Find the total salary of Finance employees.",
      targetCell: "H4",
      expectedValue: 216000,
      hints: ["Test departments in C2:C7.", "Add the aligned salaries in D2:D7."],
      solutionFormula: "=SUMIF(C2:C7,\"Finance\",D2:D7)",
      acceptedFunctionSets: [["SUMIF"]]
    },
    {
      id: "averageif-finance-01",
      title: "Average Finance Salary",
      functionCategory: "AVERAGEIF",
      difficulty: "Intermediate",
      prompt: "Find the average salary of Finance employees.",
      targetCell: "H4",
      expectedValue: 72000,
      hints: ["Test C2:C7 for Finance.", "Average the aligned values in D2:D7."],
      solutionFormula: "=AVERAGEIF(C2:C7,\"Finance\",D2:D7)",
      acceptedFunctionSets: [["AVERAGEIF"]]
    },
    {
      id: "countifs-finance-salary-01",
      title: "Count Higher-Paid Finance Employees",
      functionCategory: "COUNTIFS",
      difficulty: "Intermediate",
      prompt: "Count Finance employees earning more than 70000.",
      targetCell: "H4",
      expectedValue: 2,
      hints: ["Use one criterion for C2:C7 and another for D2:D7.", "The salary criterion is \" >70000\" without the leading space."],
      solutionFormula: "=COUNTIFS(C2:C7,\"Finance\",D2:D7,\">70000\")",
      acceptedFunctionSets: [["COUNTIFS"]]
    },
    {
      id: "sumifs-finance-years-01",
      title: "Finance Salary with Experience",
      functionCategory: "SUMIFS",
      difficulty: "Intermediate",
      prompt: "Find total salary for Finance employees with at least 4 years.",
      targetCell: "H4",
      expectedValue: 148000,
      hints: ["D2:D7 is the sum range.", "Test C2:C7 for Finance and E2:E7 with the criterion >=4."],
      solutionFormula: "=SUMIFS(D2:D7,C2:C7,\"Finance\",E2:E7,\">=4\")",
      acceptedFunctionSets: [["SUMIFS"]]
    },
    {
      id: "vlookup-id-salary-01",
      title: "Look Up Salary by Employee ID",
      functionCategory: "VLOOKUP",
      difficulty: "Intermediate",
      prompt: "Use Employee ID 1004 to return the salary.",
      targetCell: "H4",
      expectedValue: 64000,
      hints: ["The lookup table is A2:E7.", "Salary is column 4 of that table; use an exact match."],
      solutionFormula: "=VLOOKUP(1004,A2:E7,4,FALSE)",
      acceptedFunctionSets: [["VLOOKUP"]]
    },
    {
      id: "xlookup-basic-01",
      title: "Find Lucas's Salary",
      functionCategory: "XLOOKUP",
      difficulty: "Beginner",
      prompt: "Use Lucas's name to return his salary.",
      targetCell: "H4",
      expectedValue: 76000,
      hints: ["The names are in B2:B7.", "The salaries are in D2:D7.", "XLOOKUP needs a lookup value, lookup array, and return array."],
      solutionFormula: "=XLOOKUP(\"Lucas\",B2:B7,D2:D7)",
      acceptedFunctionSets: [["XLOOKUP"]]
    },
    {
      id: "xlookup-left-01",
      title: "Find Lucas's Employee ID",
      functionCategory: "XLOOKUP",
      difficulty: "Intermediate",
      prompt: "Use Lucas's name to return his Employee ID from the left.",
      targetCell: "H4",
      expectedValue: 1006,
      hints: ["Search names in B2:B7.", "Employee IDs are in A2:A7, to the left of the names."],
      solutionFormula: "=XLOOKUP(\"Lucas\",B2:B7,A2:A7)",
      acceptedFunctionSets: [["XLOOKUP"]]
    },
    {
      id: "match-noah-01",
      title: "Find Noah's Position",
      functionCategory: "MATCH",
      difficulty: "Intermediate",
      prompt: "Find Noah's position within the employee-name list.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["The names are in B2:B7.", "Use match type 0 for an exact position."],
      solutionFormula: "=MATCH(\"Noah\",B2:B7,0)",
      acceptedFunctionSets: [["MATCH"]]
    },
    {
      id: "index-name-01",
      title: "Return a Name by Position",
      functionCategory: "INDEX",
      difficulty: "Intermediate",
      prompt: "Return the employee name at row position 4 and column position 2 within A2:E7.",
      targetCell: "H4",
      expectedValue: "Noah",
      hints: ["Use A2:E7 as the INDEX array.", "The requested relative row is 4 and column is 2."],
      solutionFormula: "=INDEX(A2:E7,4,2)",
      acceptedFunctionSets: [["INDEX"]]
    },
    {
      id: "index-match-lucas-01",
      title: "Find Lucas's Salary with INDEX and MATCH",
      functionCategory: "INDEX + MATCH",
      difficulty: "Advanced",
      prompt: "Find Lucas's salary using INDEX and MATCH.",
      targetCell: "H4",
      expectedValue: 76000,
      hints: ["MATCH can find Lucas's position in B2:B7.", "Use exact match type 0.", "Pass the MATCH position to INDEX over D2:D7."],
      solutionFormula: "=INDEX(D2:D7,MATCH(\"Lucas\",B2:B7,0))",
      acceptedFunctionSets: [["INDEX", "MATCH"]]
    },
    {
      id: "len-maya-name-01",
      title: "Count Maya's Name",
      functionCategory: "LEN",
      difficulty: "Beginner",
      prompt: "Count the characters in Maya's name.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["Maya's name is in B2.", "LEN counts every character in its text argument."],
      solutionFormula: "=LEN(B2)",
      acceptedFunctionSets: [["LEN"]]
    },
    {
      id: "left-lucas-name-01",
      title: "Take Lucas's First Letters",
      functionCategory: "LEFT",
      difficulty: "Beginner",
      prompt: "Return the first two letters of Lucas's name.",
      targetCell: "H4",
      expectedValue: "Lu",
      hints: ["Lucas's name is in B7.", "Ask LEFT for 2 characters."],
      solutionFormula: "=LEFT(B7,2)",
      acceptedFunctionSets: [["LEFT"]]
    },
    {
      id: "right-sofia-name-01",
      title: "Take Sofia's Last Letters",
      functionCategory: "RIGHT",
      difficulty: "Beginner",
      prompt: "Return the last two letters of Sofia's name.",
      targetCell: "H4",
      expectedValue: "ia",
      hints: ["Sofia's name is in B4.", "RIGHT takes characters from the end."],
      solutionFormula: "=RIGHT(B4,2)",
      acceptedFunctionSets: [["RIGHT"]]
    },
    {
      id: "mid-vancouver-01",
      title: "Extract from Vancouver",
      functionCategory: "MID",
      difficulty: "Beginner",
      prompt: "Return characters 4 through 6 from the supplied Vancouver text.",
      targetCell: "H4",
      expectedValue: "cou",
      hints: ["The practice text is in H3.", "Start at character 4 and request 3 characters."],
      solutionFormula: "=MID(H3,4,3)",
      acceptedFunctionSets: [["MID"]],
      setup: [{ cell: "H3", value: "Vancouver" }]
    },
    {
      id: "upper-finance-01",
      title: "Uppercase Finance",
      functionCategory: "UPPER",
      difficulty: "Beginner",
      prompt: "Convert the Finance department in C2 to uppercase.",
      targetCell: "H4",
      expectedValue: "FINANCE",
      hints: ["The department is in C2.", "UPPER changes every letter to uppercase."],
      solutionFormula: "=UPPER(C2)",
      acceptedFunctionSets: [["UPPER"]]
    },
    {
      id: "trim-name-spacing-01",
      title: "Clean Name Spacing",
      functionCategory: "TRIM",
      difficulty: "Beginner",
      prompt: "Clean the extra spaces from the supplied Maya Chen text.",
      targetCell: "H4",
      expectedValue: "Maya Chen",
      hints: ["The text with extra spaces is in H3.", "TRIM cleans outer and repeated interior spaces."],
      solutionFormula: "=TRIM(H3)",
      acceptedFunctionSets: [["TRIM"]],
      setup: [{ cell: "H3", value: "   Maya    Chen   " }]
    },
    {
      id: "concat-name-department-01",
      title: "Build an Employee Label",
      functionCategory: "CONCAT",
      difficulty: "Beginner",
      prompt: "Combine Maya and Finance as Maya - Finance.",
      targetCell: "H4",
      expectedValue: "Maya - Finance",
      hints: ["Maya is in B2 and Finance is in C2.", "Include \" - \" as the middle CONCAT piece."],
      solutionFormula: "=CONCAT(B2,\" - \",C2)",
      acceptedFunctionSets: [["CONCAT"]]
    },
    {
      id: "textjoin-first-names-01",
      title: "Join the First Three Names",
      functionCategory: "TEXTJOIN",
      difficulty: "Intermediate",
      prompt: "Join Maya, Liam, and Sofia with comma-space separators.",
      targetCell: "H4",
      expectedValue: "Maya, Liam, Sofia",
      hints: ["The three names are in B2:B4.", "Use \", \" as the delimiter.", "Set ignore_empty to TRUE."],
      solutionFormula: "=TEXTJOIN(\", \",TRUE,B2:B4)",
      acceptedFunctionSets: [["TEXTJOIN"]]
    },
    {
      id: "search-vancouver-01",
      title: "Find a Character Position",
      functionCategory: "SEARCH",
      difficulty: "Beginner",
      prompt: "Find the position of c inside the supplied Vancouver text.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["The practice text is in H3.", "SEARCH returns a one-based position and ignores case."],
      solutionFormula: "=SEARCH(\"c\",H3)",
      acceptedFunctionSets: [["SEARCH"]],
      setup: [{ cell: "H3", value: "Vancouver" }]
    },
    {
      id: "substitute-department-01",
      title: "Rename a Department",
      functionCategory: "SUBSTITUTE",
      difficulty: "Intermediate",
      prompt: "Change Finance Department to Finance Division.",
      targetCell: "H4",
      expectedValue: "Finance Division",
      hints: ["The source text is in H3.", "Replace Department with Division."],
      solutionFormula: "=SUBSTITUTE(H3,\"Department\",\"Division\")",
      acceptedFunctionSets: [["SUBSTITUTE"]],
      setup: [{ cell: "H3", value: "Finance Department" }]
    },
    {
      id: "date-build-2026-01",
      title: "Create a Calendar Date",
      functionCategory: "DATE",
      difficulty: "Beginner",
      prompt: "Create August 17, 2026 using DATE.",
      targetCell: "H4",
      expectedValue: 46251,
      expectedNumberFormat: "Date",
      hints: ["DATE accepts year, month, and day in that order.", "Use 2026, 8, and 17."],
      solutionFormula: "=DATE(2026,8,17)",
      acceptedFunctionSets: [["DATE"]]
    },
    {
      id: "year-from-date-2026-01",
      title: "Extract the Year",
      functionCategory: "YEAR",
      difficulty: "Beginner",
      prompt: "Return the year from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 2026,
      hints: ["H3 contains a date-formatted serial.", "YEAR returns an ordinary number."],
      solutionFormula: "=YEAR(H3)",
      acceptedFunctionSets: [["YEAR"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "month-from-date-2026-01",
      title: "Extract the Month",
      functionCategory: "MONTH",
      difficulty: "Beginner",
      prompt: "Return the month number from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 8,
      hints: ["H3 contains August 17, 2026.", "MONTH returns a number from 1 through 12."],
      solutionFormula: "=MONTH(H3)",
      acceptedFunctionSets: [["MONTH"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "day-from-date-2026-01",
      title: "Extract the Day",
      functionCategory: "DAY",
      difficulty: "Beginner",
      prompt: "Return the day of the month from the practice date in H3.",
      targetCell: "H4",
      expectedValue: 17,
      hints: ["H3 contains August 17, 2026.", "DAY returns the calendar day number."],
      solutionFormula: "=DAY(H3)",
      acceptedFunctionSets: [["DAY"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "days-between-august-2026-01",
      title: "Count Days Between Dates",
      functionCategory: "DAYS",
      difficulty: "Beginner",
      prompt: "Find the number of days from August 10 to August 17, 2026.",
      targetCell: "H4",
      expectedValue: 7,
      hints: ["H2 contains the start date and H3 contains the end date.", "DAYS takes the end date first."],
      solutionFormula: "=DAYS(H3,H2)",
      acceptedFunctionSets: [["DAYS"]],
      setup: [
        { cell: "H2", value: "=DATE(2026,8,10)" },
        { cell: "H3", value: "=DATE(2026,8,17)" }
      ]
    },
    {
      id: "edate-three-months-01",
      title: "Move Forward Three Months",
      functionCategory: "EDATE",
      difficulty: "Intermediate",
      prompt: "Move the practice date in H3 forward by three months.",
      targetCell: "H4",
      expectedValue: 46343,
      expectedNumberFormat: "Date",
      hints: ["H3 contains August 17, 2026.", "Use a positive month offset of 3."],
      solutionFormula: "=EDATE(H3,3)",
      acceptedFunctionSets: [["EDATE"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "eomonth-august-2026-01",
      title: "Find the End of August",
      functionCategory: "EOMONTH",
      difficulty: "Intermediate",
      prompt: "Return the final day of the practice date's current month.",
      targetCell: "H4",
      expectedValue: 46265,
      expectedNumberFormat: "Date",
      hints: ["H3 contains August 17, 2026.", "Use a month offset of 0 for the same month."],
      solutionFormula: "=EOMONTH(H3,0)",
      acceptedFunctionSets: [["EOMONTH"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "weekday-monday-2026-01",
      title: "Number a Monday",
      functionCategory: "WEEKDAY",
      difficulty: "Intermediate",
      prompt: "Using return type 2, determine the weekday number for the practice date.",
      targetCell: "H4",
      expectedValue: 1,
      hints: ["H3 contains Monday, August 17, 2026.", "Return type 2 makes Monday equal 1."],
      solutionFormula: "=WEEKDAY(H3,2)",
      acceptedFunctionSets: [["WEEKDAY"]],
      setup: [{ cell: "H3", value: "=DATE(2026,8,17)" }]
    },
    {
      id: "round-two-decimals-01",
      title: "Round to Two Decimals",
      functionCategory: "ROUND",
      difficulty: "Beginner",
      prompt: "Round 12.3456 to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.35,
      hints: ["ROUND changes the stored numeric result.", "Use 2 for num_digits."],
      solutionFormula: "=ROUND(12.3456,2)",
      acceptedFunctionSets: [["ROUND"]]
    },
    {
      id: "roundup-two-decimals-01",
      title: "Round Away from Zero",
      functionCategory: "ROUNDUP",
      difficulty: "Beginner",
      prompt: "Round 12.341 upward to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.35,
      hints: ["ROUNDUP always moves away from zero.", "Use 2 decimal places."],
      solutionFormula: "=ROUNDUP(12.341,2)",
      acceptedFunctionSets: [["ROUNDUP"]]
    },
    {
      id: "rounddown-two-decimals-01",
      title: "Round Toward Zero",
      functionCategory: "ROUNDDOWN",
      difficulty: "Beginner",
      prompt: "Round 12.349 downward to two decimal places.",
      targetCell: "H4",
      expectedValue: 12.34,
      hints: ["ROUNDDOWN moves toward zero.", "Use 2 decimal places."],
      solutionFormula: "=ROUNDDOWN(12.349,2)",
      acceptedFunctionSets: [["ROUNDDOWN"]]
    },
    {
      id: "int-negative-01",
      title: "Round a Negative Integer Down",
      functionCategory: "INT",
      difficulty: "Beginner",
      prompt: "Use INT on -8.9.",
      targetCell: "H4",
      expectedValue: -9,
      hints: ["INT rounds downward, not toward zero."],
      solutionFormula: "=INT(-8.9)",
      acceptedFunctionSets: [["INT"]]
    },
    {
      id: "abs-negative-01",
      title: "Find an Absolute Value",
      functionCategory: "ABS",
      difficulty: "Beginner",
      prompt: "Return the absolute value of -125.",
      targetCell: "H4",
      expectedValue: 125,
      hints: ["ABS returns distance from zero."],
      solutionFormula: "=ABS(-125)",
      acceptedFunctionSets: [["ABS"]]
    },
    {
      id: "mod-remainder-01",
      title: "Find a Remainder",
      functionCategory: "MOD",
      difficulty: "Beginner",
      prompt: "Find the remainder when 25 is divided by 7.",
      targetCell: "H4",
      expectedValue: 4,
      hints: ["MOD takes the number first and divisor second."],
      solutionFormula: "=MOD(25,7)",
      acceptedFunctionSets: [["MOD"]]
    },
    {
      id: "iferror-division-01",
      title: "Handle Division by Zero",
      functionCategory: "IFERROR",
      difficulty: "Intermediate",
      prompt: "Use IFERROR so division by zero returns Cannot divide.",
      targetCell: "H4",
      expectedValue: "Cannot divide",
      hints: ["Use 10/0 as the primary expression.", "Use \"Cannot divide\" as the fallback."],
      solutionFormula: "=IFERROR(10/0,\"Cannot divide\")",
      acceptedFunctionSets: [["IFERROR"]]
    },
    {
      id: "ifna-xlookup-01",
      title: "Handle a Missing Lookup",
      functionCategory: "IFNA",
      difficulty: "Intermediate",
      prompt: "Use XLOOKUP for Olivia and return Not found with IFNA.",
      targetCell: "H4",
      expectedValue: "Not found",
      hints: ["Search Olivia in B2:B7 and return from D2:D7.", "Wrap XLOOKUP with IFNA."],
      solutionFormula: "=IFNA(XLOOKUP(\"Olivia\",B2:B7,D2:D7),\"Not found\")",
      acceptedFunctionSets: [["IFNA", "XLOOKUP"]]
    },
    {
      id: "sequence-vertical-01",
      title: "Create a Vertical Sequence",
      functionCategory: "SEQUENCE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Create a vertical sequence from 1 through 5.",
      targetCell: "H15",
      expectedShape: [5, 1],
      expectedValues: [[1], [2], [3], [4], [5]],
      hints: ["SEQUENCE needs only the number of rows for a vertical result."],
      solutionFormula: "=SEQUENCE(5)",
      acceptedFunctionSets: [["SEQUENCE"]]
    },
    {
      id: "sequence-rectangle-01",
      title: "Build a Sequence Rectangle",
      functionCategory: "SEQUENCE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Create a 2 × 3 sequence beginning at 10 and increasing by 5.",
      targetCell: "H15",
      expectedShape: [2, 3],
      expectedValues: [[10, 15, 20], [25, 30, 35]],
      hints: ["Use rows, columns, start, then step."],
      solutionFormula: "=SEQUENCE(2,3,10,5)",
      acceptedFunctionSets: [["SEQUENCE"]]
    },
    {
      id: "filter-finance-01",
      title: "Filter Finance Employees",
      functionCategory: "FILTER",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Return only Finance employees from A2:E7.",
      targetCell: "H15",
      expectedShape: [3, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Use A2:E7 as the returned array.", "Compare C2:C7 with \"Finance\"."],
      solutionFormula: "=FILTER(A2:E7,C2:C7=\"Finance\")",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "filter-salary-01",
      title: "Filter Higher Salaries",
      functionCategory: "FILTER",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Return employees earning more than 70000.",
      targetCell: "H15",
      expectedShape: [4, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1002, "Liam", "IT", 81000, 6],
        [1005, "Emma", "IT", 89000, 8],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Compare D2:D7 with 70000."],
      solutionFormula: "=FILTER(A2:E7,D2:D7>70000)",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "filter-two-conditions-01",
      title: "Combine Filter Conditions",
      functionCategory: "FILTER",
      difficulty: "Advanced",
      validationType: "arrayFormula",
      prompt: "Return Finance employees earning more than 70000.",
      targetCell: "H15",
      expectedShape: [2, 5],
      expectedValues: [
        [1001, "Maya", "Finance", 72000, 4],
        [1006, "Lucas", "Finance", 76000, 5]
      ],
      hints: ["Build one comparison for department and one for salary.", "Multiply the two boolean arrays to require both conditions."],
      solutionFormula: "=FILTER(A2:E7,(C2:C7=\"Finance\")*(D2:D7>70000))",
      acceptedFunctionSets: [["FILTER"]]
    },
    {
      id: "sort-salary-descending-01",
      title: "Sort Salaries Descending",
      functionCategory: "SORT",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Sort the employee table by its fourth column, Salary, from highest to lowest.",
      targetCell: "H15",
      expectedShape: [6, 5],
      expectedValues: [
        [1005, "Emma", "IT", 89000, 8],
        [1002, "Liam", "IT", 81000, 6],
        [1006, "Lucas", "Finance", 76000, 5],
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1004, "Noah", "HR", 64000, 5]
      ],
      hints: ["Salary is column 4 within A2:E7.", "Use -1 for descending order."],
      solutionFormula: "=SORT(A2:E7,4,-1)",
      acceptedFunctionSets: [["SORT"]]
    },
    {
      id: "sortby-salary-descending-01",
      title: "Sort by an Aligned Salary Range",
      functionCategory: "SORTBY",
      difficulty: "Intermediate",
      validationType: "arrayFormula",
      prompt: "Sort A2:E7 using D2:D7 from highest salary to lowest.",
      targetCell: "H15",
      expectedShape: [6, 5],
      expectedValues: [
        [1005, "Emma", "IT", 89000, 8],
        [1002, "Liam", "IT", 81000, 6],
        [1006, "Lucas", "Finance", 76000, 5],
        [1001, "Maya", "Finance", 72000, 4],
        [1003, "Sofia", "Finance", 68000, 3],
        [1004, "Noah", "HR", 64000, 5]
      ],
      hints: ["The returned array is A2:E7.", "Use D2:D7 as the separate sort key and -1 as its order."],
      solutionFormula: "=SORTBY(A2:E7,D2:D7,-1)",
      acceptedFunctionSets: [["SORTBY"]]
    },
    {
      id: "unique-departments-01",
      title: "List Unique Departments",
      functionCategory: "UNIQUE",
      difficulty: "Beginner",
      validationType: "arrayFormula",
      prompt: "Return each department from C2:C7 once, preserving first-occurrence order.",
      targetCell: "H15",
      expectedShape: [3, 1],
      expectedValues: [["Finance"], ["IT"], ["HR"]],
      hints: ["UNIQUE needs only the department range for this result."],
      solutionFormula: "=UNIQUE(C2:C7)",
      acceptedFunctionSets: [["UNIQUE"]]
    },
    {
      id: "format-percentage-01",
      title: "Format a Percentage",
      functionCategory: "Percentage Format",
      difficulty: "Beginner",
      validationType: "format",
      prompt: "Apply Percentage formatting with two decimal places to the value in H4.",
      targetCell: "H4",
      expectedValue: 0.075,
      expectedNumberFormat: "Percentage",
      expectedDecimals: 2,
      hints: ["Do not change the underlying 0.075 value.", "Use the % toolbar button or format dropdown."],
      solutionFormat: "Percentage with 2 decimal places",
      acceptedFunctionSets: [],
      setup: [{ cell: "H4", value: "0.075" }]
    },
    {
      id: "format-currency-01",
      title: "Format a Salary as Currency",
      functionCategory: "Currency Format",
      difficulty: "Beginner",
      validationType: "format",
      prompt: "Apply Currency formatting with two decimal places to the salary in H4.",
      targetCell: "H4",
      expectedValue: 72000,
      expectedNumberFormat: "Currency",
      expectedDecimals: 2,
      hints: ["Keep the underlying value at 72000.", "Use the $ toolbar button or format dropdown."],
      solutionFormat: "Currency with 2 decimal places",
      acceptedFunctionSets: [],
      setup: [{ cell: "H4", value: "72000" }]
    }
  ];

  global.ExcelExercises = exercises;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = exercises;
  }
})(typeof window === "undefined" ? globalThis : window);
