#!/usr/bin/env python3
"""Generate reproducible numerical assets for riemann-zeta-function.html.

Displayed zeta zeros and Hardy Z values are computed with mpmath. Prime data are
generated by an exact sieve. Random-matrix spacings use a fixed NumPy seed.
"""

from __future__ import annotations

import colorsys
import json
import math
import os
from datetime import date
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/riemann-zeta-matplotlib")

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mpmath as mp
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
IMAGES = ROOT / "images"
PAPER = "#fffdf9"
INK = "#1b1b1b"
MUTED = "#66645f"
BLUE = "#1d4f91"
ORANGE = "#b26935"
GREEN = "#287352"
RED = "#a34f4f"
SEED = 1859
ZERO_COUNT = 500


def write_json(name: str, payload: dict) -> None:
    (DATA / name).write_text(
        json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="ascii"
    )


def zero_data() -> tuple[list[float], list[float]]:
    mp.mp.dps = 40
    ordinates = [float(mp.im(mp.zetazero(index))) for index in range(1, ZERO_COUNT + 1)]
    trusted = [14.134725141734693, 21.022039638771555, 25.01085758014569]
    for found, expected in zip(ordinates[:3], trusted):
        assert abs(found - expected) < 2e-13
    assert all(right > left for left, right in zip(ordinates, ordinates[1:]))

    normalized = [
        (ordinates[index + 1] - gamma)
        * math.log(gamma / (2 * math.pi))
        / (2 * math.pi)
        for index, gamma in enumerate(ordinates[:-1])
        if index >= 50
    ]
    write_json(
        "first-zeros.json",
        {
            "description": "Positive ordinates of the first nontrivial zeta zeros on the critical line.",
            "method": "mpmath.zetazero at 40 decimal digits; JSON stores double-precision values.",
            "count": len(ordinates),
            "counting": "Increasing positive ordinates, with multiplicity as returned by mpmath.",
            "ordinates": ordinates,
        },
    )
    write_json(
        "zero-spacings.json",
        {
            "description": "Consecutive zero gaps and locally normalized gaps.",
            "normalization": "(gamma[n+1]-gamma[n])*log(gamma[n]/(2*pi))/(2*pi)",
            "source_zero_indices": [51, ZERO_COUNT],
            "sample_size": len(normalized),
            "height_range": [ordinates[50], ordinates[-1]],
            "raw_gaps": [b - a for a, b in zip(ordinates[50:-1], ordinates[51:])],
            "normalized_gaps": normalized,
            "caveat": "Finite low-height data; numerical agreement is not a proof of RH or GUE statistics.",
        },
    )
    return ordinates, normalized


def z_function_data(ordinates: list[float]) -> None:
    mp.mp.dps = 30
    ts = np.linspace(0.0, 70.0, 1401)
    values = [float(mp.siegelz(float(t))) for t in ts]
    assert all(abs(float(mp.siegelz(gamma))) < 2e-11 for gamma in ordinates[:10])
    write_json(
        "z-function-samples.json",
        {
            "description": "Hardy Z(t) samples on 0 <= t <= 70.",
            "definition": "Z(t)=exp(i*theta(t))*zeta(1/2+i*t), using mpmath's siegelz convention.",
            "step": float(ts[1] - ts[0]),
            "t": ts.tolist(),
            "z": values,
            "known_zeros_in_range": [gamma for gamma in ordinates if gamma <= 70],
        },
    )


def sieve(limit: int) -> list[int]:
    prime = bytearray(b"\x01") * (limit + 1)
    prime[:2] = b"\x00\x00"
    for value in range(2, math.isqrt(limit) + 1):
        if prime[value]:
            prime[value * value : limit + 1 : value] = b"\x00" * (
                ((limit - value * value) // value) + 1
            )
    return [value for value, is_prime in enumerate(prime) if is_prime]


def li_offset(x: float) -> float:
    """The conventional logarithmic integral li(x), principal-valued through 1."""
    return float(mp.li(x))


def prime_and_explicit_data(ordinates: list[float]) -> None:
    limit = 500
    primes = sieve(limit)
    prime_set = set(primes)
    mangoldt = [0.0] * (limit + 1)
    for prime in primes:
        power = prime
        while power <= limit:
            mangoldt[power] = math.log(prime)
            power *= prime

    pi_count = 0
    psi_value = 0.0
    rows = []
    for x in range(2, limit + 1):
        if x in prime_set:
            pi_count += 1
        psi_value += mangoldt[x]
        rows.append(
            {
                "x": x,
                "pi": pi_count,
                "x_over_log_x": x / math.log(x),
                "li": li_offset(x),
                "psi": psi_value,
                "psi0": psi_value - 0.5 * mangoldt[x],
            }
        )
    write_json(
        "prime-counting.json",
        {
            "description": "Exact prime counts and Chebyshev psi values through 500.",
            "li_convention": "li(x)=PV integral from 0 to x of dt/log(t), evaluated by mpmath.li.",
            "limit": limit,
            "primes": primes,
            "rows": rows,
        },
    )

    zero_pair_counts = [0, 1, 3, 10, 30]
    curves: dict[str, list[float]] = {}
    xs = list(range(2, limit + 1))
    for pair_count in zero_pair_counts:
        curve = []
        for x in xs:
            value = float(x - math.log(2 * math.pi) - 0.5 * math.log(1 - x ** -2))
            for gamma in ordinates[:pair_count]:
                rho = 0.5 + 1j * gamma
                value -= 2 * (x ** rho / rho).real
            curve.append(value)
        curves[str(pair_count)] = curve
    write_json(
        "explicit-formula.json",
        {
            "description": "Finite symmetric zero-pair approximations to the explicit formula for psi_0(x).",
            "formula": "x - 2*Re(sum_{gamma>0} x^(1/2+i*gamma)/(1/2+i*gamma)) - log(2*pi) - 0.5*log(1-x^-2)",
            "x": xs,
            "zero_pair_counts": zero_pair_counts,
            "approximations": curves,
            "caveat": "Each curve is truncated and uses critical-line zeros only. It is a teaching approximation, not the full symmetric zero sum.",
        },
    )


def zero_count_data(ordinates: list[float]) -> None:
    t_values = np.linspace(10.0, ordinates[-1] + 3.0, 900)
    exact = np.searchsorted(np.asarray(ordinates), t_values, side="right")

    def main_term(t: float) -> float:
        return t / (2 * math.pi) * math.log(t / (2 * math.pi)) - t / (2 * math.pi) + 7 / 8

    smooth = np.asarray([main_term(float(t)) for t in t_values])
    assert int(exact[-1]) == len(ordinates)
    write_json(
        "zero-counts.json",
        {
            "description": "Zero-count staircase from the first 500 computed ordinates and the smooth Riemann-von Mangoldt main term.",
            "counting": "N(T) counts ordinates 0 < gamma <= T with multiplicity.",
            "t": t_values.tolist(),
            "exact": exact.astype(int).tolist(),
            "smooth": smooth.tolist(),
            "residual": (exact - smooth).tolist(),
            "maximum_certified_by_dataset": ordinates[-1],
        },
    )


def random_matrix_data(normalized_zeta_gaps: list[float]) -> list[float]:
    rng = np.random.default_rng(SEED)
    size = 40
    matrix_count = 40
    gaps: list[float] = []
    for _ in range(matrix_count):
        gaussian = rng.normal(size=(size, size)) + 1j * rng.normal(size=(size, size))
        q, r = np.linalg.qr(gaussian)
        diagonal = np.diag(r)
        phases = diagonal / np.abs(diagonal)
        unitary = q @ np.diag(np.conjugate(phases))
        angles = np.sort(np.angle(np.linalg.eigvals(unitary)) % (2 * math.pi))
        circular = np.diff(np.r_[angles, angles[0] + 2 * math.pi])
        gaps.extend((circular * size / (2 * math.pi)).tolist())
    assert len(gaps) == size * matrix_count
    assert abs(float(np.mean(gaps)) - 1.0) < 1e-12
    write_json(
        "random-matrix-spacings.json",
        {
            "description": "Normalized eigenangle gaps from seeded Haar-unitary matrices (CUE).",
            "model_note": "CUE finite matrices share the GUE sine-kernel local limit after unfolding; this is simulated comparison data.",
            "seed": SEED,
            "matrix_size": size,
            "matrix_count": matrix_count,
            "sample_size": len(gaps),
            "normalized_gaps": gaps,
            "zeta_comparison_sample_size": len(normalized_zeta_gaps),
        },
    )
    return gaps


def domain_coloring() -> None:
    width, height = 520, 430
    sigmas = np.linspace(-4.5, 2.0, width)
    heights = np.linspace(32.0, -32.0, height)
    rgb = np.empty((height, width, 3), dtype=float)
    for row, t in enumerate(heights):
        for col, sigma in enumerate(sigmas):
            try:
                value = complex(mp.fp.zeta(complex(float(sigma), float(t))))
                magnitude = abs(value)
                phase = (math.atan2(value.imag, value.real) + math.pi) / (2 * math.pi)
                light = 0.20 + 0.63 * (2 / math.pi) * math.atan(magnitude)
                contour = abs((math.log10(max(magnitude, 1e-12)) * 3) % 1 - 0.5)
                if contour > 0.46:
                    light *= 0.74
                saturation = 0.82
                rgb[row, col] = colorsys.hls_to_rgb(phase, light, saturation)
            except (ValueError, ZeroDivisionError, OverflowError):
                rgb[row, col] = (1.0, 1.0, 1.0)

    fig, ax = plt.subplots(figsize=(10.8, 8.0), facecolor=PAPER)
    ax.imshow(rgb, extent=[-4.5, 2.0, -32, 32], origin="upper", aspect="auto")
    ax.axvspan(0, 1, color="white", alpha=0.08)
    ax.axvline(0, color="white", lw=1.1, alpha=0.8)
    ax.axvline(1, color="white", lw=1.1, alpha=0.8)
    ax.axvline(0.5, color="white", lw=1.6, ls="--", alpha=0.95)
    ax.scatter([1], [0], marker="x", s=80, color="white", linewidths=2.2, label="pole at 1")
    for value in [-2, -4]:
        ax.scatter([value], [0], s=34, facecolor="black", edgecolor="white", linewidth=1)
    ax.set_xlabel(r"real part $\sigma$", color=INK)
    ax.set_ylabel(r"imaginary part $t$", color=INK)
    ax.set_title("Magnitude and phase of the analytically continued zeta function", color=INK, pad=12)
    ax.tick_params(colors=MUTED)
    for spine in ax.spines.values():
        spine.set_color("#6f6b64")
    fig.tight_layout()
    fig.savefig(IMAGES / "zeta-domain-coloring.png", dpi=150, bbox_inches="tight", facecolor=PAPER)
    plt.close(fig)


def fallback_figures(
    ordinates: list[float], normalized_zeta: list[float], matrix_gaps: list[float]
) -> None:
    fig, ax = plt.subplots(figsize=(10.5, 5.1), facecolor=PAPER)
    ax.axvspan(0, 1, color="#e9f0f8", alpha=0.9, label="critical strip")
    ax.axvline(0.5, color=BLUE, ls="--", lw=2, label="critical line")
    shown = [gamma for gamma in ordinates if gamma <= 50]
    ax.scatter([0.5] * len(shown), shown, color=RED, s=36, zorder=3, label="computed zeros")
    ax.scatter([-2, -4, -6], [0, 0, 0], color=GREEN, s=46, label="trivial zeros")
    ax.set(xlim=(-6.5, 1.7), ylim=(-2, 52), xlabel=r"$\operatorname{Re}(s)$", ylabel=r"$\operatorname{Im}(s)$")
    ax.set_title("Two families of zeta zeros", color=INK)
    ax.grid(color="#e4ded3", lw=0.8)
    ax.legend(frameon=False, ncol=2)
    fig.tight_layout()
    fig.savefig(IMAGES / "zero-landscape-overview.png", dpi=150, bbox_inches="tight", facecolor=PAPER)
    plt.close(fig)

    explicit = json.loads((DATA / "explicit-formula.json").read_text())
    prime = json.loads((DATA / "prime-counting.json").read_text())
    xs = np.asarray(explicit["x"])
    psi = np.asarray([row["psi0"] for row in prime["rows"]])
    fig, ax = plt.subplots(figsize=(10.5, 5.1), facecolor=PAPER)
    ax.step(xs, psi, where="mid", color=INK, lw=1.5, label=r"exact midpoint $\psi_0(x)$")
    for count, color in [(0, ORANGE), (3, BLUE), (30, GREEN)]:
        ax.plot(xs, explicit["approximations"][str(count)], color=color, lw=1.5, label=f"{count} zero pairs")
    ax.set(xlabel="x", ylabel="value", title="Truncated zero sums recover prime-power oscillations")
    ax.grid(color="#e4ded3", lw=0.8)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(IMAGES / "explicit-formula-fallback.png", dpi=150, bbox_inches="tight", facecolor=PAPER)
    plt.close(fig)

    bins = np.linspace(0, 3.2, 25)
    fig, ax = plt.subplots(figsize=(10.5, 5.1), facecolor=PAPER)
    ax.hist(normalized_zeta, bins=bins, density=True, histtype="step", lw=2.2, color=BLUE, label="zeta gaps")
    ax.hist(matrix_gaps, bins=bins, density=True, histtype="step", lw=2.2, color=ORANGE, label="seeded CUE gaps")
    ax.set(xlabel="normalized consecutive gap", ylabel="density", title="Finite spacing comparison")
    ax.grid(color="#e4ded3", lw=0.8)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(IMAGES / "zero-spacing-fallback.png", dpi=150, bbox_inches="tight", facecolor=PAPER)
    plt.close(fig)


def manifest() -> None:
    write_json(
        "source-manifest.json",
        {
            "generated_on": date.today().isoformat(),
            "generator": "scripts/generate_numerical_assets.py",
            "precision": "40 decimal digits for zero generation; JSON values stored as doubles",
            "zero_count": ZERO_COUNT,
            "random_seed": SEED,
            "packages": {"mpmath": mp.__version__, "numpy": np.__version__, "matplotlib": matplotlib.__version__},
            "classifications": {
                "first-zeros.json": "numerically computed",
                "z-function-samples.json": "numerically computed",
                "zero-counts.json": "computed from included zeros; finite range",
                "prime-counting.json": "exact integer sieve plus numerical smooth approximations",
                "explicit-formula.json": "truncated numerical approximation",
                "zero-spacings.json": "numerically computed finite sample",
                "random-matrix-spacings.json": "deterministic seeded simulation",
                "zeta-domain-coloring.png": "numerically computed visualization",
                "other PNG files": "static fallbacks generated from the JSON datasets",
            },
        },
    )


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    IMAGES.mkdir(parents=True, exist_ok=True)
    mp.mp.dps = 40
    assert abs(mp.zeta(2) - mp.pi**2 / 6) < mp.mpf("1e-35")
    assert abs(mp.zeta(4) - mp.pi**4 / 90) < mp.mpf("1e-35")
    assert abs(mp.zeta(mp.mpc("0.5", "14.134725141734693790"))) < mp.mpf("1e-15")
    assert mp.zeta(mp.conj(mp.mpc("0.7", "12.3"))) == mp.conj(mp.zeta(mp.mpc("0.7", "12.3")))

    ordinates, normalized = zero_data()
    z_function_data(ordinates)
    prime_and_explicit_data(ordinates)
    zero_count_data(ordinates)
    matrix_gaps = random_matrix_data(normalized)
    domain_coloring()
    fallback_figures(ordinates, normalized, matrix_gaps)
    manifest()
    print(f"Generated numerical assets with {len(ordinates)} zeta zeros and seed {SEED}.")


if __name__ == "__main__":
    main()
